// AUTO-GENERATED addon pack for `weapon_parts_overhaul` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
import type { CommaSeparatedString, Section } from 'anomaly-packer'

declare global {
  interface ItemsSettingsDeathGenericIni {
    weapon_drop_condition: {
      experienced: CommaSeparatedString<string[]>
      expert: CommaSeparatedString<string[]>
      legend: CommaSeparatedString<string[]>
      master: CommaSeparatedString<string[]>
      novice: CommaSeparatedString<string[]>
      professional: CommaSeparatedString<string[]>
      trainee: CommaSeparatedString<string[]>
      veteran: CommaSeparatedString<string[]>
    }
    outfit_drop_condition: {
      experienced: CommaSeparatedString<string[]>
      expert: CommaSeparatedString<string[]>
      legend: CommaSeparatedString<string[]>
      master: CommaSeparatedString<string[]>
      novice: CommaSeparatedString<string[]>
      professional: CommaSeparatedString<string[]>
      trainee: CommaSeparatedString<string[]>
      veteran: CommaSeparatedString<string[]>
    }
    item_count: {
      adrenalin: CommaSeparatedString<string[]>
      af_aac: CommaSeparatedString<string[]>
      af_aam: CommaSeparatedString<string[]>
      af_atom: CommaSeparatedString<string[]>
      af_baloon: CommaSeparatedString<string[]>
      af_baloon_af_aac: CommaSeparatedString<string[]>
      af_baloon_af_aam: CommaSeparatedString<string[]>
      af_baloon_af_iam: CommaSeparatedString<string[]>
      af_baloon_lead_box: CommaSeparatedString<string[]>
      af_bat: CommaSeparatedString<string[]>
      af_black_angel: CommaSeparatedString<string[]>
      af_black_spray: CommaSeparatedString<string[]>
      af_black_spray_lead_box: CommaSeparatedString<string[]>
      af_blood: CommaSeparatedString<string[]>
      af_blood_af_aac: CommaSeparatedString<string[]>
      af_blood_af_aam: CommaSeparatedString<string[]>
      af_blood_af_iam: CommaSeparatedString<string[]>
      af_blood_lead_box: CommaSeparatedString<string[]>
      af_bracelet: CommaSeparatedString<string[]>
      af_bracelet_lead_box: CommaSeparatedString<string[]>
      af_camelbak: CommaSeparatedString<string[]>
      af_cell: CommaSeparatedString<string[]>
      af_chelust: CommaSeparatedString<string[]>
      af_cocoon: CommaSeparatedString<string[]>
      af_compass_af_aac: CommaSeparatedString<string[]>
      af_compass_af_aam: CommaSeparatedString<string[]>
      af_compass_af_iam: CommaSeparatedString<string[]>
      af_compass_lead_box: CommaSeparatedString<string[]>
      af_cooler: CommaSeparatedString<string[]>
      af_cristall: CommaSeparatedString<string[]>
      af_cristall_af_aac: CommaSeparatedString<string[]>
      af_cristall_af_aam: CommaSeparatedString<string[]>
      af_cristall_af_iam: CommaSeparatedString<string[]>
      af_cristall_flower: CommaSeparatedString<string[]>
      af_cristall_flower_af_aac: CommaSeparatedString<string[]>
      af_cristall_flower_af_aam: CommaSeparatedString<string[]>
      af_cristall_flower_af_iam: CommaSeparatedString<string[]>
      af_cristall_flower_lead_box: CommaSeparatedString<string[]>
      af_cristall_lead_box: CommaSeparatedString<string[]>
      af_death_lamp: CommaSeparatedString<string[]>
      af_dummy_battery: CommaSeparatedString<string[]>
      af_dummy_battery_af_aac: CommaSeparatedString<string[]>
      af_dummy_battery_af_aam: CommaSeparatedString<string[]>
      af_dummy_battery_af_iam: CommaSeparatedString<string[]>
      af_dummy_battery_lead_box: CommaSeparatedString<string[]>
      af_dummy_dummy: CommaSeparatedString<string[]>
      af_dummy_dummy_af_aac: CommaSeparatedString<string[]>
      af_dummy_dummy_af_aam: CommaSeparatedString<string[]>
      af_dummy_dummy_af_iam: CommaSeparatedString<string[]>
      af_dummy_dummy_lead_box: CommaSeparatedString<string[]>
      af_dummy_glassbeads: CommaSeparatedString<string[]>
      af_dummy_glassbeads_af_aac: CommaSeparatedString<string[]>
      af_dummy_glassbeads_af_aam: CommaSeparatedString<string[]>
      af_dummy_glassbeads_af_iam: CommaSeparatedString<string[]>
      af_dummy_glassbeads_lead_box: CommaSeparatedString<string[]>
      af_ear: CommaSeparatedString<string[]>
      af_electra_flash: CommaSeparatedString<string[]>
      af_electra_flash_af_aac: CommaSeparatedString<string[]>
      af_electra_flash_af_aam: CommaSeparatedString<string[]>
      af_electra_flash_af_iam: CommaSeparatedString<string[]>
      af_electra_flash_lead_box: CommaSeparatedString<string[]>
      af_electra_moonlight: CommaSeparatedString<string[]>
      af_electra_moonlight_af_aac: CommaSeparatedString<string[]>
      af_electra_moonlight_af_aam: CommaSeparatedString<string[]>
      af_electra_moonlight_af_iam: CommaSeparatedString<string[]>
      af_electra_moonlight_lead_box: CommaSeparatedString<string[]>
      af_electra_sparkler: CommaSeparatedString<string[]>
      af_electra_sparkler_af_aac: CommaSeparatedString<string[]>
      af_electra_sparkler_af_aam: CommaSeparatedString<string[]>
      af_electra_sparkler_af_iam: CommaSeparatedString<string[]>
      af_electra_sparkler_lead_box: CommaSeparatedString<string[]>
      af_elektron: CommaSeparatedString<string[]>
      af_empty: CommaSeparatedString<string[]>
      af_empty_lead_box: CommaSeparatedString<string[]>
      af_eye: CommaSeparatedString<string[]>
      af_eye_af_aac: CommaSeparatedString<string[]>
      af_eye_af_aam: CommaSeparatedString<string[]>
      af_eye_af_iam: CommaSeparatedString<string[]>
      af_eye_lead_box: CommaSeparatedString<string[]>
      af_fire: CommaSeparatedString<string[]>
      af_fire_af_aac: CommaSeparatedString<string[]>
      af_fire_af_aam: CommaSeparatedString<string[]>
      af_fire_af_iam: CommaSeparatedString<string[]>
      af_fire_lead_box: CommaSeparatedString<string[]>
      af_fire_loop: CommaSeparatedString<string[]>
      af_fireball: CommaSeparatedString<string[]>
      af_fireball_af_aac: CommaSeparatedString<string[]>
      af_fireball_af_aam: CommaSeparatedString<string[]>
      af_fireball_af_iam: CommaSeparatedString<string[]>
      af_fireball_lead_box: CommaSeparatedString<string[]>
      af_fonar: CommaSeparatedString<string[]>
      af_fountain: CommaSeparatedString<string[]>
      af_frames: CommaSeparatedString<string[]>
      af_freon: CommaSeparatedString<string[]>
      af_full_empty: CommaSeparatedString<string[]>
      af_full_empty_lead_box: CommaSeparatedString<string[]>
      af_fuzz_kolobok: CommaSeparatedString<string[]>
      af_fuzz_kolobok_af_aac: CommaSeparatedString<string[]>
      af_fuzz_kolobok_af_aam: CommaSeparatedString<string[]>
      af_fuzz_kolobok_af_iam: CommaSeparatedString<string[]>
      af_fuzz_kolobok_lead_box: CommaSeparatedString<string[]>
      af_generator: CommaSeparatedString<string[]>
      af_glass: CommaSeparatedString<string[]>
      af_glass_af_aac: CommaSeparatedString<string[]>
      af_glass_af_aam: CommaSeparatedString<string[]>
      af_glass_af_iam: CommaSeparatedString<string[]>
      af_glass_lead_box: CommaSeparatedString<string[]>
      af_gold_fish: CommaSeparatedString<string[]>
      af_gold_fish_af_aac: CommaSeparatedString<string[]>
      af_gold_fish_af_aam: CommaSeparatedString<string[]>
      af_gold_fish_af_iam: CommaSeparatedString<string[]>
      af_gold_fish_lead_box: CommaSeparatedString<string[]>
      af_grapes: CommaSeparatedString<string[]>
      af_gravi: CommaSeparatedString<string[]>
      af_gravi_af_aac: CommaSeparatedString<string[]>
      af_gravi_af_aam: CommaSeparatedString<string[]>
      af_gravi_af_iam: CommaSeparatedString<string[]>
      af_gravi_lead_box: CommaSeparatedString<string[]>
      af_grid: CommaSeparatedString<string[]>
      af_iam: CommaSeparatedString<string[]>
      af_ice: CommaSeparatedString<string[]>
      af_ice_af_aac: CommaSeparatedString<string[]>
      af_ice_af_aam: CommaSeparatedString<string[]>
      af_ice_af_iam: CommaSeparatedString<string[]>
      af_ice_lead_box: CommaSeparatedString<string[]>
      af_itcher: CommaSeparatedString<string[]>
      af_itcher_lead_box: CommaSeparatedString<string[]>
      af_kevlar: CommaSeparatedString<string[]>
      af_kislushka: CommaSeparatedString<string[]>
      af_kogot: CommaSeparatedString<string[]>
      af_lighthouse: CommaSeparatedString<string[]>
      af_lobster_eyes: CommaSeparatedString<string[]>
      af_lobster_eyes_lead_box: CommaSeparatedString<string[]>
      af_medallion: CommaSeparatedString<string[]>
      af_medusa: CommaSeparatedString<string[]>
      af_medusa_af_aac: CommaSeparatedString<string[]>
      af_medusa_af_aam: CommaSeparatedString<string[]>
      af_medusa_af_iam: CommaSeparatedString<string[]>
      af_medusa_lead_box: CommaSeparatedString<string[]>
      af_mincer_meat: CommaSeparatedString<string[]>
      af_mincer_meat_af_aac: CommaSeparatedString<string[]>
      af_mincer_meat_af_aam: CommaSeparatedString<string[]>
      af_mincer_meat_af_iam: CommaSeparatedString<string[]>
      af_mincer_meat_lead_box: CommaSeparatedString<string[]>
      af_moh: CommaSeparatedString<string[]>
      af_night_star: CommaSeparatedString<string[]>
      af_night_star_af_aac: CommaSeparatedString<string[]>
      af_night_star_af_aam: CommaSeparatedString<string[]>
      af_night_star_af_iam: CommaSeparatedString<string[]>
      af_night_star_lead_box: CommaSeparatedString<string[]>
      af_oasis_heart_af_aac: CommaSeparatedString<string[]>
      af_oasis_heart_af_aam: CommaSeparatedString<string[]>
      af_oasis_heart_af_iam: CommaSeparatedString<string[]>
      af_oasis_heart_lead_box: CommaSeparatedString<string[]>
      af_peas: CommaSeparatedString<string[]>
      af_pin: CommaSeparatedString<string[]>
      af_pin_lead_box: CommaSeparatedString<string[]>
      af_plates: CommaSeparatedString<string[]>
      af_quest_b14_twisted_af_aac: CommaSeparatedString<string[]>
      af_quest_b14_twisted_af_aam: CommaSeparatedString<string[]>
      af_quest_b14_twisted_af_iam: CommaSeparatedString<string[]>
      af_quest_b14_twisted_lead_box: CommaSeparatedString<string[]>
      af_repei: CommaSeparatedString<string[]>
      af_ring: CommaSeparatedString<string[]>
      af_ring_lead_box: CommaSeparatedString<string[]>
      af_sandstone: CommaSeparatedString<string[]>
      af_serofim: CommaSeparatedString<string[]>
      af_signet: CommaSeparatedString<string[]>
      af_skull_miser: CommaSeparatedString<string[]>
      af_soul: CommaSeparatedString<string[]>
      af_soul_af_aac: CommaSeparatedString<string[]>
      af_soul_af_aam: CommaSeparatedString<string[]>
      af_soul_af_iam: CommaSeparatedString<string[]>
      af_soul_lead_box: CommaSeparatedString<string[]>
      af_spaika: CommaSeparatedString<string[]>
      af_sponge: CommaSeparatedString<string[]>
      af_sponge_lead_box: CommaSeparatedString<string[]>
      af_star_phantom: CommaSeparatedString<string[]>
      af_sun: CommaSeparatedString<string[]>
      af_surge: CommaSeparatedString<string[]>
      af_tapeworm: CommaSeparatedString<string[]>
      af_vyvert: CommaSeparatedString<string[]>
      af_vyvert_af_aac: CommaSeparatedString<string[]>
      af_vyvert_af_aam: CommaSeparatedString<string[]>
      af_vyvert_af_iam: CommaSeparatedString<string[]>
      af_vyvert_lead_box: CommaSeparatedString<string[]>
      af_zhelch: CommaSeparatedString<string[]>
      akvatab__1: CommaSeparatedString<string[]>
      'ammo_11.43x23_fmj': CommaSeparatedString<string[]>
      'ammo_11.43x23_fmj_bad': CommaSeparatedString<string[]>
      'ammo_11.43x23_hydro': CommaSeparatedString<string[]>
      'ammo_11.43x23_hydro_bad': CommaSeparatedString<string[]>
      'ammo_12.7x55_ap': CommaSeparatedString<string[]>
      'ammo_12.7x55_ap_bad': CommaSeparatedString<string[]>
      'ammo_12.7x55_fmj': CommaSeparatedString<string[]>
      'ammo_12.7x55_fmj_bad': CommaSeparatedString<string[]>
      ammo_12x70_buck: CommaSeparatedString<string[]>
      ammo_12x70_buck_bad: CommaSeparatedString<string[]>
      ammo_12x76_bull: CommaSeparatedString<string[]>
      ammo_12x76_dart: CommaSeparatedString<string[]>
      ammo_12x76_dart_bad: CommaSeparatedString<string[]>
      ammo_12x76_zhekan: CommaSeparatedString<string[]>
      ammo_12x76_zhekan_bad: CommaSeparatedString<string[]>
      ammo_357_hp_mag: CommaSeparatedString<string[]>
      ammo_357_hp_mag_bad: CommaSeparatedString<string[]>
      'ammo_5.45x39_ap': CommaSeparatedString<string[]>
      'ammo_5.45x39_ap_bad': CommaSeparatedString<string[]>
      'ammo_5.45x39_ep': CommaSeparatedString<string[]>
      'ammo_5.45x39_ep_bad': CommaSeparatedString<string[]>
      'ammo_5.45x39_fmj': CommaSeparatedString<string[]>
      'ammo_5.45x39_fmj_bad': CommaSeparatedString<string[]>
      'ammo_5.56x45_ap': CommaSeparatedString<string[]>
      'ammo_5.56x45_ap_bad': CommaSeparatedString<string[]>
      'ammo_5.56x45_fmj': CommaSeparatedString<string[]>
      'ammo_5.56x45_fmj_bad': CommaSeparatedString<string[]>
      'ammo_5.56x45_ss190': CommaSeparatedString<string[]>
      'ammo_5.56x45_ss190_bad': CommaSeparatedString<string[]>
      'ammo_5.7x28_ss190': CommaSeparatedString<string[]>
      'ammo_5.7x28_ss190_bad': CommaSeparatedString<string[]>
      'ammo_5.7x28_ss195': CommaSeparatedString<string[]>
      'ammo_5.7x28_ss195_bad': CommaSeparatedString<string[]>
      'ammo_7.62x25_p': CommaSeparatedString<string[]>
      'ammo_7.62x25_p_bad': CommaSeparatedString<string[]>
      'ammo_7.62x25_ps': CommaSeparatedString<string[]>
      'ammo_7.62x25_ps_bad': CommaSeparatedString<string[]>
      'ammo_7.62x39_ap': CommaSeparatedString<string[]>
      'ammo_7.62x39_ap_bad': CommaSeparatedString<string[]>
      'ammo_7.62x39_fmj': CommaSeparatedString<string[]>
      'ammo_7.62x39_fmj_bad': CommaSeparatedString<string[]>
      'ammo_7.62x51_ap': CommaSeparatedString<string[]>
      'ammo_7.62x51_ap_bad': CommaSeparatedString<string[]>
      'ammo_7.62x51_fmj': CommaSeparatedString<string[]>
      'ammo_7.62x51_fmj_bad': CommaSeparatedString<string[]>
      'ammo_7.62x54_7h1': CommaSeparatedString<string[]>
      'ammo_7.62x54_7h1_bad': CommaSeparatedString<string[]>
      'ammo_7.62x54_7h14': CommaSeparatedString<string[]>
      'ammo_7.62x54_7h14_bad': CommaSeparatedString<string[]>
      'ammo_7.62x54_ap': CommaSeparatedString<string[]>
      'ammo_7.62x54_ap_bad': CommaSeparatedString<string[]>
      'ammo_7.92x33_ap': CommaSeparatedString<string[]>
      'ammo_7.92x33_ap_bad': CommaSeparatedString<string[]>
      'ammo_7.92x33_fmj': CommaSeparatedString<string[]>
      'ammo_7.92x33_fmj_bad': CommaSeparatedString<string[]>
      ammo_9x18_ap: CommaSeparatedString<string[]>
      ammo_9x18_ap_bad: CommaSeparatedString<string[]>
      ammo_9x18_fmj: CommaSeparatedString<string[]>
      ammo_9x18_fmj_bad: CommaSeparatedString<string[]>
      ammo_9x18_pmm: CommaSeparatedString<string[]>
      ammo_9x18_pmm_bad: CommaSeparatedString<string[]>
      ammo_9x19_ap: CommaSeparatedString<string[]>
      ammo_9x19_ap_bad: CommaSeparatedString<string[]>
      ammo_9x19_fmj: CommaSeparatedString<string[]>
      ammo_9x19_fmj_bad: CommaSeparatedString<string[]>
      ammo_9x19_pbp: CommaSeparatedString<string[]>
      ammo_9x19_pbp_bad: CommaSeparatedString<string[]>
      ammo_9x39_ap: CommaSeparatedString<string[]>
      ammo_9x39_ap_bad: CommaSeparatedString<string[]>
      ammo_9x39_pab9: CommaSeparatedString<string[]>
      ammo_9x39_pab9_bad: CommaSeparatedString<string[]>
      ammo_gauss: CommaSeparatedString<string[]>
      ammo_gauss_bad: CommaSeparatedString<string[]>
      ammo_m209: CommaSeparatedString<string[]>
      ammo_m209_bad: CommaSeparatedString<string[]>
      ammo_magnum_300: CommaSeparatedString<string[]>
      ammo_magnum_300_bad: CommaSeparatedString<string[]>
      'ammo_og-7b': CommaSeparatedString<string[]>
      'ammo_og-7b_bad': CommaSeparatedString<string[]>
      ammo_pkm_100: CommaSeparatedString<string[]>
      ammo_pkm_100_bad: CommaSeparatedString<string[]>
      'ammo_vog-25': CommaSeparatedString<string[]>
      'ammo_vog-25_bad': CommaSeparatedString<string[]>
      antirad: CommaSeparatedString<string[]>
      armor_repair_fa__1: CommaSeparatedString<string[]>
      armor_repair_pro__1: CommaSeparatedString<string[]>
      army_patch: CommaSeparatedString<string[]>
      ball_hammer: CommaSeparatedString<string[]>
      bandage: CommaSeparatedString<string[]>
      bandit_patch: CommaSeparatedString<string[]>
      batteries_dead: CommaSeparatedString<string[]>
      beadspread: CommaSeparatedString<string[]>
      beans: CommaSeparatedString<string[]>
      beer: CommaSeparatedString<string[]>
      bolt: CommaSeparatedString<string[]>
      bolt_bullet: CommaSeparatedString<string[]>
      boots: CommaSeparatedString<string[]>
      bottle_metal__1: CommaSeparatedString<string[]>
      box_matches__1: CommaSeparatedString<string[]>
      box_matches__2: CommaSeparatedString<string[]>
      box_matches__3: CommaSeparatedString<string[]>
      box_matches__4: CommaSeparatedString<string[]>
      box_matches__5: CommaSeparatedString<string[]>
      bread: CommaSeparatedString<string[]>
      breadold: CommaSeparatedString<string[]>
      broken_detector: CommaSeparatedString<string[]>
      caffeine__1: CommaSeparatedString<string[]>
      cards: CommaSeparatedString<string[]>
      charcoal__1: CommaSeparatedString<string[]>
      charcoal__2: CommaSeparatedString<string[]>
      charcoal__3: CommaSeparatedString<string[]>
      chili: CommaSeparatedString<string[]>
      chocolate: CommaSeparatedString<string[]>
      chocolate_p: CommaSeparatedString<string[]>
      cigar: CommaSeparatedString<string[]>
      cigar1__1: CommaSeparatedString<string[]>
      cigar2__1: CommaSeparatedString<string[]>
      cigar3__1: CommaSeparatedString<string[]>
      cigarettes__1: CommaSeparatedString<string[]>
      cigarettes_lucky__1: CommaSeparatedString<string[]>
      cigarettes_russian__1: CommaSeparatedString<string[]>
      cleaning_kit_p__1: CommaSeparatedString<string[]>
      cleaning_kit_r5__1: CommaSeparatedString<string[]>
      cleaning_kit_r7__1: CommaSeparatedString<string[]>
      cleaning_kit_s__1: CommaSeparatedString<string[]>
      cleaning_kit_u__1: CommaSeparatedString<string[]>
      cleaning_kit_u__2: CommaSeparatedString<string[]>
      cocaine: CommaSeparatedString<string[]>
      compression_bag: CommaSeparatedString<string[]>
      conserva: CommaSeparatedString<string[]>
      cooking__1: CommaSeparatedString<string[]>
      corn: CommaSeparatedString<string[]>
      csky_patch: CommaSeparatedString<string[]>
      cutlery: CommaSeparatedString<string[]>
      detector_advanced: CommaSeparatedString<string[]>
      detector_elite: CommaSeparatedString<string[]>
      detector_simple: CommaSeparatedString<string[]>
      device_flashlight: CommaSeparatedString<string[]>
      device_torch_dummy: CommaSeparatedString<string[]>
      dolg_patch: CommaSeparatedString<string[]>
      drink_crow: CommaSeparatedString<string[]>
      drug_anabiotic: CommaSeparatedString<string[]>
      drug_antidot__1: CommaSeparatedString<string[]>
      drug_booster: CommaSeparatedString<string[]>
      drug_coagulant__1: CommaSeparatedString<string[]>
      drug_psy_blockade__1: CommaSeparatedString<string[]>
      drug_radioprotector__1: CommaSeparatedString<string[]>
      drug_sleepingpills__1: CommaSeparatedString<string[]>
      duct_tape: CommaSeparatedString<string[]>
      ecolog_patch: CommaSeparatedString<string[]>
      energy_drink: CommaSeparatedString<string[]>
      exo_repair_kit__1: CommaSeparatedString<string[]>
      exo_repair_kit__2: CommaSeparatedString<string[]>
      explo_balon_gas__1: CommaSeparatedString<string[]>
      explo_balon_gas__2: CommaSeparatedString<string[]>
      explo_balon_gas__3: CommaSeparatedString<string[]>
      explo_balon_gas__4: CommaSeparatedString<string[]>
      explo_balon_gas__5: CommaSeparatedString<string[]>
      explo_balon_gas__6: CommaSeparatedString<string[]>
      explo_balon_gas__7: CommaSeparatedString<string[]>
      explo_balon_gas__8: CommaSeparatedString<string[]>
      explo_balon_gas_empty: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__1: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__2: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__3: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__4: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__5: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__6: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__7: CommaSeparatedString<string[]>
      explo_jerrycan_fuel__8: CommaSeparatedString<string[]>
      explo_jerrycan_fuel_empty: CommaSeparatedString<string[]>
      explo_metalcan_powder: CommaSeparatedString<string[]>
      fieldcooker: CommaSeparatedString<string[]>
      flashlight_broken: CommaSeparatedString<string[]>
      flask__1: CommaSeparatedString<string[]>
      freedom_patch: CommaSeparatedString<string[]>
      gloves: CommaSeparatedString<string[]>
      glucose: CommaSeparatedString<string[]>
      glucose_s: CommaSeparatedString<string[]>
      glue_a__1: CommaSeparatedString<string[]>
      glue_b__1: CommaSeparatedString<string[]>
      glue_e__1: CommaSeparatedString<string[]>
      grease: CommaSeparatedString<string[]>
      greh_patch: CommaSeparatedString<string[]>
      grooming: CommaSeparatedString<string[]>
      guitar_a: CommaSeparatedString<string[]>
      gun_oil__1: CommaSeparatedString<string[]>
      gun_oil_ru__1: CommaSeparatedString<string[]>
      gun_oil_ru_d__1: CommaSeparatedString<string[]>
      hand_rolling_tobacco__1: CommaSeparatedString<string[]>
      hand_watch: CommaSeparatedString<string[]>
      harmonica_a: CommaSeparatedString<string[]>
      headlamp: CommaSeparatedString<string[]>
      heavy_repair_kit__1: CommaSeparatedString<string[]>
      heavy_repair_kit__2: CommaSeparatedString<string[]>
      heavy_sewing_thread__1: CommaSeparatedString<string[]>
      heavy_sewing_thread__2: CommaSeparatedString<string[]>
      helmet_repair_kit__1: CommaSeparatedString<string[]>
      helmet_repair_kit__2: CommaSeparatedString<string[]>
      hide_bloodsucker: CommaSeparatedString<string[]>
      hide_boar: CommaSeparatedString<string[]>
      hide_burer: CommaSeparatedString<string[]>
      hide_chimera: CommaSeparatedString<string[]>
      hide_controller: CommaSeparatedString<string[]>
      hide_flesh: CommaSeparatedString<string[]>
      hide_pseudodog: CommaSeparatedString<string[]>
      hide_pseudogiant: CommaSeparatedString<string[]>
      hide_psy_dog: CommaSeparatedString<string[]>
      ied_new: CommaSeparatedString<string[]>
      ied_rpg_new: CommaSeparatedString<string[]>
      isg_patch: CommaSeparatedString<string[]>
      itm_actor_backpack: CommaSeparatedString<string[]>
      itm_advancedkit: CommaSeparatedString<string[]>
      itm_ammokit: CommaSeparatedString<string[]>
      itm_backpack: CommaSeparatedString<string[]>
      itm_basickit: CommaSeparatedString<string[]>
      itm_drugkit: CommaSeparatedString<string[]>
      itm_expertkit: CommaSeparatedString<string[]>
      itm_mapkit_1: CommaSeparatedString<string[]>
      itm_mapkit_2: CommaSeparatedString<string[]>
      itm_mapkit_3: CommaSeparatedString<string[]>
      itm_mapkit_4: CommaSeparatedString<string[]>
      itm_mapkit_5: CommaSeparatedString<string[]>
      itm_mapkit_6: CommaSeparatedString<string[]>
      itm_mapkit_7: CommaSeparatedString<string[]>
      itm_mapkit_8: CommaSeparatedString<string[]>
      itm_mapkit_9: CommaSeparatedString<string[]>
      itm_pda_common: CommaSeparatedString<string[]>
      itm_pda_rare: CommaSeparatedString<string[]>
      itm_pda_uncommon: CommaSeparatedString<string[]>
      itm_sleepbag: CommaSeparatedString<string[]>
      jar: CommaSeparatedString<string[]>
      jewelry_box: CommaSeparatedString<string[]>
      joint: CommaSeparatedString<string[]>
      journal: CommaSeparatedString<string[]>
      jup_b1_half_artifact_af_aac: CommaSeparatedString<string[]>
      jup_b1_half_artifact_af_aam: CommaSeparatedString<string[]>
      jup_b1_half_artifact_af_iam: CommaSeparatedString<string[]>
      jup_b1_half_artifact_lead_box: CommaSeparatedString<string[]>
      kerosene__1: CommaSeparatedString<string[]>
      kerosene__2: CommaSeparatedString<string[]>
      kerosene__3: CommaSeparatedString<string[]>
      kerosene__4: CommaSeparatedString<string[]>
      kerosene__5: CommaSeparatedString<string[]>
      killer_patch: CommaSeparatedString<string[]>
      kit_hunt: CommaSeparatedString<string[]>
      kolbasa: CommaSeparatedString<string[]>
      lead_box: CommaSeparatedString<string[]>
      letter_ecologist_report_1_of_3: CommaSeparatedString<string[]>
      letter_ecologist_report_2_of_3: CommaSeparatedString<string[]>
      letter_ecologist_report_3_of_3: CommaSeparatedString<string[]>
      letter_freedom_manual_1_of_2: CommaSeparatedString<string[]>
      letter_freedom_manual_2_of_2: CommaSeparatedString<string[]>
      letter_letter_to_outside: CommaSeparatedString<string[]>
      letter_memoirs_1_of_2: CommaSeparatedString<string[]>
      letter_memoirs_2_of_2: CommaSeparatedString<string[]>
      letter_mercenary: CommaSeparatedString<string[]>
      letter_military_log: CommaSeparatedString<string[]>
      letter_military_stalker: CommaSeparatedString<string[]>
      letter_monolith_prayer_1_of_3: CommaSeparatedString<string[]>
      letter_monolith_prayer_2_of_3: CommaSeparatedString<string[]>
      letter_monolith_prayer_3_of_3: CommaSeparatedString<string[]>
      letter_monolithian_thoughts: CommaSeparatedString<string[]>
      letter_stalker_letter_1_of_2: CommaSeparatedString<string[]>
      letter_stalker_letter_2_of_2: CommaSeparatedString<string[]>
      letter_stalker_letter_3: CommaSeparatedString<string[]>
      light_repair_kit__1: CommaSeparatedString<string[]>
      light_repair_kit__2: CommaSeparatedString<string[]>
      marijuana: CommaSeparatedString<string[]>
      matches: CommaSeparatedString<string[]>
      meat_bloodsucker: CommaSeparatedString<string[]>
      meat_boar: CommaSeparatedString<string[]>
      meat_chimera: CommaSeparatedString<string[]>
      meat_dog: CommaSeparatedString<string[]>
      meat_flesh: CommaSeparatedString<string[]>
      meat_pseudodog: CommaSeparatedString<string[]>
      meat_snork: CommaSeparatedString<string[]>
      meat_tushkano: CommaSeparatedString<string[]>
      medium_repair_kit__1: CommaSeparatedString<string[]>
      medium_repair_kit__2: CommaSeparatedString<string[]>
      medkit__1: CommaSeparatedString<string[]>
      medkit_army__1: CommaSeparatedString<string[]>
      medkit_scientic__1: CommaSeparatedString<string[]>
      meinkampf: CommaSeparatedString<string[]>
      mine_new: CommaSeparatedString<string[]>
      mineral_water__1: CommaSeparatedString<string[]>
      mint__1: CommaSeparatedString<string[]>
      mirror: CommaSeparatedString<string[]>
      monolith_patch: CommaSeparatedString<string[]>
      morphine: CommaSeparatedString<string[]>
      mre__1: CommaSeparatedString<string[]>
      mutant_part_boar_chop: CommaSeparatedString<string[]>
      mutant_part_boar_leg: CommaSeparatedString<string[]>
      mutant_part_burer_hand: CommaSeparatedString<string[]>
      mutant_part_cat_tail: CommaSeparatedString<string[]>
      mutant_part_chimera_claw: CommaSeparatedString<string[]>
      mutant_part_chimera_kogot: CommaSeparatedString<string[]>
      mutant_part_chimera_meat: CommaSeparatedString<string[]>
      mutant_part_controller_glass: CommaSeparatedString<string[]>
      mutant_part_controller_hand: CommaSeparatedString<string[]>
      mutant_part_crow_beak: CommaSeparatedString<string[]>
      mutant_part_dog_meat: CommaSeparatedString<string[]>
      mutant_part_dog_tail: CommaSeparatedString<string[]>
      mutant_part_flesh_eye: CommaSeparatedString<string[]>
      mutant_part_flesh_meat: CommaSeparatedString<string[]>
      mutant_part_fracture_hand: CommaSeparatedString<string[]>
      mutant_part_krovosos_jaw: CommaSeparatedString<string[]>
      mutant_part_krovosos_meat: CommaSeparatedString<string[]>
      mutant_part_pseudogigant_eye: CommaSeparatedString<string[]>
      mutant_part_pseudogigant_hand: CommaSeparatedString<string[]>
      mutant_part_psevdodog_meat: CommaSeparatedString<string[]>
      mutant_part_psevdodog_tail: CommaSeparatedString<string[]>
      mutant_part_snork_hand: CommaSeparatedString<string[]>
      mutant_part_snork_leg: CommaSeparatedString<string[]>
      mutant_part_snork_mask: CommaSeparatedString<string[]>
      mutant_part_tushkano_head: CommaSeparatedString<string[]>
      mutant_part_tushkano_meat: CommaSeparatedString<string[]>
      mutant_part_zombi_hand: CommaSeparatedString<string[]>
      nuts: CommaSeparatedString<string[]>
      picture_woman: CommaSeparatedString<string[]>
      porn: CommaSeparatedString<string[]>
      porn2: CommaSeparatedString<string[]>
      powder_poltergeist: CommaSeparatedString<string[]>
      protein: CommaSeparatedString<string[]>
      prt_i_ammo: CommaSeparatedString<string[]>
      prt_i_capacitors: CommaSeparatedString<string[]>
      prt_i_ceramic: CommaSeparatedString<string[]>
      prt_i_copper: CommaSeparatedString<string[]>
      prt_i_fasteners: CommaSeparatedString<string[]>
      prt_i_glass: CommaSeparatedString<string[]>
      prt_i_leather: CommaSeparatedString<string[]>
      prt_i_paper: CommaSeparatedString<string[]>
      prt_i_plastic: CommaSeparatedString<string[]>
      prt_i_resistors: CommaSeparatedString<string[]>
      prt_i_rubber: CommaSeparatedString<string[]>
      prt_i_scrap: CommaSeparatedString<string[]>
      prt_i_textolite: CommaSeparatedString<string[]>
      prt_i_transistors: CommaSeparatedString<string[]>
      prt_i_wood: CommaSeparatedString<string[]>
      radio: CommaSeparatedString<string[]>
      radio2: CommaSeparatedString<string[]>
      raisins: CommaSeparatedString<string[]>
      ramrod_tool__1: CommaSeparatedString<string[]>
      ramrod_tool__2: CommaSeparatedString<string[]>
      rasp_tool__1: CommaSeparatedString<string[]>
      rasp_tool__2: CommaSeparatedString<string[]>
      ration_ru__1: CommaSeparatedString<string[]>
      ration_ukr__1: CommaSeparatedString<string[]>
      recipe_advanced_1: CommaSeparatedString<string[]>
      recipe_advanced_2: CommaSeparatedString<string[]>
      recipe_advanced_3: CommaSeparatedString<string[]>
      recipe_advanced_4: CommaSeparatedString<string[]>
      recipe_ammo_1: CommaSeparatedString<string[]>
      recipe_ammo_2: CommaSeparatedString<string[]>
      recipe_ammo_3: CommaSeparatedString<string[]>
      recipe_ammo_4: CommaSeparatedString<string[]>
      recipe_basic_1: CommaSeparatedString<string[]>
      recipe_basic_2: CommaSeparatedString<string[]>
      recipe_basic_3: CommaSeparatedString<string[]>
      recipe_basic_4: CommaSeparatedString<string[]>
      recipe_drug_1: CommaSeparatedString<string[]>
      recipe_drug_2: CommaSeparatedString<string[]>
      recipe_drug_3: CommaSeparatedString<string[]>
      recipe_drug_4: CommaSeparatedString<string[]>
      recipe_expert_1: CommaSeparatedString<string[]>
      recipe_expert_2: CommaSeparatedString<string[]>
      recipe_expert_3: CommaSeparatedString<string[]>
      recipe_expert_4: CommaSeparatedString<string[]>
      renegade_patch: CommaSeparatedString<string[]>
      rope: CommaSeparatedString<string[]>
      roubles: CommaSeparatedString<string[]>
      salicidic_acid: CommaSeparatedString<string[]>
      salmon: CommaSeparatedString<string[]>
      sausage: CommaSeparatedString<string[]>
      sewing_kit_a__1: CommaSeparatedString<string[]>
      sewing_kit_a__2: CommaSeparatedString<string[]>
      sewing_kit_b__1: CommaSeparatedString<string[]>
      sewing_kit_h__1: CommaSeparatedString<string[]>
      sewing_kit_h__2: CommaSeparatedString<string[]>
      sewing_thread__1: CommaSeparatedString<string[]>
      sewing_thread__2: CommaSeparatedString<string[]>
      sharpening_stones__1: CommaSeparatedString<string[]>
      shovel_mili: CommaSeparatedString<string[]>
      shovel_old: CommaSeparatedString<string[]>
      solvent__1: CommaSeparatedString<string[]>
      stalker_patch: CommaSeparatedString<string[]>
      steel_wool: CommaSeparatedString<string[]>
      stimpack: CommaSeparatedString<string[]>
      stimpack_army: CommaSeparatedString<string[]>
      stimpack_scientic: CommaSeparatedString<string[]>
      survival_kit: CommaSeparatedString<string[]>
      swiss_knife: CommaSeparatedString<string[]>
      synthrope: CommaSeparatedString<string[]>
      tarpaulin: CommaSeparatedString<string[]>
      tea__1: CommaSeparatedString<string[]>
      tetanus: CommaSeparatedString<string[]>
      tobacco__1: CommaSeparatedString<string[]>
      tomato: CommaSeparatedString<string[]>
      toolkit_1: CommaSeparatedString<string[]>
      toolkit_2: CommaSeparatedString<string[]>
      toolkit_3: CommaSeparatedString<string[]>
      toolkit_p__1: CommaSeparatedString<string[]>
      toolkit_p__2: CommaSeparatedString<string[]>
      toolkit_r5__1: CommaSeparatedString<string[]>
      toolkit_r5__2: CommaSeparatedString<string[]>
      toolkit_r7__1: CommaSeparatedString<string[]>
      toolkit_r7__2: CommaSeparatedString<string[]>
      toolkit_s__1: CommaSeparatedString<string[]>
      toolkit_s__2: CommaSeparatedString<string[]>
      toolkit_u__1: CommaSeparatedString<string[]>
      tushonka: CommaSeparatedString<string[]>
      underwear: CommaSeparatedString<string[]>
      upgr_o_1_armor: CommaSeparatedString<string[]>
      upgr_o_1_arty: CommaSeparatedString<string[]>
      upgr_o_1_bleed: CommaSeparatedString<string[]>
      upgr_o_1_burn: CommaSeparatedString<string[]>
      upgr_o_1_carry: CommaSeparatedString<string[]>
      upgr_o_1_chem: CommaSeparatedString<string[]>
      upgr_o_1_damage: CommaSeparatedString<string[]>
      upgr_o_1_durability: CommaSeparatedString<string[]>
      upgr_o_1_health: CommaSeparatedString<string[]>
      upgr_o_1_power: CommaSeparatedString<string[]>
      upgr_o_1_psi: CommaSeparatedString<string[]>
      upgr_o_1_rad: CommaSeparatedString<string[]>
      upgr_o_1_run: CommaSeparatedString<string[]>
      upgr_o_1_shock: CommaSeparatedString<string[]>
      upgr_o_1_weight: CommaSeparatedString<string[]>
      upgr_o_2_armor: CommaSeparatedString<string[]>
      upgr_o_2_arty: CommaSeparatedString<string[]>
      upgr_o_2_bleed: CommaSeparatedString<string[]>
      upgr_o_2_burn: CommaSeparatedString<string[]>
      upgr_o_2_carry: CommaSeparatedString<string[]>
      upgr_o_2_chem: CommaSeparatedString<string[]>
      upgr_o_2_damage: CommaSeparatedString<string[]>
      upgr_o_2_durability: CommaSeparatedString<string[]>
      upgr_o_2_health: CommaSeparatedString<string[]>
      upgr_o_2_power: CommaSeparatedString<string[]>
      upgr_o_2_psi: CommaSeparatedString<string[]>
      upgr_o_2_rad: CommaSeparatedString<string[]>
      upgr_o_2_run: CommaSeparatedString<string[]>
      upgr_o_2_shock: CommaSeparatedString<string[]>
      upgr_o_2_weight: CommaSeparatedString<string[]>
      upgr_o_3_armor: CommaSeparatedString<string[]>
      upgr_o_3_arty: CommaSeparatedString<string[]>
      upgr_o_3_bleed: CommaSeparatedString<string[]>
      upgr_o_3_burn: CommaSeparatedString<string[]>
      upgr_o_3_carry: CommaSeparatedString<string[]>
      upgr_o_3_chem: CommaSeparatedString<string[]>
      upgr_o_3_damage: CommaSeparatedString<string[]>
      upgr_o_3_durability: CommaSeparatedString<string[]>
      upgr_o_3_health: CommaSeparatedString<string[]>
      upgr_o_3_power: CommaSeparatedString<string[]>
      upgr_o_3_psi: CommaSeparatedString<string[]>
      upgr_o_3_rad: CommaSeparatedString<string[]>
      upgr_o_3_run: CommaSeparatedString<string[]>
      upgr_o_3_shock: CommaSeparatedString<string[]>
      upgr_o_3_weight: CommaSeparatedString<string[]>
      upgr_w_1_calibre: CommaSeparatedString<string[]>
      upgr_w_1_dispersion: CommaSeparatedString<string[]>
      upgr_w_1_firemode: CommaSeparatedString<string[]>
      upgr_w_1_grenade_mount: CommaSeparatedString<string[]>
      upgr_w_1_inertion: CommaSeparatedString<string[]>
      upgr_w_1_magazine: CommaSeparatedString<string[]>
      upgr_w_1_muffle: CommaSeparatedString<string[]>
      upgr_w_1_recoil: CommaSeparatedString<string[]>
      upgr_w_1_reliability: CommaSeparatedString<string[]>
      upgr_w_1_rpm: CommaSeparatedString<string[]>
      upgr_w_1_scope: CommaSeparatedString<string[]>
      upgr_w_1_scope_mount: CommaSeparatedString<string[]>
      upgr_w_1_speed: CommaSeparatedString<string[]>
      upgr_w_1_weight: CommaSeparatedString<string[]>
      upgr_w_2_calibre: CommaSeparatedString<string[]>
      upgr_w_2_dispersion: CommaSeparatedString<string[]>
      upgr_w_2_firemode: CommaSeparatedString<string[]>
      upgr_w_2_grenade_mount: CommaSeparatedString<string[]>
      upgr_w_2_inertion: CommaSeparatedString<string[]>
      upgr_w_2_magazine: CommaSeparatedString<string[]>
      upgr_w_2_muffle: CommaSeparatedString<string[]>
      upgr_w_2_recoil: CommaSeparatedString<string[]>
      upgr_w_2_reliability: CommaSeparatedString<string[]>
      upgr_w_2_rpm: CommaSeparatedString<string[]>
      upgr_w_2_scope: CommaSeparatedString<string[]>
      upgr_w_2_scope_mount: CommaSeparatedString<string[]>
      upgr_w_2_speed: CommaSeparatedString<string[]>
      upgr_w_2_weight: CommaSeparatedString<string[]>
      upgr_w_3_calibre: CommaSeparatedString<string[]>
      upgr_w_3_dispersion: CommaSeparatedString<string[]>
      upgr_w_3_firemode: CommaSeparatedString<string[]>
      upgr_w_3_grenade_mount: CommaSeparatedString<string[]>
      upgr_w_3_inertion: CommaSeparatedString<string[]>
      upgr_w_3_magazine: CommaSeparatedString<string[]>
      upgr_w_3_muffle: CommaSeparatedString<string[]>
      upgr_w_3_recoil: CommaSeparatedString<string[]>
      upgr_w_3_reliability: CommaSeparatedString<string[]>
      upgr_w_3_rpm: CommaSeparatedString<string[]>
      upgr_w_3_scope: CommaSeparatedString<string[]>
      upgr_w_3_scope_mount: CommaSeparatedString<string[]>
      upgr_w_3_speed: CommaSeparatedString<string[]>
      upgr_w_3_weight: CommaSeparatedString<string[]>
      vodka__1: CommaSeparatedString<string[]>
      vodka_quality__1: CommaSeparatedString<string[]>
      vodka2__1: CommaSeparatedString<string[]>
      walkie: CommaSeparatedString<string[]>
      water_drink: CommaSeparatedString<string[]>
      welding_goggles: CommaSeparatedString<string[]>
      wpn_knife: CommaSeparatedString<string[]>
      wpn_knife2: CommaSeparatedString<string[]>
      wpn_knife3: CommaSeparatedString<string[]>
      wpn_knife4: CommaSeparatedString<string[]>
      wpn_upd: CommaSeparatedString<string[]>
    }
    keep_one: Section.Item[]
    keep_items: {
      af_compass: boolean
      af_quest_b14_twisted: boolean
      attackers_pda: boolean
      bad_psy_helmet: boolean
      broken_pda: boolean
      chernobog_notes: boolean
      cit_doctors_key: boolean
      cit_doctors_pda: boolean
      detector_scientific: boolean
      device_flash_snag: boolean
      device_pda_port_bandit_leader: boolean
      device_pda_zat_b5_dealer: boolean
      drekavac_notes: boolean
      good_psy_helmet: boolean
      jup_b202_bandit_pda: boolean
      jup_b207_merc_pda_with_contract: boolean
      jup_b46_duty_founder_pda: boolean
      jup_b47_merc_pda: boolean
      main_story_3_lab_x16_documents: boolean
      pri_a15_documents: boolean
      pri_a15_wpn_ak74: boolean
      pri_a15_wpn_ak74u: boolean
      pri_a15_wpn_svu: boolean
      pri_a15_wpn_wincheaster1300: boolean
      pri_a17_gauss_rifle: boolean
      pri_a25_explosive_charge_item: boolean
      pri_b35_lab_x8_key: boolean
      pri_b36_monolith_hiding_place_pda: boolean
      rioc_duty: boolean
      rioc_ecolog: boolean
      rioc_sid_1: boolean
      rioc_sid_2: boolean
      rioc_sid_3: boolean
      vodnik_notes: boolean
      zat_b12_key_1: boolean
      zat_b12_key_2: boolean
      zat_b14_device_pda_stalker_find_artefact: boolean
      zat_b20_noah_pda: boolean
      zat_b22_medic_pda: boolean
      zat_b40_pda_1: boolean
      zat_b40_pda_2: boolean
      zat_b40_sarge_pda: boolean
      zat_b44_barge_pda: boolean
    }
    spawn_by_story_id: {
      mar_smart_terrain_doc_doctor: string
      yan_ecolog_semenov: string
      yan_ghost: string
    }
  }

  interface IniFileSchemas {
    'items\\settings\\death_generic.ltx': ItemsSettingsDeathGenericIni
  }
}
