// AUTO-GENERATED addon pack for `weapon_parts_overhaul` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
export { }

declare global {
  interface ItemsSettingsPartPricesIni {
    wpo_part_prices: {
      prt_w_barrel_1: number
      prt_w_barrel_10: number
      prt_w_barrel_11: number
      prt_w_barrel_12: number
      prt_w_barrel_13: number
      prt_w_barrel_2: number
      prt_w_barrel_3: number
      prt_w_barrel_4: number
      prt_w_barrel_5: number
      prt_w_barrel_6: number
      prt_w_barrel_7: number
      prt_w_barrel_8: number
      prt_w_barrel_9: number
      prt_w_bolt_1: number
      prt_w_bolt_10: number
      prt_w_bolt_11: number
      prt_w_bolt_12: number
      prt_w_bolt_13: number
      prt_w_bolt_14: number
      prt_w_bolt_15: number
      prt_w_bolt_16: number
      prt_w_bolt_17: number
      prt_w_bolt_2: number
      prt_w_bolt_3: number
      prt_w_bolt_4: number
      prt_w_bolt_5: number
      prt_w_bolt_6: number
      prt_w_bolt_7: number
      prt_w_bolt_8: number
      prt_w_bolt_9: number
      prt_w_bolt_carrier_1: number
      prt_w_bolt_carrier_10: number
      prt_w_bolt_carrier_11: number
      prt_w_bolt_carrier_2: number
      prt_w_bolt_carrier_3: number
      prt_w_bolt_carrier_4: number
      prt_w_bolt_carrier_5: number
      prt_w_bolt_carrier_6: number
      prt_w_bolt_carrier_7: number
      prt_w_bolt_carrier_8: number
      prt_w_bolt_carrier_9: number
      prt_w_gas_tube_1: number
      prt_w_gas_tube_10: number
      prt_w_gas_tube_11: number
      prt_w_gas_tube_2: number
      prt_w_gas_tube_3: number
      prt_w_gas_tube_4: number
      prt_w_gas_tube_5: number
      prt_w_gas_tube_6: number
      prt_w_gas_tube_7: number
      prt_w_gas_tube_8: number
      prt_w_gas_tube_9: number
      prt_w_p_barrel_1: number
      prt_w_p_barrel_2: number
      prt_w_p_barrel_3: number
      prt_w_p_barrel_4: number
      prt_w_p_barrel_5: number
      prt_w_p_barrel_6: number
      prt_w_p_barrel_7: number
      prt_w_p_spring_1: number
      prt_w_p_spring_2: number
      prt_w_p_spring_3: number
      prt_w_p_spring_4: number
      prt_w_p_spring_5: number
      prt_w_p_spring_6: number
      prt_w_p_trigger_1: number
      prt_w_p_trigger_2: number
      prt_w_p_trigger_3: number
      prt_w_p_trigger_4: number
      prt_w_trigger_components_1: number
      prt_w_trigger_components_2: number
      prt_w_trigger_components_3: number
      prt_w_trigger_components_4: number
      prt_w_trigger_components_5: number
      prt_w_trigger_components_6: number
    }
    wpo_part_weights: {
      prt_w_barrel_1: number
      prt_w_barrel_10: number
      prt_w_barrel_11: number
      prt_w_barrel_12: number
      prt_w_barrel_13: number
      prt_w_barrel_2: number
      prt_w_barrel_3: number
      prt_w_barrel_4: number
      prt_w_barrel_5: number
      prt_w_barrel_6: number
      prt_w_barrel_7: number
      prt_w_barrel_8: number
      prt_w_barrel_9: number
      prt_w_bolt_1: number
      prt_w_bolt_10: number
      prt_w_bolt_11: number
      prt_w_bolt_12: number
      prt_w_bolt_13: number
      prt_w_bolt_14: number
      prt_w_bolt_15: number
      prt_w_bolt_16: number
      prt_w_bolt_17: number
      prt_w_bolt_2: number
      prt_w_bolt_3: number
      prt_w_bolt_4: number
      prt_w_bolt_5: number
      prt_w_bolt_6: number
      prt_w_bolt_7: number
      prt_w_bolt_8: number
      prt_w_bolt_9: number
      prt_w_bolt_carrier_1: number
      prt_w_bolt_carrier_10: number
      prt_w_bolt_carrier_11: number
      prt_w_bolt_carrier_2: number
      prt_w_bolt_carrier_3: number
      prt_w_bolt_carrier_4: number
      prt_w_bolt_carrier_5: number
      prt_w_bolt_carrier_6: number
      prt_w_bolt_carrier_7: number
      prt_w_bolt_carrier_8: number
      prt_w_bolt_carrier_9: number
      prt_w_gas_tube_1: number
      prt_w_gas_tube_10: number
      prt_w_gas_tube_11: number
      prt_w_gas_tube_2: number
      prt_w_gas_tube_3: number
      prt_w_gas_tube_4: number
      prt_w_gas_tube_5: number
      prt_w_gas_tube_6: number
      prt_w_gas_tube_7: number
      prt_w_gas_tube_8: number
      prt_w_gas_tube_9: number
      prt_w_p_barrel_1: number
      prt_w_p_barrel_2: number
      prt_w_p_barrel_3: number
      prt_w_p_barrel_4: number
      prt_w_p_barrel_5: number
      prt_w_p_barrel_6: number
      prt_w_p_barrel_7: number
      prt_w_p_spring_1: number
      prt_w_p_spring_2: number
      prt_w_p_spring_3: number
      prt_w_p_spring_4: number
      prt_w_p_spring_5: number
      prt_w_p_spring_6: number
      prt_w_p_trigger_1: number
      prt_w_p_trigger_2: number
      prt_w_p_trigger_3: number
      prt_w_p_trigger_4: number
      prt_w_trigger_components_1: number
      prt_w_trigger_components_2: number
      prt_w_trigger_components_3: number
      prt_w_trigger_components_4: number
      prt_w_trigger_components_5: number
      prt_w_trigger_components_6: number
    }
  }

  interface IniFileSchemas {
    'items\\settings\\part_prices.ltx': ItemsSettingsPartPricesIni
  }
}
