/** @noSelfInFile */

declare namespace dialogs_jupiter {
  export function actor_has_first_or_second_artefact(first_speaker: TODO, second_speaker: TODO): TODO
  export function actor_has_plant(first_speaker: TODO, second_speaker: TODO): TODO
  export function actor_relocate_conservation_info(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_delivery_info(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_evacuation_info(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_losses_info(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_meeting_info(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_plant(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_power_info(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_trapper_reward(first_speaker: TODO, second_speaker: TODO): void
  export function actor_relocate_way_info(first_speaker: TODO, second_speaker: TODO): void
  export function dm_ashot_and_yar_generate_dialog(a: TODO, b: TODO): TODO
  export function ecolog_companion_task_2_complete(a: TODO, b: TODO): TODO
  export function ecolog_companion_task_2_complete_task(a: TODO, b: TODO): void
  export function ecolog_companion_task_2_give_reward(a: TODO, b: TODO): void
  export function ecolog_companion_task_2_not_complete(a: TODO, b: TODO): TODO
  export function give_jup_b1_art(first_speaker: TODO, second_speaker: TODO): void
  export function give_jup_b16_oasis_artifact(first_speaker: TODO, second_speaker: TODO): void
  export function give_jup_b9_blackbox(first_speaker: TODO, second_speaker: TODO): void
  export function if_actor_has_af_fuzz_kolobok(first_speaker: TODO, second_speaker: TODO): TODO
  export function if_actor_has_af_mincer_meat(first_speaker: TODO, second_speaker: TODO): TODO
  export function if_actor_has_jup_b1_art(first_speaker: TODO, second_speaker: TODO): TODO
  export function if_actor_has_jup_b16_oasis_artifact(first_speaker: TODO, second_speaker: TODO): TODO
  export function if_actor_has_jup_b9_blackbox(first_speaker: TODO, second_speaker: TODO): TODO
  export function if_actor_hasnt_jup_b16_oasis_artifact(first_speaker: TODO, second_speaker: TODO): TODO
  export function is_message_receiver(a: TODO, b: TODO): boolean
  export function jup_a10_actor_give_money(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a10_actor_give_outfit_money(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a10_actor_has_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a10_actor_has_not_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a10_actor_has_not_outfit_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a10_actor_has_outfit_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a10_proverka_wpn(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_a10_proverka_wpn_false(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a10_vano_give_money(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a12_actor_do_not_has_15000_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a12_actor_do_not_has_artefacts(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_a12_actor_has_15000_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a12_actor_has_artefact_1(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a12_actor_has_artefact_2(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a12_actor_has_artefact_3(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a12_actor_has_artefact_4(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a12_actor_has_artefacts(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_a12_transfer_5000_money_to_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a12_transfer_artefact_to_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a12_transfer_cashier_money_from_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a12_transfer_ransom_from_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a9_actor_has_conservation_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_has_delivery_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_has_evacuation_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_has_losses_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_has_meeting_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_has_power_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_has_way_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_conservation_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_delivery_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_evacuation_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_losses_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_meeting_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_power_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_actor_hasnt_way_info(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_a9_owl_stalker_trader_sell_jup_a9_delivery_info(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a9_owl_stalker_trader_sell_jup_a9_evacuation_info(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a9_owl_stalker_trader_sell_jup_a9_losses_info(first_speaker: TODO, second_speaker: TODO): void
  export function jup_a9_owl_stalker_trader_sell_jup_a9_meeting_info(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b1_actor_do_not_have_good_suit(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b1_actor_have_good_suit(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b1_reward_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b1_stalker_squad_thanks(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b10_actor_has_ufo_memory(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b10_ufo_has_money_1000(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b10_ufo_has_money_3000(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b10_ufo_hasnt_money_1000(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b10_ufo_hasnt_money_3000(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b10_ufo_memory_2_give_to_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b10_ufo_memory_give_to_actor(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b10_ufo_memory_give_to_npc(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b10_ufo_relocate_money_1000(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b10_ufo_relocate_money_3000(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b15_actor_sci_outfit(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b15_dec_counter(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b15_no_actor_sci_outfit(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b19_reward(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b19_transfer_conserva_to_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b202_actor_has_medkit(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b202_hit_bandit_from_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b202_medic_dialog_precondition(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b202_transfer_medkit(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b207_actor_has_dealers_pda(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b207_actor_has_merc_pda_with_contract(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b207_generic_decrypt_need_dialog_precond(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b207_give_dealers_pda(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b207_sell_dealers_pda(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b207_sell_merc_pda_with_contract(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b207_transfer_blackmail_reward(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b207_transfer_blackmail_reward_for_pda(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b208_give_reward(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b209_get_monster_scanner(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b209_return_monster_scanner(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b211_kill_bludsuckers_reward(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b217_actor_got_toolkit(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b218_counter_equal_3(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b218_counter_not_0(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b218_counter_not_3(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b25_frase_count_inc(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b32_anomaly_do_not_has_af(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b32_anomaly_has_af(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b32_give_reward_to_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b32_task_give_dialog_precond(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b32_transfer_scanners(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b32_transfer_scanners_2(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b4_is_actor_enemies_to_dolg(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_enemies_to_freedom(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_friend_to_dolg(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_friend_to_freedom(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_neutral_to_dolg(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_neutral_to_freedom(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_not_enemies_to_dolg(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b4_is_actor_not_enemies_to_freedom(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b43_actor_do_not_has_5000_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b43_actor_has_5000_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b43_reward_for_both_artefacts(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b43_reward_for_first_artefact(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b43_reward_for_second_artefact(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b46_actor_has_founder_pda(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b46_sell_duty_founder_pda(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b46_sell_duty_founder_pda_to_owl(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b46_transfer_duty_founder_pda(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b47_actor_can_take_task(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_actor_has_hauss_rifle_docs(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_actor_has_merc_pda(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_actor_has_not_merc_pda(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_actor_not_enemy_to_dolg(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_actor_not_enemy_to_freedom(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_bunker_guard_revard(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b47_employ_squad(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_gauss_rifle_revard(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b47_jupiter_docs_enabled(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_jupiter_products_info_disabled(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_jupiter_products_info_enabled(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b47_jupiter_products_info_revard(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b47_merc_pda_revard(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_actor_can_not_start(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b6_actor_can_start(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b6_actor_outfit_cs(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b6_all_reward_for_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_all_reward_for_actor_extra(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_first_reward_for_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_first_reward_for_actor_extra(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_reward_actor_by_detector(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_scientist_nuclear_physicist_scan_anomaly_precond(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b6_second_reward_for_actor(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_second_reward_for_actor_extra(first_speaker: TODO, second_speaker: TODO): void
  export function jup_b6_stalker_dialog_precond(first_speaker: TODO, second_speaker: TODO): boolean
  export function jup_b9_actor_has_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jup_b9_actor_has_not_money(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_actor_has_all_mail_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_actor_has_any_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_actor_has_any_mail_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_actor_has_any_secondary_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_actor_hasnt_all_mail_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_actor_hasnt_any_mail_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function jupiter_a9_dolg_leader_jupiter_delivery(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_dolg_leader_jupiter_evacuation(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_dolg_leader_jupiter_losses(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_dolg_leader_jupiter_meeting(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_dolg_leader_jupiter_sell_all_secondary_items(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_freedom_leader_jupiter_delivery(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_freedom_leader_jupiter_evacuation(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_freedom_leader_jupiter_losses(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_freedom_leader_jupiter_meeting(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_a9_freedom_leader_jupiter_sell_all_secondary_items(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_b16_reward(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_b200_tech_materials_relocate(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_b220_all_hunted(first_speaker: TODO, second_speaker: TODO): boolean
  export function jupiter_b220_no_one_hunted(first_speaker: TODO, second_speaker: TODO): boolean
  export function jupiter_b6_sell_halfartefact(first_speaker: TODO, second_speaker: TODO): void
  export function jupiter_b9_relocate_money(first_speaker: TODO, second_speaker: TODO): void
  export function npc_in_b4_smart(first_speaker: TODO, second_speaker: TODO): TODO
  export function pay_cost_to_guide_to_pripyat(first_speaker: TODO, second_speaker: TODO): void
  export function pri_a15_sokolov_actor_give_note(first_speaker: TODO, second_speaker: TODO): void
  export function pri_a15_sokolov_actor_has_not_note(first_speaker: TODO, second_speaker: TODO): TODO
  export function pri_a15_sokolov_actor_has_note(first_speaker: TODO, second_speaker: TODO): TODO
  export function transfer_af_fuzz_kolobok(first_speaker: TODO, second_speaker: TODO): void
  export function transfer_af_mincer_meat(first_speaker: TODO, second_speaker: TODO): void
  export function who_is_actor(first_speaker: TODO, second_speaker: TODO): TODO
  export function zat_b106_trapper_reward(first_speaker: TODO, second_speaker: TODO): void
  export function zat_b30_actor_do_not_has_transfer_items(first_speaker: TODO, second_speaker: TODO): TODO
  export function zat_b30_actor_has_transfer_items(first_speaker: TODO, second_speaker: TODO): boolean
  export function zat_b30_transfer_detectors(first_speaker: TODO, second_speaker: TODO): void
}
