/** @noSelfInFile */

declare namespace xr_actions_id {
  export const abuse_base: number
  export const action_script: number
  export const alife: number
  export const animpoint_action: number
  export const assistance: number
  export const chugai_act_tutor: number
  export const chugai_actions: number
  export const chugai_ambush_base: number
  export const chugai_barman_base: number
  export const chugai_commander_base: number
  export const chugai_escape_factory_bandits_base: number
  export const chugai_formation_base: number
  export const chugai_heli_hunter_base: number
  export const chugai_military_commander_base: number
  export const chugai_replics_base: number
  export const chugai_scout_base: number
  export const combat_camper_base: number
  export const combat_monolith_base: number
  export const combat_zombied_base: number
  export const corpse_exist: number
  export const death: number
  export const global_actions: number
  export const jon_actions: number
  export const jon_outcast: number
  export const jon_outcast_replics: number
  export const jon_scientist: number
  export const jon_security: number
  export const jon_sniper_camper: number
  export const jon_sniper_enabled: number
  export const jon_sniper_see_enemy: number
  export const jon_sniper_see_monster: number
  export const jon_stalker_attack: number
  export const jon_stalker_novice: number
  export const jon_stalker_novice2: number
  export const jon_stalker_novice3: number
  export const jon_stalker_zombie: number
  export const narrator_actions: number
  export const peace_sh_base: number
  export const peacemaker_actions: number
  export const post_combat: number
  export const reach_task_location: number
  export const script_combat_planner: number
  export const sidor_act_bandits_base: number
  export const sidor_act_bar: number
  export const sidor_act_chaser: number
  export const sidor_act_follower_base: number
  export const sidor_act_patrol: number
  export const sidor_act_ptr: number
  export const sidor_act_report_leader: number
  export const sidor_act_report_soldier: number
  export const sidor_act_rest: number
  export const sidor_act_secret_lab: number
  export const sidor_act_soldier: number
  export const sidor_act_sos: number
  export const sidor_act_swat_base: number
  export const sidor_act_wounded_base: number
  export const sidor_act_yantar: number
  export const sidor_actions: number
  export const sidor_attendant_act: number
  export const smartcover_action: number
  export const state_mgr: number
  export const stohe_actions: number
  export const stohe_camper_base: number
  export const stohe_cover_base: number
  export const stohe_gulag_base: number
  export const stohe_kamp_base: number
  export const stohe_meet_base: number
  export const stohe_position: number
  export const stohe_reactions_base: number
  export const stohe_state_base: number
  export const stohe_tradeseller_base: number
  export const stohe_tradeseller_init: number
  export const test_reaction: number
  export const wounded_exist: number
  export const zmey_action_guard_activity: number
  export const zmey_actions: number
  export const zmey_assassin_base: number
  export const zmey_bodyguard_base: number
  export const zmey_camper_base: number
  export const zmey_companion_base: number
  export const zmey_guard_base: number
  export const zmey_guide_base: number
  export const zmey_punch_base: number
  export const zmey_remark_base: number
  export const zmey_robber_base: number
  export const zmey_robber_guard_base: number
  export const zmey_scared_base: number
  export const zmey_sleeper_base: number
  export const zmey_talker_base: number
  export const zmey_test_base: number
  export const zmey_walker_base: number
  export const zmey_zoneguard_base: number
}
