/** @noSelfInFile */

declare namespace xr_evaluators_id {
  export const abuse_base: number
  export const animpoint_property: number
  export const assistance: number
  export const chugai_ambush_base: number
  export const chugai_barman_base: number
  export const chugai_commander_base: number
  export const chugai_escape_factory_bandits_base: number
  export const chugai_formation_base: number
  export const chugai_heli_hunter_base: number
  export const chugai_military_commander_base: number
  export const chugai_replics_base: number
  export const chugai_scout_base: number
  export const combat_camper_base: number
  export const combat_monolith_base: number
  export const combat_zombied_base: number
  export const corpse_exist: number
  export const danger: number
  export const death: number
  export const final_trade_init: number
  export const global_evaluators: number
  export const jon_outcast: number
  export const jon_outcast_replics: number
  export const jon_scientist: number
  export const jon_security: number
  export const jon_sniper_enabled: number
  export const jon_sniper_enemy_is: number
  export const jon_sniper_enemy_near: number
  export const jon_sniper_see_enemy: number
  export const jon_sniper_see_monster: number
  export const jon_stalker_attack: number
  export const jon_stalker_novice: number
  export const jon_stalker_novice2: number
  export const jon_stalker_novice3: number
  export const jon_stalker_zombie: number
  export const narrator_evaluators: number
  export const peace_sh_base: number
  export const position: number
  export const post_combat: number
  export const reached_task_location: number
  export const reaction: number
  export const script_combat: number
  export const script_evaluator: number
  export const sidor_attendant_eva: number
  export const sidor_bandits_base: number
  export const sidor_bar: number
  export const sidor_chaser: number
  export const sidor_follower_base: number
  export const sidor_military_radio: number
  export const sidor_patrol_base: number
  export const sidor_patrol_base_property: number
  export const sidor_ptr: number
  export const sidor_report_leader: number
  export const sidor_report_soldier: number
  export const sidor_rest: number
  export const sidor_secret_lab: number
  export const sidor_sos: number
  export const sidor_swat_base: number
  export const sidor_wounded_base: number
  export const sidor_yantar: number
  export const smartcover_action: number
  export const state_change: number
  export const state_mgr: number
  export const stohe_camper_base: number
  export const stohe_cover_base: number
  export const stohe_gulag_base: number
  export const stohe_kamp_base: number
  export const stohe_meet_base: number
  export const stohe_reactions_base: number
  export const stohe_state_base: number
  export const stohe_tradeseller_base: number
  export const test_reaction: number
  export const wounded_exist: number
  export const zmey_assassin_base: number
  export const zmey_bodyguard_base: number
  export const zmey_camper_base: number
  export const zmey_companion_base: number
  export const zmey_guard_base: number
  export const zmey_guide_base: number
  export const zmey_property_guard_activity_end: number
  export const zmey_punch_base: number
  export const zmey_remark_base: number
  export const zmey_robber_base: number
  export const zmey_robber_guard_base: number
  export const zmey_scared_base: number
  export const zmey_sleeper_base: number
  export const zmey_talker_base: number
  export const zmey_test_base: number
  export const zmey_walker_base: number
  export const zmey_zoneguard_base: number
}
