import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

/**
 * Generates `src/types/game/__base/info-portions.d.ts` from the vanilla Anomaly
 * `configs/gameplay` XML tree, collecting every `<info_portion id="...">`. The
 * ids seed a mergeable `interface InfoPortions` registry; `InfoPortion = keyof
 * InfoPortions` is the derived union, which addons extend by declaration merging.
 *
 * Usage: `tsx src/scripts/gen-info-portions.ts [configs-gameplay-dir]`
 */

const GAMEPLAY = resolve(
  process.argv[2] ??
    "c:/Games/STALKER Anomaly/tools/_unpacked/configs/gameplay",
)
const OUT = resolve("src/types/game/__base/info-portions.d.ts")

function walk(dir: string): string[] {
  const out: string[] = []
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (e.toLowerCase().endsWith(".xml")) out.push(p)
  }
  return out
}

const ids = new Set<string>()
for (const f of walk(GAMEPLAY)) {
  const text = readFileSync(f, "latin1")
  for (const m of text.matchAll(/info_portion\s+id\s*=\s*"([^"]+)"/g))
    ids.add(m[1])
}

const key = (s: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s) ? s : `'${s}'`)
let out = `// AUTO-GENERATED by \`tsx src/scripts/gen-info-portions.ts\`. Do not edit by hand.
// Vanilla Anomaly info portions (\`has_info\` / \`give_info\` ids). Mergeable interface:
// an addon's own .d.ts adds ids via \`interface InfoPortions { my_info: 0 }\` and the
// \`InfoPortion\` union grows automatically.

interface InfoPortions {\n`
for (const id of [...ids].sort()) out += `  ${key(id)}: 0\n`
out += `}\ntype InfoPortion = keyof InfoPortions\n`

writeFileSync(OUT, out)
console.log(`Wrote ${OUT} (${ids.size} info portions)`)
