import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { basename, join, resolve } from "node:path"
import { emitLeafFile } from "./lib/emit"
import { emitSchemaBody, parseIni, pascal, winPath as win } from "./lib/ini-core"

/**
 * Generates `IniFileSchemas` file schemas for the vanilla Anomaly config ltx that
 * scripts open with a literal path (`ini_file("misc\\surge_manager.ltx")`), where a
 * schema actually binds and pays off.
 *
 * Domain-driven: {@link DOMAINS} lists the config sub-dirs to cover (flat — the level
 * sub-folders under `scripts/` and the data sub-folders under `misc/` are opened
 * dynamically or belong to other generators, so they are skipped). Each ltx becomes
 * one leaf `.d.ts` under `__base/ini/<domain>/`, declaring a mergeable
 * `<Domain><Name>Ini` interface (domain-qualified so two files of the same stem in
 * different domains never collide-merge) and registering it in `IniFileSchemas` under
 * the backslash path key. A single barrel `__base/ini.d.ts` references every leaf and
 * is itself referenced from `__base.d.ts`.
 *
 * Modelling ("sections precise, values conservative"):
 *  - Section names are enumerated (typed `section_exist`/autocomplete) and stay
 *    mergeable via the named interface.
 *  - A list-style section (bare line keys, no `=`) maps to `Record<string, string>`.
 *  - A field is `number`/`boolean`/`vector` only when EVERY observed value fits;
 *    `vector` needs a 3-4 float tuple. Multi-token values become a branded
 *    `CommaSeparatedString`/`SlashSeparatedString`/`TwoBackslashSeparatedString<string[]>`
 *    (element union unknown from ltx alone → `string`); anything else stays `string`.
 *
 * Usage: `tsx src/scripts/gen-ini-schemas.ts [configs-dir]`
 */

const CONFIGS = resolve(
  process.argv[2] ?? "c:/Games/STALKER Anomaly/tools/_unpacked/configs",
)
const INI_ROOT = resolve("src/types/game/__base/ini")
const BARREL = resolve("src/types/game/__base/ini.d.ts")
const BASE = resolve("src/types/game/__base.d.ts")

/** Config sub-dirs to schema, each scanned flat (top-level ltx only). */
const DOMAINS = ["plugins", "misc", "ai_tweaks", "scripts"] as const

/**
 * Individual literally-opened ltx that don't belong to a flat directory domain —
 * scripts open them with a fixed path (`ini_file("sr_teleport_sections.ltx")`). Paths
 * are relative to {@link CONFIGS} in posix form; each becomes one leaf under
 * `__base/ini/top/`, with a path-derived interface name and a backslash path key.
 * (Directory domains like `ui`/`gameplay` are intentionally absent — `ui` has no ltx,
 * and `gameplay/loadouts` is the engine spawn-loadout format, not script-read config.)
 */
const SCATTERED = [
  "sr_teleport_sections.ltx",
  "default_custom_data.ltx",
  "named_locations.ltx",
  "creatures/game_relations.ltx",
  "items/settings/treasure_manager.ltx",
] as const

const AUTOGEN = "// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand."

/** One leaf `.d.ts`: a named mergeable interface holding the parsed sections plus its
 *  `IniFileSchemas` registration. `iface` and `pathKey` are supplied by the caller so
 *  both flat-domain and scattered files share the same body. Parsing/typing is shared
 *  with the addon generator via `./lib/ini-core`. */
function buildLeaf(iface: string, pathKey: string, file: string): string | null {
  const sections = parseIni(file)
  if (!sections.size) return null
  const body = emitSchemaBody(sections, "  ", iface)
  return emitLeafFile({
    comment: `${AUTOGEN}
// Schema of \`${pathKey}\`. Sections enumerated for autocomplete; \`${iface}\` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).`,
    interfaces: [{ name: iface, body }],
    register: { key: pathKey, iface },
  })
}

// --- generate ---
rmSync(INI_ROOT, { recursive: true, force: true })
const refs: string[] = []
const summary: Record<string, number> = {}
for (const domain of DOMAINS) {
  const dir = join(CONFIGS, domain)
  if (!existsSync(dir)) {
    console.warn(`skip ${domain}: ${dir} not found`)
    continue
  }
  const outDir = join(INI_ROOT, domain)
  mkdirSync(outDir, { recursive: true })
  const files = readdirSync(dir).filter((f) => f.toLowerCase().endsWith(".ltx")).sort()
  let n = 0
  for (const f of files) {
    const stem = basename(f, ".ltx")
    const iface = `${pascal(domain)}${pascal(stem)}Ini`
    const content = buildLeaf(iface, win(`${domain}/${stem}.ltx`), join(dir, f))
    if (!content) continue
    writeFileSync(join(outDir, `${stem}.d.ts`), content)
    refs.push(`ini/${domain}/${stem}.d.ts`)
    n++
  }
  summary[domain] = n
}

// Scattered individual files (no directory domain) → one leaf each under ini/top/.
{
  const outDir = join(INI_ROOT, "top")
  mkdirSync(outDir, { recursive: true })
  let n = 0
  for (const rel of SCATTERED) {
    const file = join(CONFIGS, rel)
    if (!existsSync(file)) {
      console.warn(`skip ${rel}: ${file} not found`)
      continue
    }
    const stem = basename(rel, ".ltx")
    const iface = `${pascal(rel.replace(/\.ltx$/i, ""))}Ini`
    const content = buildLeaf(iface, win(rel), file)
    if (!content) continue
    writeFileSync(join(outDir, `${stem}.d.ts`), content)
    refs.push(`ini/top/${stem}.d.ts`)
    n++
  }
  summary["top"] = n
}

const barrel = `${AUTOGEN}
// Barrel for the per-file config ltx schemas in ./ini. Each leaf registers its own
// \`IniFileSchemas\` key; this file references them all and is referenced from
// __base.d.ts.

${refs.map((r) => `/// <reference path="${r}" />`).join("\n")}
`
writeFileSync(BARREL, barrel)

// Reference the barrel from __base.d.ts: drop any stale __base/ini* references, then
// insert the canonical one after the last __base/ reference (CRLF-safe).
const ref = `/// <reference path="__base/ini.d.ts" />`
let base = readFileSync(BASE, "utf8")
base = base.replace(/^\/\/\/ <reference path="__base\/ini[^"]*" \/>\r?\n/gm, "")
if (!base.includes(ref)) {
  const idx = base.lastIndexOf('/// <reference path="__base/')
  if (idx === -1) throw new Error("no __base/ references found in __base.d.ts to anchor insertion")
  const eol = base.indexOf("\n", idx)
  const at = eol === -1 ? base.length : eol + 1
  base = base.slice(0, at) + ref + "\n" + base.slice(at)
}
writeFileSync(BASE, base)

console.log(`Wrote ${refs.length} ini schemas + barrel`)
for (const domain of [...DOMAINS, "top"]) console.log(`  ${domain}: ${summary[domain] ?? 0}`)
