import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, join, resolve } from "node:path"

/**
 * Generates `src/types/game/__base/weather.d.ts` from the vanilla Anomaly
 * environment configs.
 *
 * `Weather` (preset) is the set of weather files in `environment/weathers/`
 * (the value `level.set_weather` / `get_weather` and the weather editor use).
 * `WeatherCycle` is the `[weather_cycles]` list in
 * `environment/dynamic_weather_graphs.ltx` (clear, partly, cloudy, rain, storm,
 * foggy) — what the `WeatherManager` cycle methods return.
 *
 * Both are mergeable `interface` registries so an addon's own `.d.ts` (e.g. an
 * AtmosFear preset pack) can append entries and the derived unions grow in the
 * consumer's project.
 *
 * Usage: `tsx src/scripts/gen-weather.ts [environment-dir]`
 */

const ENV = resolve(
  process.argv[2] ??
    "c:/Games/STALKER Anomaly/tools/_unpacked/configs/environment",
)
const WEATHERS = join(ENV, "weathers")
const GRAPHS = join(ENV, "dynamic_weather_graphs.ltx")
const OUT = resolve("src/types/game/__base/weather.d.ts")

// --- weather presets: every .ltx basename in environment/weathers/ ---
const presets = new Set<string>()
for (const e of readdirSync(WEATHERS))
  if (e.toLowerCase().endsWith(".ltx")) presets.add(basename(e, ".ltx"))

// --- weather cycles: entries under [weather_cycles] in the graphs file ---
const cycles = new Set<string>()
let inCycles = false
for (const raw of readFileSync(GRAPHS, "latin1").split("\n")) {
  const line = raw.replace(/;.*$/, "").trim()
  if (!line) continue
  const h = line.match(/^\[([^\]]+)\]/)
  if (h) {
    inCycles = h[1].trim() === "weather_cycles"
    continue
  }
  if (inCycles && /^[A-Za-z_][A-Za-z0-9_]*$/.test(line)) cycles.add(line)
}

const key = (s: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s) ? s : `'${s}'`)
function iface(name: string, names: Iterable<string>): string {
  let s = `interface ${name} {\n`
  for (const n of [...names].sort()) s += `  ${key(n)}: 0\n`
  return s + `}\n`
}

let out = `// AUTO-GENERATED by \`tsx src/scripts/gen-weather.ts\`. Do not edit by hand.
// Vanilla Anomaly weather. Both registries are mergeable interfaces: an addon's
// own .d.ts can add entries (e.g. \`interface Weathers { my_preset: 0 }\`) and the
// derived unions grow automatically.
//   Weather      - weather presets (environment/weathers/*.ltx); level.set_weather.
//   WeatherCycle - weather cycles ([weather_cycles] in dynamic_weather_graphs.ltx).

`
out += iface("Weathers", presets)
out += `type Weather = keyof Weathers\n\n`
out += iface("WeatherCycles", cycles)
out += `type WeatherCycle = keyof WeatherCycles\n`

writeFileSync(OUT, out)
console.log(`Wrote ${OUT}`)
console.log(`  Weather: ${presets.size}`)
console.log(`  WeatherCycle: ${cycles.size}`)
