import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, join, resolve } from "node:path"

/**
 * Generates `src/types/game/__base/weather.d.ts` from the vanilla Anomaly
 * environment configs.
 *
 * `Weather` (preset) is the set of weather files in `environment/weathers/`
 * (the value `level.set_weather` / `get_weather` and the weather editor use).
 * `WeatherCycle` is the `[weather_cycles]` list in
 * `environment/dynamic_weather_graphs.ltx` (clear, partly, cloudy, rain, storm,
 * foggy) — what the `WeatherManager` cycle methods return.
 *
 * Both are mergeable `interface` registries so an addon's own `.d.ts` (e.g. an
 * AtmosFear preset pack) can append entries and the derived unions grow in the
 * consumer's project.
 *
 * The generator also emits the weather **file schemas** into {@link IniFileSchemas}
 * (family B): a shared `WeatherSectionFields` shape (field -> value type, inferred
 * by scanning the ltx values) reused by every `environment\weathers\<preset>.ltx`
 * key, plus a `environment\dynamic_weather_graphs.ltx` schema. Registered paths use
 * Windows separators (`\`) because xray's FS requires them — forward slashes crash
 * the game — so keys are written with escaped `\\` in the emitted `.d.ts`. A literal
 * open — `ini_file('environment\\weathers\\w_clear1.ltx')` — or a template open —
 * ``ini_file(`environment\\weathers\\${w}.ltx`)`` with `w: Weather` — binds to the
 * typed section/field API.
 *
 * Usage: `tsx src/scripts/gen-weather.ts [environment-dir]`
 */

const ENV = resolve(
  process.argv[2] ??
    "c:/Games/STALKER Anomaly/tools/_unpacked/configs/environment",
)
const WEATHERS = join(ENV, "weathers")
const GRAPHS = join(ENV, "dynamic_weather_graphs.ltx")
const OUT = resolve("src/types/game/__base/weather.d.ts")

// --- weather presets: every .ltx basename in environment/weathers/ ---
const presets = new Set<string>()
for (const e of readdirSync(WEATHERS))
  if (e.toLowerCase().endsWith(".ltx")) presets.add(basename(e, ".ltx"))

// --- weather cycles: entries under [weather_cycles] in the graphs file ---
const cycles = new Set<string>()
let inCycles = false
for (const raw of readFileSync(GRAPHS, "latin1").split("\n")) {
  const line = raw.replace(/;.*$/, "").trim()
  if (!line) continue
  const h = line.match(/^\[([^\]]+)\]/)
  if (h) {
    inCycles = h[1].trim() === "weather_cycles"
    continue
  }
  if (inCycles && /^[A-Za-z_][A-Za-z0-9_]*$/.test(line)) cycles.add(line)
}

// --- weather file schema: infer each field's value type from its ltx values ---
// A `key = value` line under a time-of-day section. A value that is a comma list of
// floats is a color/`vector`; a bare number is `number`; anything else (texture path,
// section-name reference, or only-ever-empty) is `string`.
type FieldType = "string" | "number" | "vector"
const NUM = /^-?\d+(\.\d+)?$/
const VEC = /^-?\d+(\.\d+)?(\s*,\s*-?\d+(\.\d+)?)+$/

const fieldValues = new Map<string, Set<string>>()
for (const preset of presets) {
  for (const raw of readFileSync(join(WEATHERS, `${preset}.ltx`), "latin1").split("\n")) {
    const line = raw.replace(/;.*$/, "").trim()
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/)
    if (!m) continue
    if (!fieldValues.has(m[1])) fieldValues.set(m[1], new Set())
    fieldValues.get(m[1])!.add(m[2].trim())
  }
}
function inferType(values: Set<string>): FieldType {
  const nonEmpty = [...values].filter(Boolean)
  if (nonEmpty.length && nonEmpty.every((v) => NUM.test(v))) return "number"
  if (nonEmpty.some((v) => VEC.test(v))) return "vector"
  return "string"
}
const weatherFields = [...fieldValues.keys()].sort().map((f) => [f, inferType(fieldValues.get(f)!)] as const)

// --- graphs file: enumerate section headers so section names are typed ---
const graphSections = new Set<string>()
for (const raw of readFileSync(GRAPHS, "latin1").split("\n")) {
  const h = raw.replace(/;.*$/, "").trim().match(/^\[([^\]]+)\]/)
  if (h) graphSections.add(h[1].trim())
}

const key = (s: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s) ? s : `'${s}'`)
// xray FS wants Windows separators; emit `\\` (one real backslash per `/`) so the
// registered key string equals the path scripts pass to `ini_file`. Forward slashes
// crash the game, so they are never used.
const win = (p: string) => p.replace(/\//g, "\\\\")
function iface(name: string, names: Iterable<string>): string {
  let s = `interface ${name} {\n`
  for (const n of [...names].sort()) s += `  ${key(n)}: 0\n`
  return s + `}\n`
}

let out = `// AUTO-GENERATED by \`tsx src/scripts/gen-weather.ts\`. Do not edit by hand.
// Vanilla Anomaly weather. Both registries are mergeable interfaces: an addon's
// own .d.ts can add entries (e.g. \`interface Weathers { my_preset: 0 }\`) and the
// derived unions grow automatically.
//   Weather      - weather presets (environment/weathers/*.ltx); level.set_weather.
//   WeatherCycle - weather cycles ([weather_cycles] in dynamic_weather_graphs.ltx).

`
out += iface("Weathers", presets)
out += `type Weather = keyof Weathers\n\n`
out += iface("WeatherCycles", cycles)
out += `type WeatherCycle = keyof WeatherCycles\n\n`

// --- family B: weather file schemas registered in IniFileSchemas ---
out += `// --- file schemas (IniFileSchemas) ---------------------------------------\n`
out += `// Shared field shape of a weather preset's time-of-day section. Field value\n`
out += `// types are inferred from the vanilla ltx (color tuples -> vector, scalars ->\n`
out += `// number, texture/section refs -> string).\n`
out += `interface WeatherSectionFields {\n`
for (const [f, t] of weatherFields) out += `  ${key(f)}: ${t}\n`
out += `}\n`
out += `/** A weather preset file: time-of-day section (\`HH:MM:SS\`) -> fields. Section\n`
out += ` *  names are runtime time strings, so an index signature keys them. */\n`
out += `type WeatherFileSchema = Record<string, WeatherSectionFields>\n\n`
out += `/** Schema of \`environment/dynamic_weather_graphs.ltx\`. Sections are enumerated\n`
out += ` *  for name autocomplete; entries are read generically (\`r_line_ex\` /\n`
out += ` *  \`collect_section\`), so fields stay permissive. */\n`
out += `interface WeatherGraphsSchema {\n`
for (const s of [...graphSections].sort()) out += `  ${key(s)}: Record<string, string>\n`
out += `}\n\n`
out += `// Keys use Windows separators (\\\\) because xray's FS requires them (forward\n`
out += `// slashes crash the game); binds on literal opens and on template opens.\n`
out += `interface IniFileSchemas {\n`
for (const preset of [...presets].sort())
  out += `  '${win(`environment/weathers/${preset}.ltx`)}': WeatherFileSchema\n`
out += `  '${win("environment/dynamic_weather_graphs.ltx")}': WeatherGraphsSchema\n`
out += `}\n`

writeFileSync(OUT, out)
console.log(`Wrote ${OUT}`)
console.log(`  Weather: ${presets.size}`)
console.log(`  WeatherCycle: ${cycles.size}`)
console.log(`  WeatherSectionFields: ${weatherFields.length}`)
console.log(`  IniFileSchemas entries: ${presets.size + 1}`)
