import { XMLParser } from 'fast-xml-parser'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { ModuleDeclarationKind, Project, QuoteKind } from 'ts-morph'

/**
 * Generates the ambient set of texture ids from the `ui\textures_descr` xml tree.
 *
 * These ids are what `CUIStatic:InitTexture` and any ltx field holding a texture take. They
 * were previously untyped `string`, so a typo produced no error and no icon — the failure is
 * silent and shows up only in game, which is a miserable way to find it.
 *
 * The ids are emitted as keys of an `interface`, not as a bare union, so the type stays strict
 * while remaining extensible: an addon that ships its own `textures_descr` file declares its
 * ids by merging into `UI.Textures`, and they become valid everywhere a texture is accepted.
 * A union with a `string & {}` arm would autocomplete but accept anything, which is no
 * stronger than `string` and defeats the point.
 *
 * Usage: `tsx src/scripts/gen-textures.ts [configs-dir]`
 */

const CONFIGS = resolve(process.argv[2] ?? 'c:/Games/STALKER Anomaly/tools/_unpacked/configs')
const DESCR_DIR = join(CONFIGS, 'ui', 'textures_descr')
const OUT = resolve('src/types/other/textures.d.ts')

/**
 * `texture` and `file` are forced to arrays so a single entry and several have the same shape;
 * everything else keeps its natural form. Textures appear both inside `<file>` and loose under
 * the root, so collection walks the whole tree rather than assuming a depth.
 */
const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: '@_',
  isArray: (name) => name === 'texture' || name === 'file',
})

function collect(node: unknown, out: Set<string>) {
  if (!node || typeof node !== 'object') return
  for (const [key, value] of Object.entries(node)) {
    if (key === 'texture') {
      for (const texture of value as Record<string, string>[]) {
        if (texture['@_id']) out.add(texture['@_id'])
      }
    } else if (Array.isArray(value)) {
      for (const child of value) collect(child, out)
    } else {
      collect(value, out)
    }
  }
}

const ids = new Set<string>()
for (const file of readdirSync(DESCR_DIR).filter((f) => f.endsWith('.xml'))) {
  // Parsed rather than regexed: large stretches of these files are commented out, and a
  // regex happily harvests ids the engine never registers — 1376 of them across vanilla.
  // Read as latin1 because the tree is win1251-encoded, not utf8.
  collect(parser.parse(readFileSync(join(DESCR_DIR, file), 'latin1')), ids)
}
const sorted = [...ids].sort((a, b) => a.localeCompare(b))

// --- emit ------------------------------------------------------------------
const project = new Project({
  useInMemoryFileSystem: true,
  manipulationSettings: { quoteKind: QuoteKind.Single },
})
const sf = project.createSourceFile('textures.d.ts', '', { overwrite: true })

const ui = sf.addModule({
  name: 'UI',
  hasDeclareKeyword: true,
  declarationKind: ModuleDeclarationKind.Namespace,
})

ui.addInterface({
  name: 'Textures',
  docs: [
    {
      description: [
        "Every texture id registered from `ui\\textures_descr`. Vanilla's are generated below;",
        'an addon shipping its own `textures_descr` file adds its ids by merging into this',
        'interface, which is what keeps {@link TextureId} strict rather than falling back to',
        '`string`:',
        '',
        '```ts',
        'declare global {',
        '  namespace UI {',
        '    interface Textures {',
        '      my_addon_icon: true',
        '    }',
        '  }',
        '}',
        '```',
      ].join('\n'),
    },
  ],
  // Added in one call: ts-morph re-analyses the file on every individual `addProperty`, which
  // turns a few thousand ids into a multi-minute run.
  properties: sorted.map((id) => ({ name: `'${id}'`, type: 'true' })),
})

ui.addTypeAlias({
  name: 'TextureId',
  type: 'Extract<keyof Textures, string>',
  docs: [{ description: 'A texture id — vanilla, or any an addon declared by merging into {@link Textures}.' }],
})

const comment = [
  '// AUTO-GENERATED by `tsx src/scripts/gen-textures.ts`. Do not edit by hand.',
  `// ${sorted.length} ids from ${DESCR_DIR.replace(/\\/g, '/')}`,
].join('\n')

writeFileSync(OUT, `${comment}\n${sf.getFullText()}`, 'utf8')

console.log(`Generated ${OUT} (${sorted.length} texture ids)`)
