import { mkdirSync, rmSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { bucketSections, ITEM_NAMES, OBJECT_NAMES } from "./lib/sections-core"

/**
 * Generates the importable `anomaly-packer` section types from the vanilla Anomaly ltx
 * config tree.
 *
 * The class-resolution and category bucketing live in {@link bucketSections}
 * (`./lib/sections-core`), shared verbatim with the on-demand addon-pack generator
 * (`anomaly-packer gen-addon`) so the two can never disagree on which category a
 * section falls into. This file is only the vanilla driver + emitter.
 *
 * Output is a real ES module under `src/types/sections/` — one augmentable
 * `export interface <Name>s {}` + `export type <Name> = keyof <Name>s` leaf per
 * category, an `index.d.ts` that re-exports them and composes the aggregates
 * `Item`/`Object`/`All`, all re-exported from the package root so consumers do
 * `import type { Weapon } from 'anomaly-packer'` and addons augment via
 * `declare module 'anomaly-packer'`. A thin ambient shim keeps the historical bare
 * `Section`/`AnySection` globals working unchanged.
 *
 * Usage: `tsx src/scripts/gen-sections.ts [configs-dir]`
 */

const CONFIGS = resolve(
  process.argv[2] ?? "c:/Games/STALKER Anomaly/tools/_unpacked/configs",
)

/** The importable `anomaly-packer/sections` module source (one leaf per category + an
 *  index barrel). */
const MODULE_DIR = resolve("src/types/sections")
const INDEX = join(MODULE_DIR, "index.d.ts")
/** Ambient back-compat shim: keeps the bare `Section`/`AnySection` globals alive as
 *  aliases of the module, so the ~190 hand-written game .d.ts stay unchanged. Lives
 *  where the old ambient barrel was (already referenced from __base.d.ts). */
const SHIM = resolve("src/types/game/__base/sections.d.ts")
/** The old ambient leaf dir under __base — removed by this generator now that the
 *  category files live in the module. */
const OLD_LEAF_DIR = resolve("src/types/game/__base/sections")

const { buckets } = bucketSections([CONFIGS])

// --- emit ------------------------------------------------------------------
const key = (s: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s) ? s : `'${s}'`)
const plural = (name: string) => `${name}s`
const kebab = (name: string) => name.replace(/[A-Z]/g, (m, i) => (i ? "-" : "") + m.toLowerCase())

const AUTOGEN = "// AUTO-GENERATED by `tsx src/scripts/gen-sections.ts`. Do not edit by hand."

const allCategories = [...ITEM_NAMES, ...OBJECT_NAMES].map((name) => ({ name, members: buckets.get(name)! }))

/** One category inside the `Section` namespace: an augmentable `interface <Name>s` plus its
 *  `keyof`-derived `<Name>` union. Indented two spaces to sit under `export namespace Section`. */
function category(name: string, members: Iterable<string>): string {
  const sorted = [...members].sort()
  let iface = `  export interface ${plural(name)} {\n`
  for (const n of sorted) iface += `    ${key(n)}: 0\n`
  iface += `  }\n`
  return `${iface}  export type ${name} = keyof ${plural(name)}`
}

// Rewrite the module dir from scratch so a removed category can't leave a stale leaf behind,
// and drop the old ambient leaf dir under __base (superseded by this module).
rmSync(OLD_LEAF_DIR, { recursive: true, force: true })
rmSync(MODULE_DIR, { recursive: true, force: true })
mkdirSync(MODULE_DIR, { recursive: true })

// index.d.ts: the whole section-id world under a single `Section` namespace, reachable straight
// from 'anomaly-packer'. Every category is an augmentable interface with a `keyof`-derived union;
// the aggregates are composed from them. Consumers do `import type { Section } from 'anomaly-packer'`
// and write `Section.Weapon` / `Section.Item` / `Section.All`; addons augment via
// `declare module 'anomaly-packer' { namespace Section { interface Weapons { my_wpn: 0 } } }`.
const index = `${AUTOGEN}
// The section-id types, exposed as one \`Section\` namespace re-exported from the package root
// (\`export type * from './types/sections'\` in src/index.ts). Each category is an augmentable
// interface with a \`keyof\`-derived union, composed into the aggregates:
//   Section.Item   - every item section (spawn/give APIs), split by category.
//   Section.Object - Item plus non-item object sections (Npc, Squad, Vehicle, Helicopter,
//                    Monster, Anomaly).
//   Section.All    - the type a game object's section() can return.
// Import: \`import type { Section } from 'anomaly-packer'\` then \`Section.Weapon\` / \`Section.All\`.
// Augment: \`declare module 'anomaly-packer' { namespace Section { interface Weapons { my_wpn: 0 } } }\`.

export namespace Section {
${allCategories.map((c) => category(c.name, c.members)).join("\n")}

  export type Item = ${ITEM_NAMES.join(" | ")}
  export type Object = Item | ${OBJECT_NAMES.join(" | ")}
  export type All = Object
}
`
writeFileSync(INDEX, index)

// Ambient shim: keep the historical bare globals working as aliases of the module.
const shim = `${AUTOGEN}
// Ambient back-compat aliases for the section-id types re-exported from 'anomaly-packer'.
// Kept so the hand-written game .d.ts that reference the bare \`Section\`/\`AnySection\`
// globals compile unchanged. Inline \`import()\` types keep this file an ambient script (no
// top-level import/export) — the aliases remain global. New code should import from
// 'anomaly-packer' directly; addons augment via \`declare module 'anomaly-packer'\`.

/** @deprecated prefer \`import('anomaly-packer').Section.Item\` */
type Section = import('anomaly-packer').Section.Item
/** @deprecated prefer \`import('anomaly-packer').Section.Npc\` */
type NpcSection = import('anomaly-packer').Section.Npc
/** @deprecated prefer \`import('anomaly-packer').Section.Squad\` */
type SquadSection = import('anomaly-packer').Section.Squad
/** @deprecated prefer \`import('anomaly-packer').Section.All\` */
type AnySection = import('anomaly-packer').Section.All
`
writeFileSync(SHIM, shim)

console.log(`Wrote module ${INDEX} + ${allCategories.length} leaf files in ${MODULE_DIR}`)
console.log(`Wrote ambient shim ${SHIM}`)
for (const c of allCategories) console.log(`  ${c.name}: ${c.members.size}`)
