// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `default_custom_data.ltx`. Sections enumerated for autocomplete; `DefaultCustomDataIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface DefaultCustomDataIni {
  logic: {
    active: string
  }
}

interface IniFileSchemas {
  'default_custom_data.ltx': DefaultCustomDataIni
}
