// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `creatures\\game_relations.ltx`. Sections enumerated for autocomplete; `CreaturesGameRelationsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface CreaturesGameRelationsIni {
  game_relations: {
    attitude_friend_threshold: number
    attitude_neutal_threshold: number
    communities: CommaSeparatedString<string>
    goodwill_enemy: number
    goodwill_friend: number
    goodwill_names: CommaSeparatedString<string>
    goodwill_neutal: number
    monster_rating: CommaSeparatedString<string>
    rating: CommaSeparatedString<string>
    rating_names: CommaSeparatedString<string>
    reputation: CommaSeparatedString<string>
    reputation_names: CommaSeparatedString<string>
  }
  communities_relations: {
    actor: CommaSeparatedString<string>
    actor_army: CommaSeparatedString<string>
    actor_bandit: CommaSeparatedString<string>
    actor_csky: CommaSeparatedString<string>
    actor_dolg: CommaSeparatedString<string>
    actor_ecolog: CommaSeparatedString<string>
    actor_freedom: CommaSeparatedString<string>
    actor_greh: CommaSeparatedString<string>
    actor_isg: CommaSeparatedString<string>
    actor_killer: CommaSeparatedString<string>
    actor_monolith: CommaSeparatedString<string>
    actor_renegade: CommaSeparatedString<string>
    actor_stalker: CommaSeparatedString<string>
    actor_zombied: CommaSeparatedString<string>
    arena_enemy: CommaSeparatedString<string>
    army: CommaSeparatedString<string>
    army_npc: CommaSeparatedString<string>
    bandit: CommaSeparatedString<string>
    csky: CommaSeparatedString<string>
    dolg: CommaSeparatedString<string>
    ecolog: CommaSeparatedString<string>
    freedom: CommaSeparatedString<string>
    greh: CommaSeparatedString<string>
    greh_npc: CommaSeparatedString<string>
    isg: CommaSeparatedString<string>
    killer: CommaSeparatedString<string>
    monolith: CommaSeparatedString<string>
    monster: CommaSeparatedString<string>
    renegade: CommaSeparatedString<string>
    stalker: CommaSeparatedString<string>
    trader: CommaSeparatedString<string>
    zombied: CommaSeparatedString<string>
  }
  rank_relations: {
    experienced: CommaSeparatedString<string>
    expert: CommaSeparatedString<string>
    legend: CommaSeparatedString<string>
    master: CommaSeparatedString<string>
    novice: CommaSeparatedString<string>
    professional: CommaSeparatedString<string>
    trainee: CommaSeparatedString<string>
    veteran: CommaSeparatedString<string>
  }
  reputation_relations: {
    bad: CommaSeparatedString<string>
    excellent: CommaSeparatedString<string>
    good: CommaSeparatedString<string>
    neutral: CommaSeparatedString<string>
    really_bad: CommaSeparatedString<string>
    really_good: CommaSeparatedString<string>
    terrible: CommaSeparatedString<string>
    very_bad: CommaSeparatedString<string>
    very_good: CommaSeparatedString<string>
  }
  rank_kill_points: {
    experienced: number
    expert: number
    legend: number
    master: number
    novice: number
    professional: number
    trainee: number
    veteran: number
  }
  communities_sympathy: {
    actor: number
    actor_army: number
    actor_bandit: number
    actor_csky: number
    actor_dolg: number
    actor_ecolog: number
    actor_freedom: number
    actor_greh: number
    actor_isg: number
    actor_killer: number
    actor_monolith: number
    actor_renegade: number
    actor_stalker: number
    actor_zombied: number
    arena_enemy: number
    army: number
    army_npc: number
    bandit: number
    csky: number
    dolg: number
    ecolog: number
    freedom: number
    greh: number
    greh_npc: number
    isg: number
    killer: number
    monolith: number
    monster: number
    renegade: number
    stalker: number
    trader: number
    zombied: number
  }
  action_points: {
    community_goodwill_limits: CommaSeparatedString<string>
    community_member_fight_help_goodwill: number
    community_member_kill_goodwill: number
    danger_community_member_attack_goodwill: number
    danger_enemy_attack_goodwill: number
    danger_enemy_attack_reputation: number
    danger_friend_attack_goodwill: number
    danger_friend_attack_reputation: number
    danger_neutral_attack_goodwill: number
    danger_neutral_attack_reputation: number
    enemy_fight_help_goodwill: number
    enemy_fight_help_reputation: number
    enemy_kill_goodwill: number
    enemy_kill_reputation: number
    fight_remember_time: number
    free_community_member_attack_goodwill: number
    free_enemy_attack_goodwill: number
    free_enemy_attack_reputation: number
    free_friend_attack_goodwill: number
    free_friend_attack_reputation: number
    free_neutral_attack_goodwill: number
    free_neutral_attack_reputation: number
    friend_fight_help_goodwill: number
    friend_fight_help_reputation: number
    friend_kill_goodwill: number
    friend_kill_reputation: number
    min_attack_delta_time: number
    neutral_fight_help_goodwill: number
    neutral_fight_help_reputation: number
    neutral_kill_goodwill: number
    neutral_kill_reputation: number
    personal_goodwill_limits: CommaSeparatedString<string>
  }
  ranks_properties: {
    dispersion_experienced_k: number
    dispersion_novice_k: number
    immunities_experienced_k: number
    immunities_novice_k: number
    visibility_experienced_k: number
    visibility_novice_k: number
  }
  smart_terrain_rank_change: {
    max: number
    min: number
  }
  monster_communities: {
    communities: CommaSeparatedString<string>
  }
  monster_relations: {
    actor: CommaSeparatedString<string>
    arena_monstr: CommaSeparatedString<string>
    bird: CommaSeparatedString<string>
    bloodsucker: CommaSeparatedString<string>
    boar: CommaSeparatedString<string>
    burer: CommaSeparatedString<string>
    cat: CommaSeparatedString<string>
    chimera: CommaSeparatedString<string>
    controller: CommaSeparatedString<string>
    corpse: CommaSeparatedString<string>
    dog: CommaSeparatedString<string>
    flesh: CommaSeparatedString<string>
    fly: CommaSeparatedString<string>
    fracture: CommaSeparatedString<string>
    giant: CommaSeparatedString<string>
    human: CommaSeparatedString<string>
    karlik: CommaSeparatedString<string>
    komar: CommaSeparatedString<string>
    lurker: CommaSeparatedString<string>
    medwed: CommaSeparatedString<string>
    mwolf: CommaSeparatedString<string>
    poltergeist: CommaSeparatedString<string>
    pseudodog: CommaSeparatedString<string>
    psysucker: CommaSeparatedString<string>
    rat: CommaSeparatedString<string>
    rotan: CommaSeparatedString<string>
    snork: CommaSeparatedString<string>
    tark: CommaSeparatedString<string>
    trader: CommaSeparatedString<string>
    tushkano: CommaSeparatedString<string>
    zombie: CommaSeparatedString<string>
    zoo_monster: CommaSeparatedString<string>
  }
}

interface IniFileSchemas {
  'creatures\\game_relations.ltx': CreaturesGameRelationsIni
}
