// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `named_locations.ltx`. Sections enumerated for autocomplete; `NamedLocationsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface NamedLocationsIni {
  barrier_spawn_1: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_2: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_3: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_4: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_5: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_6: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_7: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_8: {
    position: CommaSeparatedString<string>
  }
  barrier_spawn_9: {
    position: CommaSeparatedString<string>
  }
}

interface IniFileSchemas {
  'named_locations.ltx': NamedLocationsIni
}
