// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `sr_teleport_sections.ltx`. Sections enumerated for autocomplete; `SrTeleportSectionsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface SrTeleportSectionsIni {
  mar_space_restrictor_to_escape_1: {
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mar_space_restrictor_to_escape_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mar_space_restrictor_to_agroprom_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mar_teleport_from_base_to_north: {
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mar_teleport_from_base_to_west: {
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mar_teleport_to_base: {
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  esc_space_restrictor_to_marsh_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  esc_space_restrictor_to_marsh_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  esc_space_restrictor_to_garbage_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  esc_space_restrictor_to_garbage_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  esc_space_restrictor_to_darkscape_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  ds_space_restrictor_to_escape: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  ds_space_restrictor_to_darkvalley: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_garbage_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_garbage_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_marsh_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_yantar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_agr_ug_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_agr_ug_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_agr_ug_3: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_agr_ug_4: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_agr_ug_5: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  agr_space_restrictor_to_agr_ug_6: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_agroprom_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_agroprom_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_bar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_darkvalley_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_darkvalley_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_escape_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_escape_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gar_space_restrictor_to_rostok_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  val_space_restrictor_to_darkscape: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  val_space_restrictor_to_garbage_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  val_space_restrictor_to_garbage_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  val_space_restrictor_to_labx18: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  val_space_restrictor_to_tc: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  bar_space_restrictor_to_garbage_01: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  bar_space_restrictor_to_military_01: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  bar_space_restrictor_to_rostok_01: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  bar_space_restrictor_to_tc: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  ros_space_restrictor_to_bar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  ros_space_restrictor_to_garbage_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  ros_space_restrictor_to_yantar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  yan_space_restrictor_to_rostok_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  yan_space_restrictor_to_agroprom_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  yan_space_restrictor_to_dead_city_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  yan_space_restrictor_to_x16: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mil_space_restrictor_to_red_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mil_space_restrictor_to_bar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mil_space_restrictor_to_radar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mil_space_restrictor_to_dead_city_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  mil_space_restrictor_to_tc: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  cit_space_restrictor_to_limansk: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  cit_space_restrictor_to_yantar: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  cit_space_restrictor_to_military: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  red_space_restricor_to_jupiter: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  red_space_restrictor_to_military_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  red_space_restrictor_to_limansk: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  red_space_restrictor_to_radar_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  rad_space_restrictor_to_military_01: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  rad_space_restrictor_to_red_forest: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  rad_space_restrictor_to_pripyat_01: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  rad_space_restrictor_to_bunker: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  lim_space_restrictor_to_dead_city: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  lim_space_restrictor_to_red_forest: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  lim_space_restrictor_to_hospital: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  katacomb_space_restrictor_to_limansk: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  katacomb_space_restrictor_to_aes_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pri_space_restrictor_to_radar: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pri_space_restrictor_to_stancia: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pri_space_restrictor_to_cop_pripyat: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pri_space_restrictor_to_jupiter: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pri_space_restrictor_to_jup_ug: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pri_space_restrictor_to_labx8: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes_space_restrictor_to_pripyat: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes_space_restrictor_to_zaton: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes_space_restrictor_to_aes2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes_space_restrictor_to_sarcofag: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes2_space_restrictor_to_gen: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes2_space_restrictor_to_aes1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes2_space_restrictor_to_hospital: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  aes2_space_restrictor_to_secret_lab: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gen_space_restrictor_to_aes2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  gen_space_restrictor_to_warlab: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  zaton_space_restrictor_to_jupiter: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  zaton_space_restrictor_to_stancia_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  jup_space_restrictor_to_zaton: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  jupiter_space_restrictor_to_red_forest: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  jupiter_space_restrictor_to_soc_pripyat: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  jupiter_space_restrictor_to_jupiter_ug: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  jupiter_ug_space_restrictor_to_jupiter: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  cop_pripyat_space_restrictor_to_soc_pripyat: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  tc_space_restrictor_to_darkvalley: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  tc_space_restrictor_to_bar: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  tc_space_restrictor_to_military_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  tc_space_restrictor_to_military_2: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  tc_space_restrictor_to_military_3: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pol_space_restrictor_to_escape_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  esc_space_restrictor_to_pole_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  val_space_restrictor_to_pole_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
  pol_space_restrictor_to_val_1: {
    autosave: boolean
    enable: boolean
    hint: string
    path: string
    reject_path: string
    spot: string
    text: string
  }
}

interface IniFileSchemas {
  'sr_teleport_sections.ltx': SrTeleportSectionsIni
}
