// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `items\\settings\\treasure_manager.ltx`. Sections enumerated for autocomplete; `ItemsSettingsTreasureManagerIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface ItemsSettingsTreasureManagerIni {
  rare_stashes_names: {
    agr_q3_t_a: boolean
    agr_q4_n: boolean
    agr_smart_terrain_4_2_box: boolean
    agr_smart_terrain_5_2_box: boolean
    dark_valley_treasure_19: boolean
    esc_treasure_15: boolean
    gar_treasure_18: boolean
    gar_treasure_5: boolean
    gar_treasure_quest_reward_in_anomaly: boolean
    hos_treasure_2: boolean
    l06_rostok_level_prefix_inventory_box_0009: boolean
    l06_rostok_level_prefix_inventory_box_0014: boolean
    l06_rostok_level_prefix_inventory_box_0017: boolean
    l06_rostok_level_prefix_inventory_box_0019: boolean
    l06_rostok_level_prefix_inventory_box_0020: boolean
    l10_radar_level_prefix_inventory_box: boolean
    l10_radar_level_prefix_inventory_box_0000: boolean
    l10_radar_level_prefix_inventory_box_0003: boolean
    l10_radar_level_prefix_inventory_box_0004: boolean
    lim_treasure_8: boolean
    mar_treasure_44: boolean
    mar_treasure_5: boolean
    mar_treasure_6: boolean
    mar_treasure_8: boolean
    mil_additional_quest_1_box: boolean
    mil_treasure_20: boolean
    red_q1_t_l: boolean
    red_q2_t_a: boolean
    red_recover_item_2_spawn: boolean
    red_treasure_20: boolean
    red_treasure_7: boolean
    stash_gen_undegr_mlr1: boolean
    stash_gen_undegr_mlr2: boolean
    trc_inventory_box_0005: boolean
    trc_inventory_box_0013: boolean
    trc_inventory_box_0019: boolean
    trc_inventory_box_0027: boolean
    trc_inventory_box_0030: boolean
    val_q9_n: boolean
    yan_q6_n: boolean
    yan_smart_terrain_3_4_box: boolean
    yantar_treasure_12: boolean
    yantar_treasure_6: boolean
  }
  blacklist_stashes_names: Record<string, string>
  settings_common: {
    max_weight: number
    min_weight: number
    num_of_tiers: number
  }
  kind_tier_effect_common: {
    i_arty: CommaSeparatedString<string>
    i_arty_cont: CommaSeparatedString<string>
    i_arty_junk: CommaSeparatedString<string>
    i_device: CommaSeparatedString<string>
    i_drink: CommaSeparatedString<string>
    i_food: CommaSeparatedString<string>
    i_kit: CommaSeparatedString<string>
    i_medical: CommaSeparatedString<string>
    i_misc: CommaSeparatedString<string>
    i_mutant_belt: CommaSeparatedString<string>
    i_mutant_cooked: CommaSeparatedString<string>
    i_mutant_part: CommaSeparatedString<string>
    i_mutant_raw: CommaSeparatedString<string>
    i_part: CommaSeparatedString<string>
    i_repair: CommaSeparatedString<string>
    i_tool: CommaSeparatedString<string>
    i_upgrade: CommaSeparatedString<string>
    o_heavy: CommaSeparatedString<string>
    o_light: CommaSeparatedString<string>
    o_medium: CommaSeparatedString<string>
    o_sci: CommaSeparatedString<string>
    w_ammo: CommaSeparatedString<string>
    w_explosive: CommaSeparatedString<string>
    w_melee: CommaSeparatedString<string>
    w_misc: CommaSeparatedString<string>
  }
  settings_rare: {
    completed_task_num: number
    max_weight: number
    min_weight: number
    num_of_tiers: number
    reward_bonus: CommaSeparatedString<string>
    start_chance: number
  }
  kind_tier_effect_rare: {
    i_arty: CommaSeparatedString<string>
    i_arty_cont: CommaSeparatedString<string>
    i_arty_junk: CommaSeparatedString<string>
    i_device: CommaSeparatedString<string>
    i_drink: CommaSeparatedString<string>
    i_food: CommaSeparatedString<string>
    i_kit: CommaSeparatedString<string>
    i_medical: CommaSeparatedString<string>
    i_misc: CommaSeparatedString<string>
    i_mutant_belt: CommaSeparatedString<string>
    i_mutant_cooked: CommaSeparatedString<string>
    i_mutant_part: CommaSeparatedString<string>
    i_mutant_raw: CommaSeparatedString<string>
    i_part: CommaSeparatedString<string>
    i_repair: CommaSeparatedString<string>
    i_tool: CommaSeparatedString<string>
    i_upgrade: CommaSeparatedString<string>
    o_heavy: CommaSeparatedString<string>
    o_light: CommaSeparatedString<string>
    o_medium: CommaSeparatedString<string>
    o_sci: CommaSeparatedString<string>
    w_ammo: CommaSeparatedString<string>
    w_explosive: CommaSeparatedString<string>
    w_melee: CommaSeparatedString<string>
    w_misc: CommaSeparatedString<string>
  }
  possible_items: {
    af_aac: CommaSeparatedString<string>
    af_iam: number
    cigar2__2: CommaSeparatedString<string>
    cigar3__3: CommaSeparatedString<string>
    cigarettes__3: CommaSeparatedString<string>
    cigarettes_lucky__1: number
    cigarettes_lucky__2: CommaSeparatedString<string>
    detector_advanced: number
    hand_rolling_tobacco__1: number
  }
  stash_bonus: {
    cigar2__2: CommaSeparatedString<string>
    cigar3__3: CommaSeparatedString<string>
    cigarettes__3: CommaSeparatedString<string>
    cigarettes_lucky__1: number
    cigarettes_lucky__2: CommaSeparatedString<string>
    hand_rolling_tobacco__1: number
  }
  isg_stash_bonus: {
    b_1: CommaSeparatedString<string>
    b_10: CommaSeparatedString<string>
    b_11: string
    b_12: string
    b_13: string
    b_14: string
    b_15: string
    b_16: string
    b_17: string
    b_18: string
    b_19: string
    b_2: CommaSeparatedString<string>
    b_20: CommaSeparatedString<string>
    b_21: CommaSeparatedString<string>
    b_22: CommaSeparatedString<string>
    b_23: CommaSeparatedString<string>
    b_3: CommaSeparatedString<string>
    b_4: CommaSeparatedString<string>
    b_5: string
    b_6: string
    b_7: string
    b_8: string
    b_9: string
  }
}

interface IniFileSchemas {
  'items\\settings\\treasure_manager.ltx': ItemsSettingsTreasureManagerIni
}
