// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `ai_tweaks\\axr_companions.ltx`. Sections enumerated for autocomplete; `AiTweaksAxrCompanionsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface AiTweaksAxrCompanionsIni {
  main: {
    allow_only_friends_as_companions: boolean
    allow_simulation_squads_as_companions: boolean
    enable: boolean
    max_actor_squad_size: number
    max_actor_squad_size_patriarch: number
  }
}

interface IniFileSchemas {
  'ai_tweaks\\axr_companions.ltx': AiTweaksAxrCompanionsIni
}
