// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `ai_tweaks\\axr_smartcover.ltx`. Sections enumerated for autocomplete; `AiTweaksAxrSmartcoverIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface AiTweaksAxrSmartcoverIni {
  settings: {
    enable: boolean
  }
}

interface IniFileSchemas {
  'ai_tweaks\\axr_smartcover.ltx': AiTweaksAxrSmartcoverIni
}
