// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `ai_tweaks\\rx_ff.ltx`. Sections enumerated for autocomplete; `AiTweaksRxFfIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface AiTweaksRxFfIni {
  main: {
    check_period: number
    enabled: boolean
    forbidden_factions: string
    forbidden_npcs: string
  }
}

interface IniFileSchemas {
  'ai_tweaks\\rx_ff.ltx': AiTweaksRxFfIni
}
