// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `ai_tweaks\\simulation_objects.ltx`. Sections enumerated for autocomplete; `AiTweaksSimulationObjectsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
import type { CommaSeparatedString } from 'anomaly-packer'

declare global {
  interface AiTweaksSimulationObjectsIni {
    k00_marsh: {
      target_maps: CommaSeparatedString<string[]>
    }
    k01_darkscape: {
      target_maps: CommaSeparatedString<string[]>
    }
    l01_escape: {
      target_maps: CommaSeparatedString<string[]>
    }
    l02_garbage: {
      target_maps: CommaSeparatedString<string[]>
    }
    l03_agroprom: {
      target_maps: CommaSeparatedString<string[]>
    }
    l04_darkvalley: {
      target_maps: CommaSeparatedString<string[]>
    }
    l05_bar: {
      target_maps: CommaSeparatedString<string[]>
    }
    l06_rostok: {
      target_maps: CommaSeparatedString<string[]>
    }
    l07_military: {
      target_maps: CommaSeparatedString<string[]>
    }
    l08_yantar: {
      target_maps: CommaSeparatedString<string[]>
    }
    l09_deadcity: {
      target_maps: CommaSeparatedString<string[]>
    }
    l10_limansk: {
      target_maps: CommaSeparatedString<string[]>
    }
    l10_radar: {
      target_maps: CommaSeparatedString<string[]>
    }
    l10_red_forest: {
      target_maps: CommaSeparatedString<string[]>
    }
    l11_hospital: {
      target_maps: CommaSeparatedString<string[]>
    }
    l11_pripyat: {
      target_maps: CommaSeparatedString<string[]>
    }
    l12_stancia: {
      target_maps: CommaSeparatedString<string[]>
    }
    l12u_sarcofag: {
      target_maps: string
    }
    l12u_control_monolith: {
      target_maps: string
    }
    l12_stancia_2: {
      target_maps: CommaSeparatedString<string[]>
    }
    l13_generators: {
      target_maps: string
    }
    zaton: {
      target_maps: CommaSeparatedString<string[]>
    }
    jupiter: {
      target_maps: CommaSeparatedString<string[]>
    }
    pripyat: {
      target_maps: CommaSeparatedString<string[]>
    }
    jupiter_underground: {
      target_maps: CommaSeparatedString<string[]>
    }
    k02_trucks_cemetery: {
      target_maps: CommaSeparatedString<string[]>
    }
    y04_pole: {
      target_maps: CommaSeparatedString<string[]>
    }
  }

  interface IniFileSchemas {
    'ai_tweaks\\simulation_objects.ltx': AiTweaksSimulationObjectsIni
  }
}
