// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `ai_tweaks\\sr_light.ltx`. Sections enumerated for autocomplete; `AiTweaksSrLightIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface AiTweaksSrLightIni {
  settings: {
    light_off_while_sleep: boolean
  }
  hour_time_min: {
    army: number
    bandit: number
    bandit_elite: number
    bandit_elite_hostile: number
    bandit_hostile: number
    dolg: number
    dolg_elite: number
    dolg_elite_hostile: number
    dolg_hostile: number
    dolg_hunter_day: number
    dolg_hunter_day_hostile: number
    dolg_hunter_night: number
    dolg_hunter_night_hostile: number
    ecolog: number
    freedom: number
    freedom_elite: number
    freedom_elite_hostile: number
    freedom_hostile: number
    freedom_sci: number
    freedom_sci_hostile: number
    greh: number
    isg: number
    killer: number
    monolith: number
    monolith_pripyat: number
    monolith_sci: number
    monster_zombied_day: number
    renegade: number
    stalker: number
    stalker_elite: number
    stalker_elite_hostile: number
    stalker_hostile: number
    stalker_hunter_day: number
    stalker_hunter_day_hostile: number
    stalker_hunter_night: number
    stalker_hunter_night_hostile: number
    stalker_sci: number
    stalker_sci_hostile: number
    zombied: number
  }
  hour_time_max: {
    army: number
    bandit: number
    bandit_elite: number
    bandit_elite_hostile: number
    bandit_hostile: number
    dolg: number
    dolg_elite: number
    dolg_elite_hostile: number
    dolg_hostile: number
    dolg_hunter_day: number
    dolg_hunter_day_hostile: number
    dolg_hunter_night: number
    dolg_hunter_night_hostile: number
    ecolog: number
    freedom: number
    freedom_elite: number
    freedom_elite_hostile: number
    freedom_hostile: number
    freedom_sci: number
    freedom_sci_hostile: number
    greh: number
    isg: number
    killer: number
    monolith: number
    monolith_pripyat: number
    monolith_sci: number
    monster_zombied_day: number
    renegade: number
    stalker: number
    stalker_elite: number
    stalker_elite_hostile: number
    stalker_hostile: number
    stalker_hunter_day: number
    stalker_hunter_day_hostile: number
    stalker_hunter_night: number
    stalker_hunter_night_hostile: number
    stalker_sci: number
    stalker_sci_hostile: number
    zombied: number
  }
}

interface IniFileSchemas {
  'ai_tweaks\\sr_light.ltx': AiTweaksSrLightIni
}
