// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `ai_tweaks\\xr_corpse_detection.ltx`. Sections enumerated for autocomplete; `AiTweaksXrCorpseDetectionIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface AiTweaksXrCorpseDetectionIni {
    settings: {
      always_detect_dist: number
      enable_mutant_looting: boolean
      state_run: string
      state_walk: string
    }
    loot_mutant_communities: string[]
    ignore_sections: string[]
  }

  interface IniFileSchemas {
    'ai_tweaks\\xr_corpse_detection.ltx': AiTweaksXrCorpseDetectionIni
  }
}
