// AUTO-GENERATED addon pack for `3dss-for-gamma` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
import type { CommaSeparatedString } from 'anomaly-packer'
declare global {
  interface ModSystemZz3dssPmIni {
    wpn_pm_sk1_new_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: CommaSeparatedString<string[]>
      aim_hud_offset_rot_16x9: CommaSeparatedString<string[]>
      anm_ammo_check: CommaSeparatedString<string[]>
      anm_ammo_check_ammo1: CommaSeparatedString<string[]>
      anm_ammo_check_ammo2: CommaSeparatedString<string[]>
      anm_ammo_check_ammo3: CommaSeparatedString<string[]>
      anm_ammo_check_ammo4: CommaSeparatedString<string[]>
      anm_ammo_check_ammo5: CommaSeparatedString<string[]>
      anm_ammo_check_ammo6: CommaSeparatedString<string[]>
      anm_ammo_check_ammo7: CommaSeparatedString<string[]>
      anm_ammo_check_ammo8: CommaSeparatedString<string[]>
      anm_ammo_check_empty: CommaSeparatedString<string[]>
      anm_ammo_check_empty_jammed: CommaSeparatedString<string[]>
      anm_ammo_check_jammed: CommaSeparatedString<string[]>
      anm_ammo_check_no_mag: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_empty: CommaSeparatedString<string[]>
      anm_bore_empty_jammed: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_bore_no_mag: CommaSeparatedString<string[]>
      anm_empty_fire: CommaSeparatedString<string[]>
      anm_empty_fire_jammed: CommaSeparatedString<string[]>
      anm_hide: CommaSeparatedString<string[]>
      anm_hide_empty: CommaSeparatedString<string[]>
      anm_hide_empty_jammed: CommaSeparatedString<string[]>
      anm_hide_jammed: CommaSeparatedString<string[]>
      anm_idle: CommaSeparatedString<string[]>
      anm_idle_aim: CommaSeparatedString<string[]>
      anm_idle_aim_empty: CommaSeparatedString<string[]>
      anm_idle_aim_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_end: CommaSeparatedString<string[]>
      anm_idle_aim_end_empty: CommaSeparatedString<string[]>
      anm_idle_aim_end_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_end_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_move_crouch_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_move_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_move_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_move_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_start: CommaSeparatedString<string[]>
      anm_idle_aim_start_empty: CommaSeparatedString<string[]>
      anm_idle_aim_start_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_start_jammed: CommaSeparatedString<string[]>
      anm_idle_empty: CommaSeparatedString<string[]>
      anm_idle_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_empty_lowered: CommaSeparatedString<string[]>
      anm_idle_jammed: CommaSeparatedString<string[]>
      anm_idle_lowered: CommaSeparatedString<string[]>
      anm_idle_lowered_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_lowered_jammed: CommaSeparatedString<string[]>
      anm_idle_moving: CommaSeparatedString<string[]>
      anm_idle_moving_crouch: CommaSeparatedString<string[]>
      anm_idle_moving_crouch_empty: CommaSeparatedString<string[]>
      anm_idle_moving_crouch_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_moving_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_moving_empty: CommaSeparatedString<string[]>
      anm_idle_moving_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_sprint: CommaSeparatedString<string[]>
      anm_idle_sprint_empty: CommaSeparatedString<string[]>
      anm_idle_sprint_empty_jammed: CommaSeparatedString<string[]>
      anm_idle_sprint_jammed: CommaSeparatedString<string[]>
      anm_idle2sprint: CommaSeparatedString<string[]>
      anm_idle2sprint_empty: CommaSeparatedString<string[]>
      anm_idle2sprint_empty_jammed: CommaSeparatedString<string[]>
      anm_idle2sprint_jammed: CommaSeparatedString<string[]>
      anm_reload: CommaSeparatedString<string[]>
      anm_reload_ammo1: CommaSeparatedString<string[]>
      anm_reload_ammo2: CommaSeparatedString<string[]>
      anm_reload_ammo3: CommaSeparatedString<string[]>
      anm_reload_ammo4: CommaSeparatedString<string[]>
      anm_reload_ammo5: CommaSeparatedString<string[]>
      anm_reload_ammo6: CommaSeparatedString<string[]>
      anm_reload_ammo7: CommaSeparatedString<string[]>
      anm_reload_ammo8: CommaSeparatedString<string[]>
      anm_reload_empty: CommaSeparatedString<string[]>
      anm_reload_empty_no_mag: CommaSeparatedString<string[]>
      anm_reload_misfire: CommaSeparatedString<string[]>
      anm_reload_misfire_empty: CommaSeparatedString<string[]>
      anm_shot_l: CommaSeparatedString<string[]>
      anm_shot_l_aim: CommaSeparatedString<string[]>
      anm_shots: CommaSeparatedString<string[]>
      anm_shots_aim: CommaSeparatedString<string[]>
      anm_shots_aim_empty_jammed: CommaSeparatedString<string[]>
      anm_shots_aim_jammed: CommaSeparatedString<string[]>
      anm_shots_aim_variant1: CommaSeparatedString<string[]>
      anm_shots_aim_variant2: CommaSeparatedString<string[]>
      anm_shots_aim_variant3: CommaSeparatedString<string[]>
      anm_shots_empty_jammed: CommaSeparatedString<string[]>
      anm_shots_jammed: CommaSeparatedString<string[]>
      anm_shots_variant1: CommaSeparatedString<string[]>
      anm_shots_variant2: CommaSeparatedString<string[]>
      anm_shots_variant3: CommaSeparatedString<string[]>
      anm_show: CommaSeparatedString<string[]>
      anm_show_empty: CommaSeparatedString<string[]>
      anm_show_empty_jammed: CommaSeparatedString<string[]>
      anm_show_jammed: CommaSeparatedString<string[]>
      anm_sprint2idle: CommaSeparatedString<string[]>
      anm_sprint2idle_empty: CommaSeparatedString<string[]>
      anm_sprint2idle_empty_jammed: CommaSeparatedString<string[]>
      anm_sprint2idle_jammed: CommaSeparatedString<string[]>
      attach_place_idx: number
      empty_click_anm_power: number
      empty_click_anm_speed: number
      fire_bone: string
      fire_point: vector
      gl_hud_offset_pos: vector
      gl_hud_offset_rot: vector
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      inertion_offset_LRUD_aim: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lean_hud_offset_pos: vector
      lean_hud_offset_rot: vector
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      safemode_anm: string
      safemode_anm_power: number
      safemode_anm_power2: number
      safemode_anm_speed: number
      safemode_anm_speed2: number
      safemode_anm2: string
      shell_bone: string
      shell_point: vector
      shooting_backward_offset: CommaSeparatedString<string[]>
      shooting_hud_effect: boolean
      shooting_max_LRUD: vector
      shooting_max_LRUD_aim: vector
      shooting_min_LRUD_power: number
      shooting_ret_aim_speed: number
      shooting_ret_speed: number
      strafe_hud_offset_pos: vector
      strafe_hud_offset_pos_16x9: vector
      strafe_hud_offset_rot: vector
      strafe_hud_offset_rot_16x9: vector
      strafe_transition_time: number
      ts_pattern_idle2sprint: CommaSeparatedString<string[]>
      ts_pattern_sprint2idle: CommaSeparatedString<string[]>
      zoom_hide_crosshair: boolean
    }
    wpn_pm_custom_lazup_pl15: {
      description: string
      hud: string
      icons_texture: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      laser_status: boolean
      use_alt_aim_hud: boolean
    }
    wpn_pm_sk1_lazup_pl15_hud: Omit<ModSystemZz3dssPmIni['wpn_pm_sk1_new_hud'], 'aim_hud_offset_alt_pos' | 'aim_hud_offset_alt_pos_16x9' | 'aim_hud_offset_alt_rot' | 'aim_hud_offset_alt_rot_16x9' | 'item_visual'> & {
      aim_hud_offset_alt_pos: vector
      aim_hud_offset_alt_pos_16x9: vector
      aim_hud_offset_alt_rot: CommaSeparatedString<string[]>
      aim_hud_offset_alt_rot_16x9: CommaSeparatedString<string[]>
      item_visual: string
    }
  }

  interface IniFileSchemas {
    'mod_system_zz_3dss_pm.ltx': ModSystemZz3dssPmIni
  }
}
