// AUTO-GENERATED addon pack for `3dss-for-gamma` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
// `items/weapons/w_rpk.ltx` is never opened directly — `items/weapons/base.ltx` globs it in, so these sections augment
// that file's schema. The interface is path-derived, so every mod contributing to it merges here.
import type { CommaSeparatedString } from 'anomaly-packer'
declare global {
  interface ItemsWeaponsBaseIni {
    wpn_rpk: {
      $npc: boolean
      $prefetch: number
      $spawn: string
      ammo_class: CommaSeparatedString<string[]>
      ammo_elapsed: number
      ammo_mag_size: number
      animation_slot: number
      bullet_speed: number
      cam_dispersion: number
      cam_dispersion_frac: number
      cam_dispersion_inc: number
      cam_max_angle: number
      cam_max_angle_horz: number
      cam_relax_speed: number
      cam_relax_speed_ai: number
      cam_return: number
      cam_step_angle_horz: number
      cform: string
      class: string
      condition_queue_shot_dec: number
      condition_shot_dec: number
      control_inertion_factor: string
      cost: number
      crosshair_inertion: number
      default_to_ruck: boolean
      description: string
      ef_main_weapon_type: number
      ef_weapon_type: number
      fire_dispersion_base: number
      fire_dispersion_condition_factor: number
      fire_distance: number
      fire_modes: CommaSeparatedString<string[]>
      fire_point: vector
      fire_point2: vector
      flame_particles: string
      grenade_class: CommaSeparatedString<string[]>
      grenade_flame_particles: string
      grenade_launcher_name: string
      grenade_launcher_status: number
      grenade_launcher_x: number
      grenade_launcher_y: number
      GroupControlSection: string
      hand_dependence: number
      hit_impulse: number
      hit_power: vector
      hit_probability_gd_master: number
      hit_probability_gd_novice: number
      hit_probability_gd_stalker: number
      hit_probability_gd_veteran: number
      hit_type: string
      holder_fov_modifier: number
      holder_range_modifier: number
      hud: string
      installed_upgrades: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      kind: string
      launch_speed: number
      light_color: vector
      light_disabled: boolean
      light_range: number
      light_time: number
      light_var_color: number
      light_var_range: number
      max_radius: number
      min_radius: number
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_probability: number
      misfire_start_condition: number
      misfire_start_prob: number
      orientation: vector
      PDM_disp_accel_factor: number
      PDM_disp_base: number
      PDM_disp_crouch: number
      PDM_disp_crouch_no_acc: number
      PDM_disp_vel_factor: number
      ph_mass: number
      position: vector
      reload_dof: vector
      repair_type: string
      rpm: number
      rpm_empty_click: number
      scheduled: boolean
      scope_status: number
      scope_zoom_factor: number
      scripted_snd_ammo_check: string
      scripted_snd_ammo_check_empty: string
      scripted_snd_ammo_check_empty_jammed: string
      scripted_snd_ammo_check_jammed: string
      scripted_snd_ammo_check_no_mag: string
      scripted_snd_sprint2walk: string
      scripted_snd_walk2sprint: string
      silencer_light_color: vector
      silencer_light_range: number
      silencer_light_time: number
      silencer_light_var_color: number
      silencer_light_var_range: number
      silencer_name: string
      silencer_smoke_particles: string
      silencer_status: number
      silencer_x: number
      silencer_y: number
      single_handed: number
      slot: number
      smoke_particles: string
      snd_bore: string
      snd_draw: string
      snd_empty: string
      snd_holster: string
      snd_reload: string
      snd_reload_empty: string
      snd_reload_misfire: string
      snd_switch_mode: string
      sprint_allowed: boolean
      startup_ammo: number
      strap_bone0: string
      strap_bone1: string
      strap_orientation: vector
      strap_position: vector
      time_to_aim: number
      upgr_icon_height: number
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      upgrade_scheme: string
      upgrades: CommaSeparatedString<string[]>
      use_aim_bullet: boolean
      visual: string
      weapon_class: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_frac: number
      zoom_cam_dispersion_inc: number
      zoom_cam_max_angle: number
      zoom_cam_max_angle_horz: number
      zoom_cam_relax_speed: number
      zoom_cam_relax_speed_ai: number
      zoom_cam_step_angle_horz: number
      zoom_dof: vector
      zoom_enabled: boolean
      zoom_rotate_time: number
    }
    wpn_rpk_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_ammo_check: CommaSeparatedString<string[]>
      anm_ammo_check_empty: CommaSeparatedString<string[]>
      anm_ammo_check_empty_jammed: CommaSeparatedString<string[]>
      anm_ammo_check_jammed: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_empty_jammed: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_hide: CommaSeparatedString<string[]>
      anm_hide_jammed: CommaSeparatedString<string[]>
      anm_idle: CommaSeparatedString<string[]>
      anm_idle_aim: CommaSeparatedString<string[]>
      anm_idle_aim_end: CommaSeparatedString<string[]>
      anm_idle_aim_end_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_start: CommaSeparatedString<string[]>
      anm_idle_aim_start_jammed: CommaSeparatedString<string[]>
      anm_idle_jammed: CommaSeparatedString<string[]>
      anm_idle_moving: CommaSeparatedString<string[]>
      anm_idle_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_sprint: CommaSeparatedString<string[]>
      anm_idle_sprint_jammed: CommaSeparatedString<string[]>
      anm_reload: CommaSeparatedString<string[]>
      anm_reload_empty: CommaSeparatedString<string[]>
      anm_reload_misfire: CommaSeparatedString<string[]>
      anm_shots: string
      anm_shots_aim: string
      anm_show: CommaSeparatedString<string[]>
      anm_show_jammed: CommaSeparatedString<string[]>
      anm_sprint2walk: CommaSeparatedString<string[]>
      anm_sprint2walk_jammed: CommaSeparatedString<string[]>
      anm_switch_mode: CommaSeparatedString<string[]>
      anm_switch_mode_jammed: CommaSeparatedString<string[]>
      anm_walk2sprint: CommaSeparatedString<string[]>
      anm_walk2sprint_jammed: CommaSeparatedString<string[]>
      attach_place_idx: number
      fire_bone: string
      fire_point: vector
      gl_hud_offset_pos: vector
      gl_hud_offset_pos_16x9: vector
      gl_hud_offset_rot: vector
      gl_hud_offset_rot_16x9: vector
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lean_hud_offset_pos: vector
      lean_hud_offset_rot: vector
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      ts_pattern_sprint2walk: CommaSeparatedString<string[]>
      ts_pattern_sprint2walk_aim: CommaSeparatedString<string[]>
      ts_pattern_walk2sprint: CommaSeparatedString<string[]>
      ts_strict_aim2sprint: CommaSeparatedString<string[]>
      ts_strict_sprint2aim: CommaSeparatedString<string[]>
      ts_strict_sprint2aimthing: CommaSeparatedString<string[]>
      ts_strict_sprint2inspect: CommaSeparatedString<string[]>
      ts_strict_sprint2walk_idle: CommaSeparatedString<string[]>
      ts_strict_sprint2walk_move: CommaSeparatedString<string[]>
      ts_strict_walk2sprint_inspect: CommaSeparatedString<string[]>
      zoom_hide_crosshair: boolean
    }
    wpn_rpk74: Omit<ItemsWeaponsBaseIni['wpn_rpk'], 'ammo_class' | 'ammo_elapsed' | 'ammo_mag_size' | 'bullet_speed' | 'cam_dispersion' | 'cam_dispersion_frac' | 'cam_dispersion_inc' | 'cam_max_angle' | 'cam_max_angle_horz' | 'cam_relax_speed' | 'cam_relax_speed_ai' | 'cam_return' | 'cam_step_angle_horz' | 'condition_queue_shot_dec' | 'condition_shot_dec' | 'control_inertion_factor' | 'cost' | 'crosshair_inertion' | 'description' | 'fire_dispersion_base' | 'fire_dispersion_condition_factor' | 'fire_distance' | 'fire_modes' | 'grenade_class' | 'grenade_launcher_name' | 'grenade_launcher_x' | 'grenade_launcher_y' | 'hit_power' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'kill_msg_height' | 'kill_msg_width' | 'kill_msg_x' | 'kill_msg_y' | 'kind' | 'misfire_end_condition' | 'misfire_end_prob' | 'misfire_probability' | 'misfire_start_condition' | 'misfire_start_prob' | 'parent_section' | 'PDM_disp_accel_factor' | 'PDM_disp_base' | 'PDM_disp_crouch' | 'PDM_disp_crouch_no_acc' | 'PDM_disp_vel_factor' | 'repair_type' | 'rpm' | 'scope_status' | 'scope_zoom_factor' | 'scopes' | 'silencer_light_color' | 'silencer_light_range' | 'silencer_light_time' | 'silencer_light_var_color' | 'silencer_light_var_range' | 'silencer_name' | 'silencer_smoke_particles' | 'silencer_status' | 'silencer_x' | 'silencer_y' | 'upgr_icon_height' | 'upgr_icon_width' | 'upgr_icon_x' | 'upgr_icon_y' | 'upgrades' | 'visual' | 'zoom_cam_dispersion' | 'zoom_cam_dispersion_frac' | 'zoom_cam_dispersion_inc' | 'zoom_cam_max_angle' | 'zoom_cam_max_angle_horz' | 'zoom_cam_relax_speed' | 'zoom_cam_relax_speed_ai' | 'zoom_cam_step_angle_horz' | 'zoom_enabled' | 'zoom_rotate_time'> & {
      ammo_class: CommaSeparatedString<string[]>
      ammo_elapsed: number
      ammo_mag_size: number
      bullet_speed: number
      cam_dispersion: number
      cam_dispersion_frac: number
      cam_dispersion_inc: number
      cam_max_angle: number
      cam_max_angle_horz: number
      cam_relax_speed: number
      cam_relax_speed_ai: number
      cam_return: number
      cam_step_angle_horz: number
      condition_queue_shot_dec: number
      condition_shot_dec: number
      control_inertion_factor: string
      cost: number
      crosshair_inertion: number
      description: string
      fire_dispersion_base: number
      fire_dispersion_condition_factor: number
      fire_distance: number
      fire_modes: CommaSeparatedString<string[]>
      grenade_class: CommaSeparatedString<string[]>
      grenade_launcher_name: string
      grenade_launcher_x: number
      grenade_launcher_y: number
      hit_power: vector
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      kind: string
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_probability: number
      misfire_start_condition: number
      misfire_start_prob: number
      parent_section: string
      PDM_disp_accel_factor: number
      PDM_disp_base: number
      PDM_disp_crouch: number
      PDM_disp_crouch_no_acc: number
      PDM_disp_vel_factor: number
      repair_type: string
      rpm: number
      scope_status: number
      scope_zoom_factor: number
      scopes: CommaSeparatedString<string[]>
      silencer_light_color: vector
      silencer_light_range: number
      silencer_light_time: number
      silencer_light_var_color: number
      silencer_light_var_range: number
      silencer_name: string
      silencer_smoke_particles: string
      silencer_status: number
      silencer_x: number
      silencer_y: number
      upgr_icon_height: number
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      upgrades: CommaSeparatedString<string[]>
      visual: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_frac: number
      zoom_cam_dispersion_inc: number
      zoom_cam_max_angle: number
      zoom_cam_max_angle_horz: number
      zoom_cam_relax_speed: number
      zoom_cam_relax_speed_ai: number
      zoom_cam_step_angle_horz: number
      zoom_enabled: boolean
      zoom_rotate_time: number
    }
    wpn_rpk74_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_ammo_check: CommaSeparatedString<string[]>
      anm_ammo_check_empty: CommaSeparatedString<string[]>
      anm_ammo_check_empty_jammed: CommaSeparatedString<string[]>
      anm_ammo_check_jammed: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_empty_jammed: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_hide: CommaSeparatedString<string[]>
      anm_hide_jammed: CommaSeparatedString<string[]>
      anm_idle: CommaSeparatedString<string[]>
      anm_idle_aim: CommaSeparatedString<string[]>
      anm_idle_aim_end: CommaSeparatedString<string[]>
      anm_idle_aim_end_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_start: CommaSeparatedString<string[]>
      anm_idle_aim_start_jammed: CommaSeparatedString<string[]>
      anm_idle_jammed: CommaSeparatedString<string[]>
      anm_idle_moving: CommaSeparatedString<string[]>
      anm_idle_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_sprint: CommaSeparatedString<string[]>
      anm_idle_sprint_jammed: CommaSeparatedString<string[]>
      anm_reload: CommaSeparatedString<string[]>
      anm_reload_empty: CommaSeparatedString<string[]>
      anm_reload_misfire: CommaSeparatedString<string[]>
      anm_shots: string
      anm_shots_aim: string
      anm_show: CommaSeparatedString<string[]>
      anm_show_jammed: CommaSeparatedString<string[]>
      anm_sprint2walk: CommaSeparatedString<string[]>
      anm_sprint2walk_jammed: CommaSeparatedString<string[]>
      anm_switch_mode: CommaSeparatedString<string[]>
      anm_switch_mode_jammed: CommaSeparatedString<string[]>
      anm_walk2sprint: CommaSeparatedString<string[]>
      anm_walk2sprint_jammed: CommaSeparatedString<string[]>
      attach_place_idx: number
      fire_bone: string
      fire_point: vector
      gl_hud_offset_pos: vector
      gl_hud_offset_pos_16x9: vector
      gl_hud_offset_rot: vector
      gl_hud_offset_rot_16x9: vector
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lean_hud_offset_pos: vector
      lean_hud_offset_rot: vector
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      ts_pattern_sprint2walk: CommaSeparatedString<string[]>
      ts_pattern_sprint2walk_aim: CommaSeparatedString<string[]>
      ts_pattern_walk2sprint: CommaSeparatedString<string[]>
      ts_strict_aim2sprint: CommaSeparatedString<string[]>
      ts_strict_sprint2aim: CommaSeparatedString<string[]>
      ts_strict_sprint2aimthing: CommaSeparatedString<string[]>
      ts_strict_sprint2inspect: CommaSeparatedString<string[]>
      ts_strict_sprint2walk_idle: CommaSeparatedString<string[]>
      ts_strict_sprint2walk_move: CommaSeparatedString<string[]>
      ts_strict_walk2sprint_inspect: CommaSeparatedString<string[]>
      zoom_hide_crosshair: boolean
    }
    wpn_rpk74_1p29: Omit<ItemsWeaponsBaseIni['wpn_rpk74'], '1icon_layer' | '1icon_layer_x' | '1icon_layer_y' | 'hud' | 'visual'> & {
      '1icon_layer': string
      '1icon_layer_x': number
      '1icon_layer_y': number
      hud: string
      visual: string
    }
    wpn_rpk74_1p29_hud: Omit<ItemsWeaponsBaseIni['wpn_rpk74_hud'], 'item_visual'> & {
      item_visual: string
    }
    wpn_rpk74_kobra: Omit<ItemsWeaponsBaseIni['wpn_rpk74'], '1icon_layer' | '1icon_layer_x' | '1icon_layer_y' | 'hud' | 'inv_weight' | 'visual'> & {
      '1icon_layer': string
      '1icon_layer_x': number
      '1icon_layer_y': number
      hud: string
      inv_weight: number
      visual: string
    }
    wpn_rpk74_kobra_hud: Omit<ItemsWeaponsBaseIni['wpn_rpk74_hud'], 'item_visual'> & {
      item_visual: string
    }
    wpn_rpk74_ps01: Omit<ItemsWeaponsBaseIni['wpn_rpk74'], '1icon_layer' | '1icon_layer_x' | '1icon_layer_y' | 'hud'> & {
      '1icon_layer': string
      '1icon_layer_x': number
      '1icon_layer_y': number
      hud: string
    }
    wpn_rpk_sk1_hud: Omit<ItemsWeaponsBaseIni['wpn_rpk_hud'], 'anm_reload' | 'anm_reload_empty' | 'item_visual'> & {
      anm_reload: CommaSeparatedString<string[]>
      anm_reload_empty: CommaSeparatedString<string[]>
      item_visual: string
    }
  }
}
