// AUTO-GENERATED addon pack for `3dss-for-gamma` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
// `items/weapons/w_ks23.ltx` is never opened directly — `items/weapons/base.ltx` globs it in, so these sections augment
// that file's schema. The interface is path-derived, so every mod contributing to it merges here.
import type { CommaSeparatedString } from 'anomaly-packer'
declare global {
  interface ItemsWeaponsBaseIni {
    wpn_ks23: {
      $npc: boolean
      $prefetch: number
      $spawn: string
      ammo_class: CommaSeparatedString<string[]>
      ammo_elapsed: number
      ammo_mag_size: number
      animation_slot: number
      bullet_speed: number
      cam_dispersion: number
      cam_dispersion_frac: number
      cam_dispersion_inc: number
      cam_max_angle: number
      cam_max_angle_horz: number
      cam_relax_speed: number
      cam_relax_speed_ai: number
      cam_return: number
      cam_step_angle_horz: number
      cform: string
      class: string
      condition_queue_shot_dec: number
      condition_shot_dec: number
      control_inertion_factor: string
      cost: number
      crosshair_inertion: number
      description: string
      ef_main_weapon_type: number
      ef_weapon_type: number
      fire_dispersion_base: number
      fire_dispersion_condition_factor: number
      fire_distance: number
      fire_modes: number
      fire_point: vector
      fire_point2: vector
      flame_particles: string
      grenade_flame_particles: string
      grenade_launcher_status: number
      GroupControlSection: string
      hand_dependence: number
      hit_impulse: number
      hit_power: vector
      hit_probability_gd_master: number
      hit_probability_gd_novice: number
      hit_probability_gd_stalker: number
      hit_probability_gd_veteran: number
      hit_type: string
      holder_fov_modifier: number
      holder_range_modifier: number
      hud: string
      icons_texture: string
      installed_upgrades: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      kind: string
      light_color: vector
      light_range: number
      light_time: number
      light_var_color: number
      light_var_range: number
      max_radius: number
      min_radius: number
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_probability: number
      misfire_start_condition: number
      misfire_start_prob: number
      orientation: vector
      parent_section: string
      PDM_disp_accel_factor: number
      PDM_disp_base: number
      PDM_disp_crouch: number
      PDM_disp_crouch_no_acc: number
      PDM_disp_vel_factor: number
      ph_mass: number
      position: vector
      repair_type: string
      rpm: number
      rpm_empty_click: number
      scheduled: boolean
      scope_status: number
      scope_zoom_factor: number
      scopes: string
      scripted_snd_add_cartridge: string
      scripted_snd_add_cartridge_empty: string
      scripted_snd_anm_close_pump: string
      scripted_snd_close: string
      scripted_snd_open: string
      scripted_snd_open_empty: string
      scripted_snd_reload_misfire: string
      scripted_snd_reloadendemptytac_end: string
      scripted_snd_reloadendtac_end: string
      scripted_snd_reloadendtacnachalo_end: string
      scripted_snd_rotatetac_start: string
      scripted_snd_startzarada: string
      silencer_smoke_particles: string
      silencer_status: number
      single_handed: number
      slot: number
      smoke_particles: string
      snd_add_cartridge: string
      snd_bore: string
      snd_close_weapon: string
      snd_draw: string
      snd_empty: string
      snd_holster: string
      snd_open_weapon: string
      snd_reload: string
      snd_shoot: string
      snd_shoot_duplet: string
      snd_silncer_shot: string
      snd_silncer_shot_actor: string
      startup_ammo: number
      strap_bone0: string
      strap_bone1: string
      strap_orientation: vector
      strap_position: vector
      tri_state_reload: boolean
      upgr_icon_height: number
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      upgrade_scheme: string
      upgrades: CommaSeparatedString<string[]>
      use_alt_aim_hud: boolean
      visual: string
      weapon_class: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_frac: number
      zoom_cam_dispersion_inc: number
      zoom_cam_max_angle: number
      zoom_cam_max_angle_horz: number
      zoom_cam_relax_speed: number
      zoom_cam_relax_speed_ai: number
      zoom_cam_step_angle_horz: number
      zoom_dof: vector
      zoom_enabled: boolean
    }
    wpn_ks23_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_add_cartridge: CommaSeparatedString<string[]>
      anm_add_cartridge_empty: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_close: CommaSeparatedString<string[]>
      anm_hide: CommaSeparatedString<string[]>
      anm_hide_jammed: CommaSeparatedString<string[]>
      anm_idle: CommaSeparatedString<string[]>
      anm_idle_aim: CommaSeparatedString<string[]>
      anm_idle_aim_end: CommaSeparatedString<string[]>
      anm_idle_aim_end_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_start: CommaSeparatedString<string[]>
      anm_idle_aim_start_jammed: CommaSeparatedString<string[]>
      anm_idle_jammed: CommaSeparatedString<string[]>
      anm_idle_moving: CommaSeparatedString<string[]>
      anm_idle_moving_crouch: CommaSeparatedString<string[]>
      anm_idle_moving_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_sprint: CommaSeparatedString<string[]>
      anm_idle_sprint_jammed: CommaSeparatedString<string[]>
      anm_open: CommaSeparatedString<string[]>
      anm_open_empty: CommaSeparatedString<string[]>
      anm_reload_misfire: CommaSeparatedString<string[]>
      anm_reloadendemptytac_end: CommaSeparatedString<string[]>
      anm_reloadendtac_end: CommaSeparatedString<string[]>
      anm_reloadendtacnachalo_end: CommaSeparatedString<string[]>
      anm_rotatetac_start: CommaSeparatedString<string[]>
      anm_shots: CommaSeparatedString<string[]>
      anm_shots_aim: CommaSeparatedString<string[]>
      anm_show: CommaSeparatedString<string[]>
      anm_show_jammed: CommaSeparatedString<string[]>
      anm_sprint_end: CommaSeparatedString<string[]>
      anm_sprint_end_jammed: CommaSeparatedString<string[]>
      anm_sprint_start: CommaSeparatedString<string[]>
      anm_sprint_start_jammed: CommaSeparatedString<string[]>
      anm_startzarada: CommaSeparatedString<string[]>
      attach_place_idx: number
      fire_bone: string
      fire_point: vector
      freelook_z_offset_mul: number
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      orientation: vector
      position: vector
      shell_bone: string
      shell_dir: vector
      shell_point: vector
      strap_position: vector
      ts_pattern_reloadend_end: CommaSeparatedString<string[]>
      ts_pattern_reloadendbegin_end: CommaSeparatedString<string[]>
      ts_pattern_reloadendstandart_end: CommaSeparatedString<string[]>
      ts_pattern_reloadendstandartopen_end: CommaSeparatedString<string[]>
      ts_pattern_reloadendtwo_end: CommaSeparatedString<string[]>
      ts_pattern_sprint_end: CommaSeparatedString<string[]>
      ts_pattern_sprint_start: CommaSeparatedString<string[]>
      ts_strict_rotate_end: CommaSeparatedString<string[]>
      ts_strict_rotate_start: CommaSeparatedString<string[]>
      ts_strict_sprint_end_move: CommaSeparatedString<string[]>
      zoom_hide_crosshair: boolean
    }
    wpn_ks23_23_up: Omit<ItemsWeaponsBaseIni['wpn_ks23'], 'cam_dispersion' | 'cam_dispersion_inc' | 'description' | 'hit_impulse' | 'hit_power' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'scopes' | 'visual' | 'zoom_cam_step_angle_horz'> & {
      cam_dispersion: number
      cam_dispersion_inc: number
      description: string
      hit_impulse: number
      hit_power: vector
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      scopes: string
      visual: string
      zoom_cam_step_angle_horz: number
    }
    wpn_ks23_23_up_hud: Omit<ItemsWeaponsBaseIni['wpn_ks23_hud'], 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'anm_add_cartridge' | 'anm_add_cartridge_empty' | 'anm_bore' | 'anm_bore_jammed' | 'anm_startzarada' | 'hands_orientation' | 'hands_orientation_16x9' | 'hands_position' | 'hands_position_16x9' | 'item_orientation' | 'item_position' | 'item_visual'> & {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_add_cartridge: CommaSeparatedString<string[]>
      anm_add_cartridge_empty: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_startzarada: CommaSeparatedString<string[]>
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
    }
    wpn_ks23_kaban: Omit<ItemsWeaponsBaseIni['wpn_ks23'], 'cam_dispersion' | 'cam_dispersion_inc' | 'cost' | 'description' | 'hit_impulse' | 'hit_power' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'scope_zoom_factor_alt' | 'scopes' | 'upgr_icon_height' | 'upgr_icon_path' | 'upgr_icon_width' | 'upgr_icon_x' | 'upgr_icon_y' | 'visual' | 'zoom_cam_step_angle_horz'> & {
      cam_dispersion: number
      cam_dispersion_inc: number
      cost: number
      description: string
      hit_impulse: number
      hit_power: vector
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      scope_zoom_factor_alt: number
      scopes: string
      upgr_icon_height: number
      upgr_icon_path: string
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      visual: string
      zoom_cam_step_angle_horz: number
    }
    wpn_ks23_kaban_hud: Omit<ItemsWeaponsBaseIni['wpn_ks23_hud'], 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'anm_add_cartridge' | 'anm_add_cartridge_empty' | 'anm_bore' | 'anm_bore_jammed' | 'anm_startzarada' | 'hands_orientation' | 'hands_orientation_16x9' | 'hands_position' | 'hands_position_16x9' | 'item_orientation' | 'item_position' | 'item_visual'> & {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_add_cartridge: CommaSeparatedString<string[]>
      anm_add_cartridge_empty: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_startzarada: CommaSeparatedString<string[]>
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
    }
    wpn_ks23_kaban_kab_up: Omit<ItemsWeaponsBaseIni['wpn_ks23_kaban'], 'cam_dispersion' | 'cam_dispersion_inc' | 'description' | 'fire_point' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'scopes' | 'silencer_light_color' | 'silencer_light_range' | 'silencer_light_time' | 'silencer_light_var_color' | 'silencer_light_var_range' | 'silencer_name' | 'silencer_status' | 'silencer_x' | 'silencer_y' | 'upgr_icon_height' | 'upgr_icon_path' | 'upgr_icon_width' | 'upgr_icon_x' | 'upgr_icon_y' | 'visual' | 'zoom_cam_step_angle_horz'> & {
      cam_dispersion: number
      cam_dispersion_inc: number
      description: string
      fire_point: vector
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      scopes: string
      silencer_light_color: vector
      silencer_light_range: number
      silencer_light_time: number
      silencer_light_var_color: number
      silencer_light_var_range: number
      silencer_name: string
      silencer_status: number
      silencer_x: number
      silencer_y: number
      upgr_icon_height: number
      upgr_icon_path: string
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      visual: string
      zoom_cam_step_angle_horz: number
    }
    wpn_ks23_kaban_kab_up_hud: Omit<ItemsWeaponsBaseIni['wpn_ks23_kaban_hud'], 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'anm_add_cartridge' | 'anm_add_cartridge_empty' | 'anm_bore' | 'anm_bore_jammed' | 'anm_startzarada' | 'hands_orientation' | 'hands_orientation_16x9' | 'hands_position' | 'hands_position_16x9' | 'item_orientation' | 'item_position' | 'item_visual'> & {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_add_cartridge: CommaSeparatedString<string[]>
      anm_add_cartridge_empty: CommaSeparatedString<string[]>
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_startzarada: CommaSeparatedString<string[]>
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
    }
  }
}
