// AUTO-GENERATED addon pack for `3dss-for-gamma` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
// `items/weapons/w_remington700.ltx` is never opened directly — `items/weapons/base.ltx` globs it in, so these sections augment
// that file's schema. The interface is path-derived, so every mod contributing to it merges here.
import type { CommaSeparatedString } from 'anomaly-packer'
declare global {
  interface ItemsWeaponsBaseIni {
    wpn_remington700: {
      $npc: boolean
      $prefetch: number
      $spawn: string
      ammo_class: CommaSeparatedString<string[]>
      ammo_current: number
      ammo_elapsed: number
      ammo_limit: number
      ammo_mag_size: number
      animation_slot: number
      bullet_speed: number
      cam_dispersion: number
      cam_dispersion_frac: number
      cam_dispersion_inc: number
      cam_max_angle: number
      cam_max_angle_horz: number
      cam_relax_speed: number
      cam_relax_speed_ai: number
      cam_return: number
      cam_step_angle_horz: number
      cform: string
      class: string
      condition_queue_shot_dec: number
      condition_shot_dec: number
      control_inertion_factor: string
      cost: number
      crosshair_inertion: number
      description: string
      ef_main_weapon_type: number
      ef_weapon_type: number
      fire_dispersion_base: number
      fire_dispersion_condition_factor: number
      fire_distance: number
      fire_modes: number
      fire_point: vector
      fire_point2: vector
      flame_particles: string
      grenade_launcher_status: number
      hand_dependence: number
      hit_impulse: number
      hit_power: vector
      hit_probability_gd_master: number
      hit_probability_gd_novice: number
      hit_probability_gd_stalker: number
      hit_probability_gd_veteran: number
      hit_type: string
      holder_fov_modifier: number
      holder_range_modifier: number
      hud: string
      icons_texture: string
      installed_upgrades: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      kind: string
      light_color: vector
      light_disabled: boolean
      light_range: number
      light_time: number
      light_var_color: number
      light_var_range: number
      max_radius: number
      min_radius: number
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_probability: number
      misfire_start_condition: number
      misfire_start_prob: number
      orientation: vector
      parent_section: string
      PDM_disp_accel_factor: number
      PDM_disp_base: number
      PDM_disp_crouch: number
      PDM_disp_crouch_no_acc: number
      PDM_disp_vel_factor: number
      ph_mass: number
      position: vector
      reload_dof: vector
      repair_type: string
      rpm: number
      rpm_empty_click: number
      scheduled: boolean
      scope_dynamic_zoom: boolean
      scope_status: number
      scope_texture: string
      scope_x: number
      scope_y: number
      scope_zoom_factor: number
      scopes: CommaSeparatedString<string[]>
      shell_dir: vector
      shell_point: vector
      silencer_light_color: vector
      silencer_light_range: number
      silencer_light_time: number
      silencer_light_var_color: number
      silencer_light_var_range: number
      silencer_name: string
      silencer_smoke_particles: string
      silencer_status: number
      silencer_x: number
      silencer_y: number
      single_handed: number
      slot: number
      smoke_particles: string
      startup_ammo: number
      strap_bone0: string
      strap_bone1: string
      strap_orientation: vector
      strap_position: vector
      time_to_aim: number
      upgr_icon_height: number
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      upgrade_scheme: string
      upgrades: CommaSeparatedString<string[]>
      use_aim_bullet: boolean
      visual: string
      weapon_class: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_frac: number
      zoom_cam_dispersion_inc: number
      zoom_cam_max_angle: number
      zoom_cam_max_angle_horz: number
      zoom_cam_relax_speed: number
      zoom_cam_relax_speed_ai: number
      zoom_cam_step_angle_horz: number
      zoom_enabled: boolean
      zoom_rotate_time: number
    }
    wpn_remington700_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      attach_place_idx: number
      fire_bone: string
      fire_bone2: string
      fire_point: vector
      fire_point2: vector
      freelook_z_offset_mul: number
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      shell_bone: string
      shell_dir: vector
      shell_point: vector
      zoom_hide_crosshair: boolean
    }
    wpn_remington700_archangel: Omit<ItemsWeaponsBaseIni['wpn_remington700'], 'ammo_mag_size' | 'bullet_speed' | 'description' | 'fire_dispersion_base' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'silencer_x' | 'silencer_y' | 'startup_ammo' | 'visual' | 'zoom_cam_dispersion' | 'zoom_cam_dispersion_inc' | 'zoom_cam_step_angle_horz'> & {
      ammo_mag_size: number
      bullet_speed: number
      description: string
      fire_dispersion_base: number
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      silencer_x: number
      silencer_y: number
      startup_ammo: number
      visual: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_inc: number
      zoom_cam_step_angle_horz: number
    }
    wpn_remington700_archangel_hud: Omit<ItemsWeaponsBaseIni['wpn_remington700_hud'], 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'item_visual'> & {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      item_visual: string
    }
    wpn_remington700_magpul_pro: Omit<ItemsWeaponsBaseIni['wpn_remington700'], 'ammo_mag_size' | 'bullet_speed' | 'description' | 'fire_dispersion_base' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'silencer_x' | 'silencer_y' | 'startup_ammo' | 'use_alt_aim_hud' | 'visual' | 'zoom_cam_dispersion' | 'zoom_cam_dispersion_inc' | 'zoom_cam_step_angle_horz'> & {
      ammo_mag_size: number
      bullet_speed: number
      description: string
      fire_dispersion_base: number
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      silencer_x: number
      silencer_y: number
      startup_ammo: number
      use_alt_aim_hud: boolean
      visual: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_inc: number
      zoom_cam_step_angle_horz: number
    }
    wpn_remington700_magpul_pro_hud: Omit<ItemsWeaponsBaseIni['wpn_remington700_hud'], 'aim_hud_offset_alt_pos' | 'aim_hud_offset_alt_pos_16x9' | 'aim_hud_offset_alt_rot' | 'aim_hud_offset_alt_rot_16x9' | 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'item_visual'> & {
      aim_hud_offset_alt_pos: vector
      aim_hud_offset_alt_pos_16x9: vector
      aim_hud_offset_alt_rot: vector
      aim_hud_offset_alt_rot_16x9: vector
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      item_visual: string
    }
    wpn_remington700_mod_x_gen3: Omit<ItemsWeaponsBaseIni['wpn_remington700'], 'ammo_mag_size' | 'bullet_speed' | 'description' | 'fire_dispersion_base' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'silencer_x' | 'silencer_y' | 'startup_ammo' | 'use_alt_aim_hud' | 'visual' | 'zoom_cam_dispersion' | 'zoom_cam_dispersion_inc' | 'zoom_cam_step_angle_horz'> & {
      ammo_mag_size: number
      bullet_speed: number
      description: string
      fire_dispersion_base: number
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      silencer_x: number
      silencer_y: number
      startup_ammo: number
      use_alt_aim_hud: boolean
      visual: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_inc: number
      zoom_cam_step_angle_horz: number
    }
    wpn_remington700_mod_x_gen3_hud: Omit<ItemsWeaponsBaseIni['wpn_remington700_hud'], 'aim_hud_offset_alt_pos' | 'aim_hud_offset_alt_pos_16x9' | 'aim_hud_offset_alt_rot' | 'aim_hud_offset_alt_rot_16x9' | 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'item_visual'> & {
      aim_hud_offset_alt_pos: vector
      aim_hud_offset_alt_pos_16x9: vector
      aim_hud_offset_alt_rot: vector
      aim_hud_offset_alt_rot_16x9: vector
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      item_visual: string
    }
    wpn_remington700_lapua700: Omit<ItemsWeaponsBaseIni['wpn_remington700'], 'ammo_class' | 'ammo_mag_size' | 'bullet_speed' | 'description' | 'fire_dispersion_base' | 'hit_power' | 'hud' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'parent_section' | 'silencer_name' | 'silencer_x' | 'silencer_y' | 'startup_ammo' | 'visual' | 'zoom_cam_dispersion' | 'zoom_cam_dispersion_inc' | 'zoom_cam_step_angle_horz'> & {
      ammo_class: CommaSeparatedString<string[]>
      ammo_mag_size: number
      bullet_speed: number
      description: string
      fire_dispersion_base: number
      hit_power: vector
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      parent_section: string
      silencer_name: string
      silencer_x: number
      silencer_y: number
      startup_ammo: number
      visual: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_inc: number
      zoom_cam_step_angle_horz: number
    }
    wpn_remington700_lapua700_hud: Omit<ItemsWeaponsBaseIni['wpn_remington700_hud'], 'aim_hud_offset_pos' | 'aim_hud_offset_pos_16x9' | 'aim_hud_offset_rot' | 'aim_hud_offset_rot_16x9' | 'item_visual'> & {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      item_visual: string
    }
  }
}
