// AUTO-GENERATED addon pack for `3dss-for-gamma` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
// `items/weapons/w_rpg7.ltx` is never opened directly — `items/weapons/base.ltx` globs it in, so these sections augment
// that file's schema. The interface is path-derived, so every mod contributing to it merges here.
import type { CommaSeparatedString } from 'anomaly-packer'
declare global {
  interface ItemsWeaponsBaseIni {
    wpn_rpg7: {
      $prefetch: number
      $spawn: string
      ammo_class: CommaSeparatedString<string[]>
      ammo_current: number
      ammo_elapsed: number
      ammo_limit: number
      ammo_mag_size: number
      animation_slot: number
      auto_spawn_ammo: boolean
      bullet_speed: number
      cam_dispersion: number
      cam_max_angle: number
      cam_max_angle_horz: number
      cam_relax_speed: number
      cam_relax_speed_ai: number
      cam_step_angle_horz: number
      cform: string
      class: string
      condition_queue_shot_dec: number
      condition_shot_dec: number
      control_inertion_factor: string
      cost: number
      crosshair_inertion: number
      description: string
      discovery_dependency: string
      ef_main_weapon_type: number
      ef_weapon_type: number
      explode_duration: number
      fire_dispersion_base: number
      fire_dispersion_condition_factor: number
      fire_distance: number
      fire_point: vector
      fragment_speed: number
      grenade_launcher_status: number
      GroupControlSection: string
      hand_dependence: number
      hit_impulse: number
      hit_power: number
      hit_type: string
      holder_fov_modifier: number
      holder_range_modifier: number
      hud: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      kind: string
      launch_speed: number
      light_color: vector
      light_range: number
      light_time: number
      light_var_color: number
      light_var_range: number
      max_radius: number
      max_zoom_factor: number
      min_radius: number
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_probability: number
      misfire_start_condition: number
      misfire_start_prob: number
      orientation: vector
      PDM_disp_accel_factor: number
      PDM_disp_base: number
      PDM_disp_crouch: number
      PDM_disp_crouch_no_acc: number
      PDM_disp_vel_factor: number
      ph_mass: number
      position: vector
      reload_dof: vector
      rocket_class: string
      rpm: number
      scheduled: boolean
      scope_status: number
      scope_zoom_factor: number
      silencer_status: number
      single_handed: number
      slot: number
      smoke_particles: string
      sprint_allowed: boolean
      strap_bone0: string
      strap_bone1: string
      strap_orientation: vector
      strap_position: vector
      upgr_icon_height: number
      upgr_icon_path: string
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      visual: string
      wallmark_section: string
      weapon_class: string
      zoom_dof: vector
      zoom_enabled: boolean
    }
    wpn_rpg7_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: CommaSeparatedString<string[]>
      aim_hud_offset_rot_16x9: vector
      anm_bore: string
      anm_hide: string
      anm_idle: string
      anm_idle_aim: CommaSeparatedString<string[]>
      anm_idle_aim_moving: string
      anm_idle_moving: string
      anm_idle_moving_crouch: string
      anm_idle_moving_slow: string
      anm_idle_sprint: string
      anm_reload: CommaSeparatedString<string[]>
      anm_reload_empty: CommaSeparatedString<string[]>
      anm_shots: CommaSeparatedString<string[]>
      anm_show: string
      attach_place_idx: number
      fire_bone: string
      fire_point: vector
      gl_hud_offset_pos: vector
      gl_hud_offset_rot: vector
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lean_hud_offset_pos: vector
      lean_hud_offset_rot: vector
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      zoom_hide_crosshair: boolean
    }
    wpn_rpg7_missile: {
      $prefetch: number
      blast: number
      blast_impulse: number
      blast_impulse_factor: number
      blast_r: number
      cform: string
      class: string
      cost: number
      discovery_dependency: string
      engine_impulse: number
      engine_impulse_up: CommaSeparatedString<string[]>
      engine_particles: string
      engine_present: boolean
      engine_work_time: number
      explode_duration: number
      explode_particles: string
      force_explode_time: number
      frag_hit: number
      frag_hit_impulse: number
      fragment_speed: number
      frags: number
      frags_r: number
      GroupControlSection: string
      hit_type_blast: string
      hit_type_frag: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: string
      jump_height: number
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      light_color: vector
      light_range: number
      light_time: number
      lights_enabled: boolean
      ph_mass: number
      trail_light_color: vector
      trail_light_range: number
      up_throw_factor: number
      visual: string
      wallmark_section: string
      wm_size: number
    }
  }
}
