// AUTO-GENERATED addon pack for `3dss-for-gamma` by `anomaly-packer gen-addon`. Config ltx schemas.
// Refine `TODO` (= any) by hand where the mod gave no type.
// `items/weapons/w_gauss.ltx` is never opened directly — `items/weapons/base.ltx` globs it in, so these sections augment
// that file's schema. The interface is path-derived, so every mod contributing to it merges here.
import type { CommaSeparatedString } from 'anomaly-packer'
declare global {
  interface ItemsWeaponsBaseIni {
    wpn_gauss: Omit<ItemsWeaponsBaseIni['wpn_gauss_sounds_new'], '$npc' | '$prefetch' | '$spawn' | 'ammo_class' | 'ammo_current' | 'ammo_elapsed' | 'ammo_limit' | 'ammo_mag_size' | 'animation_slot' | 'bullet_bones' | 'bullet_speed' | 'cam_dispersion' | 'cam_dispersion_frac' | 'cam_dispersion_inc' | 'cam_max_angle' | 'cam_max_angle_horz' | 'cam_relax_speed' | 'cam_relax_speed_ai' | 'cam_return' | 'cam_step_angle_horz' | 'cform' | 'class' | 'condition_queue_shot_dec' | 'condition_shot_dec' | 'control_inertion_factor' | 'cost' | 'crosshair_inertion' | 'default_to_ruck' | 'description' | 'discovery_dependency' | 'ef_main_weapon_type' | 'ef_weapon_type' | 'fire_dispersion_base' | 'fire_dispersion_condition_factor' | 'fire_distance' | 'fire_point' | 'fire_point2' | 'flame_particles' | 'grenade_launcher_status' | 'GroupControlSection' | 'hand_dependence' | 'hit_impulse' | 'hit_power' | 'hit_probability_gd_master' | 'hit_probability_gd_novice' | 'hit_probability_gd_stalker' | 'hit_probability_gd_veteran' | 'hit_type' | 'holder_fov_modifier' | 'holder_range_modifier' | 'hud' | 'icons_texture' | 'inv_grid_height' | 'inv_grid_width' | 'inv_grid_x' | 'inv_grid_y' | 'inv_name' | 'inv_name_short' | 'inv_weight' | 'kill_msg_height' | 'kill_msg_width' | 'kill_msg_x' | 'kill_msg_y' | 'kind' | 'light_color' | 'light_disabled' | 'light_range' | 'light_time' | 'light_var_color' | 'light_var_range' | 'max_radius' | 'min_radius' | 'misfire_end_condition' | 'misfire_end_prob' | 'misfire_probability' | 'misfire_start_condition' | 'misfire_start_prob' | 'orientation' | 'PDM_disp_accel_factor' | 'PDM_disp_base' | 'PDM_disp_crouch' | 'PDM_disp_crouch_no_acc' | 'PDM_disp_vel_factor' | 'ph_mass' | 'position' | 'reload_dof' | 'repair_type' | 'rpm' | 'rpm_empty_click' | 'scheduled' | 'scope_dynamic_zoom' | 'scope_name' | 'scope_status' | 'scope_texture' | 'scope_x' | 'scope_y' | 'shell_dir' | 'shell_point' | 'silencer_status' | 'single_handed' | 'slot' | 'smoke_particles' | 'sprint_allowed' | 'startup_ammo' | 'strap_bone0' | 'strap_bone1' | 'strap_orientation' | 'strap_position' | 'time_to_aim' | 'upgr_icon_height' | 'upgr_icon_width' | 'upgr_icon_x' | 'upgr_icon_y' | 'upgrade_scheme' | 'upgrades' | 'use_aim_bullet' | 'visual' | 'weapon_class' | 'zoom_cam_dispersion' | 'zoom_cam_dispersion_frac' | 'zoom_cam_dispersion_inc' | 'zoom_cam_max_angle' | 'zoom_cam_max_angle_horz' | 'zoom_cam_relax_speed' | 'zoom_cam_relax_speed_ai' | 'zoom_cam_step_angle_horz' | 'zoom_enabled' | 'zoom_rotate_time'> & {
      $npc: boolean
      $prefetch: number
      $spawn: string
      ammo_class: CommaSeparatedString<string[]>
      ammo_current: number
      ammo_elapsed: number
      ammo_limit: number
      ammo_mag_size: number
      animation_slot: number
      bullet_bones: CommaSeparatedString<string[]>
      bullet_speed: number
      cam_dispersion: number
      cam_dispersion_frac: number
      cam_dispersion_inc: number
      cam_max_angle: number
      cam_max_angle_horz: number
      cam_relax_speed: number
      cam_relax_speed_ai: number
      cam_return: number
      cam_step_angle_horz: number
      cform: string
      class: string
      condition_queue_shot_dec: number
      condition_shot_dec: number
      control_inertion_factor: string
      cost: number
      crosshair_inertion: number
      default_to_ruck: boolean
      description: string
      discovery_dependency: string
      ef_main_weapon_type: number
      ef_weapon_type: number
      fire_dispersion_base: number
      fire_dispersion_condition_factor: number
      fire_distance: number
      fire_point: vector
      fire_point2: vector
      flame_particles: string
      grenade_launcher_status: number
      GroupControlSection: string
      hand_dependence: number
      hit_impulse: number
      hit_power: vector
      hit_probability_gd_master: number
      hit_probability_gd_novice: number
      hit_probability_gd_stalker: number
      hit_probability_gd_veteran: number
      hit_type: string
      holder_fov_modifier: number
      holder_range_modifier: number
      hud: string
      icons_texture: string
      inv_grid_height: number
      inv_grid_width: number
      inv_grid_x: number
      inv_grid_y: number
      inv_name: string
      inv_name_short: string
      inv_weight: number
      kill_msg_height: number
      kill_msg_width: number
      kill_msg_x: number
      kill_msg_y: number
      kind: string
      light_color: vector
      light_disabled: boolean
      light_range: number
      light_time: number
      light_var_color: number
      light_var_range: number
      max_radius: number
      min_radius: number
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_probability: number
      misfire_start_condition: number
      misfire_start_prob: number
      orientation: vector
      PDM_disp_accel_factor: number
      PDM_disp_base: number
      PDM_disp_crouch: number
      PDM_disp_crouch_no_acc: number
      PDM_disp_vel_factor: number
      ph_mass: number
      position: vector
      reload_dof: vector
      repair_type: string
      rpm: number
      rpm_empty_click: number
      scheduled: boolean
      scope_dynamic_zoom: boolean
      scope_name: string
      scope_status: number
      scope_texture: string
      scope_x: number
      scope_y: number
      shell_dir: vector
      shell_point: vector
      silencer_status: number
      single_handed: number
      slot: number
      smoke_particles: string
      sprint_allowed: boolean
      startup_ammo: number
      strap_bone0: string
      strap_bone1: string
      strap_orientation: vector
      strap_position: vector
      time_to_aim: number
      upgr_icon_height: number
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
      upgrade_scheme: string
      upgrades: CommaSeparatedString<string[]>
      use_aim_bullet: boolean
      visual: string
      weapon_class: string
      zoom_cam_dispersion: number
      zoom_cam_dispersion_frac: number
      zoom_cam_dispersion_inc: number
      zoom_cam_max_angle: number
      zoom_cam_max_angle_horz: number
      zoom_cam_relax_speed: number
      zoom_cam_relax_speed_ai: number
      zoom_cam_step_angle_horz: number
      zoom_enabled: boolean
      zoom_rotate_time: number
    }
    wpn_gauss_hud: {
      aim_hud_offset_pos: vector
      aim_hud_offset_pos_16x9: vector
      aim_hud_offset_rot: vector
      aim_hud_offset_rot_16x9: vector
      anm_bore: CommaSeparatedString<string[]>
      anm_bore_empty: CommaSeparatedString<string[]>
      anm_bore_jammed: CommaSeparatedString<string[]>
      anm_hide: CommaSeparatedString<string[]>
      anm_hide_empty: CommaSeparatedString<string[]>
      anm_hide_jammed: CommaSeparatedString<string[]>
      anm_idle: CommaSeparatedString<string[]>
      anm_idle_aim: CommaSeparatedString<string[]>
      anm_idle_aim_empty: CommaSeparatedString<string[]>
      anm_idle_aim_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch_empty: CommaSeparatedString<string[]>
      anm_idle_aim_moving_crouch_jammed: CommaSeparatedString<string[]>
      anm_idle_aim_moving_empty: CommaSeparatedString<string[]>
      anm_idle_aim_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_empty: CommaSeparatedString<string[]>
      anm_idle_jammed: CommaSeparatedString<string[]>
      anm_idle_moving: CommaSeparatedString<string[]>
      anm_idle_moving_empty: CommaSeparatedString<string[]>
      anm_idle_moving_jammed: CommaSeparatedString<string[]>
      anm_idle_sprint: CommaSeparatedString<string[]>
      anm_idle_sprint_empty: CommaSeparatedString<string[]>
      anm_idle_sprint_jammed: CommaSeparatedString<string[]>
      anm_reload: CommaSeparatedString<string[]>
      anm_reload_empty: CommaSeparatedString<string[]>
      anm_reload_misfire: CommaSeparatedString<string[]>
      anm_reload_misfire_empty: CommaSeparatedString<string[]>
      anm_shot_l: CommaSeparatedString<string[]>
      anm_shots: CommaSeparatedString<string[]>
      anm_shots_jammed: CommaSeparatedString<string[]>
      anm_show: CommaSeparatedString<string[]>
      anm_show_empty: CommaSeparatedString<string[]>
      anm_show_jammed: CommaSeparatedString<string[]>
      attach_place_idx: number
      fire_bone: string
      fire_point: vector
      gl_hud_offset_pos: vector
      gl_hud_offset_rot: vector
      hands_orientation: vector
      hands_orientation_16x9: vector
      hands_position: vector
      hands_position_16x9: vector
      item_orientation: vector
      item_position: vector
      item_visual: string
      lean_hud_offset_pos: vector
      lean_hud_offset_rot: vector
      lowered_hud_offset_pos: vector
      lowered_hud_offset_pos_16x9: vector
      lowered_hud_offset_rot: vector
      lowered_hud_offset_rot_16x9: vector
      shell_bone: string
      shell_dir: vector
      shell_point: vector
      zoom_hide_crosshair: boolean
    }
    pri_a17_gauss_rifle: Omit<ItemsWeaponsBaseIni['wpn_gauss'], '$spawn' | 'ammo_class' | 'ammo_current' | 'ammo_elapsed' | 'ammo_limit' | 'ammo_mag_size' | 'bullet_speed' | 'condition_queue_shot_dec' | 'condition_shot_dec' | 'description' | 'fire_distance' | 'hit_impulse' | 'hit_power' | 'hit_probability_gd_master' | 'hit_probability_gd_novice' | 'hit_probability_gd_stalker' | 'hit_probability_gd_veteran' | 'hit_type' | 'hud' | 'inv_name' | 'misfire_end_condition' | 'misfire_end_prob' | 'misfire_start_condition' | 'misfire_start_prob' | 'quest_item' | 'story_id' | 'upgr_icon_height' | 'upgr_icon_width' | 'upgr_icon_x' | 'upgr_icon_y'> & {
      $spawn: string
      ammo_class: CommaSeparatedString<string[]>
      ammo_current: number
      ammo_elapsed: number
      ammo_limit: number
      ammo_mag_size: number
      bullet_speed: number
      condition_queue_shot_dec: number
      condition_shot_dec: number
      description: string
      fire_distance: number
      hit_impulse: number
      hit_power: vector
      hit_probability_gd_master: number
      hit_probability_gd_novice: number
      hit_probability_gd_stalker: number
      hit_probability_gd_veteran: number
      hit_type: string
      hud: string
      inv_name: string
      misfire_end_condition: number
      misfire_end_prob: number
      misfire_start_condition: number
      misfire_start_prob: number
      quest_item: boolean
      story_id: string
      upgr_icon_height: number
      upgr_icon_width: number
      upgr_icon_x: number
      upgr_icon_y: number
    }
    wpn_gauss_sounds_new: {
      scripted_snd_bore_jammed: string
      scripted_snd_hide: string
      scripted_snd_hide_empty: string
      scripted_snd_hide_jammed: string
      scripted_snd_shots: string
      scripted_snd_show: CommaSeparatedString<string[]>
      scripted_snd_show_empty: string
      scripted_snd_show_jammed: string
      snd_bore: string
      snd_draw: string
      snd_empty: string
      snd_holster: string
      snd_reload: string
      snd_reload_empty: string
      snd_reload_empty1: string
      snd_reload_empty2: string
      snd_reload_misfire: string
      snd_reload1: string
      snd_reload2: string
      snd_shoot: string
      snd_shoot_actor: string
    }
    wpn_gauss_snd_shot: {
      snd_1_layer: string
      snd_2_layer: string
      snd_3_layer: string
      snd_4_layer: string
    }
    wpn_gauss_snd_shot_swp_actor: {
      snd_1_layer: string
      snd_2_layer: string
      snd_3_layer: string
      snd_4_layer: string
    }
  }
}
