// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `misc\\bridge.ltx`. Sections enumerated for autocomplete; `MiscBridgeIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface MiscBridgeIni {
  red_forest_bridge: {
    $prefetch: number
    $spawn: string
    class: string
    GroupControlSection: string
    remove_time: number
    script_binding: string
    visual: string
  }
  agru_door: {
    $prefetch: number
    $spawn: string
    class: string
    GroupControlSection: string
    remove_time: number
    script_binding: string
    visual: string
  }
}

interface IniFileSchemas {
  'misc\\bridge.ltx': MiscBridgeIni
}
