// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `misc\\effectors.ltx`. Sections enumerated for autocomplete; `MiscEffectorsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface MiscEffectorsIni {
    bobbing_effector: {
      limp_amplitude: number
      limp_speed: number
      run_amplitude: number
      run_speed: number
      walk_amplitude: number
      walk_speed: number
    }
    monster_attack_effector: {
      blur: number
      ce_amplitude: number
      ce_period_number: number
      ce_power: number
      ce_time: number
      color_add: vector
      color_base: vector
      color_gray: vector
      duality_h: number
      duality_v: number
      gray: number
      noise_fps: number
      noise_grain: number
      noise_intensity: number
      time: number
      time_attack: number
      time_release: number
    }
    small_monster_attack_effector: {
      blur: number
      ce_amplitude: number
      ce_period_number: number
      ce_power: number
      ce_time: number
      color_add: vector
      color_base: vector
      color_gray: vector
      duality_h: number
      duality_v: number
      gray: number
      noise_fps: number
      noise_grain: number
      noise_intensity: number
      time: number
      time_attack: number
      time_release: number
    }
    explode_effector: {
      effect_sect_name: string
    }
    sleep_effector: {
      blur: number
      color_add: vector
      color_base: vector
      color_gray: vector
      duality_h: number
      duality_v: number
      gray: number
      noise_fps: number
      noise_grain: number
      noise_intensity: number
      time: number
      time_attack: number
      time_release: number
    }
    zoom_inertion_effector: {
      camera_move_epsilon: number
      delta_time: number
      disp_min: number
      speed_min: number
      zoom_aim_disp_k: number
      zoom_aim_speed_k: number
    }
  }

  interface IniFileSchemas {
    'misc\\effectors.ltx': MiscEffectorsIni
  }
}
