// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `misc\\postprocess.ltx`. Sections enumerated for autocomplete; `MiscPostprocessIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface MiscPostprocessIni {
  postprocess_base: {
    blur: number
    duality_h: string
    duality_v: string
    gray: string
    noise: string
    noise_color: vector
    noise_scale: number
    pp_eff_name: string
  }
  postprocess_anomaly: {
    blur: number
    duality_h: number
    duality_v: number
    gray: string
    noise: string
    noise_color: vector
    noise_scale: number
    pp_eff_name: string
  }
  postprocess_steam_mine: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_acidic: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_acidic_mine: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_thermal: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_thermal_mine: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_rad: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_psi: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  psy_antenna: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  postprocess_death: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_flame: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_fuzz: {
    pp_eff_cyclic: number
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_gravi: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_gravi_mine: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_electra: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_electra_mine: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  mosquito_bald: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_gas: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  postprocess_new: {
    pp_eff_name: string
    radius_max: number
    radius_min: number
  }
  effector_alcohol: {
    cam_eff_cyclic: number
    cam_eff_name: string
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  alcohol: {
    cam_eff_cyclic: number
    cam_eff_name: string
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_explode_hit: {
    cam_eff_cyclic: number
    cam_eff_hud_affect: boolean
    cam_eff_name: string
  }
  effector_fire_hit: {
    cam_eff_cyclic: number
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_fire_hit_0: {
    cam_eff_name: string
  }
  effector_fire_hit_1: {
    cam_eff_name: string
  }
  effector_fire_hit_2: {
    cam_eff_name: string
  }
  effector_fire_hit_3: {
    cam_eff_name: string
  }
  effector_fire_hit_4: {
    cam_eff_name: string
  }
  effector_fire_hit_5: {
    cam_eff_name: string
  }
  effector_fire_hit_6: {
    cam_eff_name: string
  }
  effector_fire_hit_7: {
    cam_eff_name: string
  }
  snd_shock_effector: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_controller_aura: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_blink_black: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_controller_aura2: {
    cam_eff_cyclic: number
    pp_eff_cyclic: number
  }
  effector_monster_hit: {
    cam_eff_cyclic: number
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_monster_hit_0: {
    cam_eff_name: string
  }
  effector_monster_hit_1: {
    cam_eff_name: string
  }
  effector_monster_hit_2: {
    cam_eff_name: string
  }
  effector_monster_hit_3: {
    cam_eff_name: string
  }
  effector_monster_hit_4: {
    cam_eff_name: string
  }
  effector_monster_hit_5: {
    cam_eff_name: string
  }
  effector_monster_hit_6: {
    cam_eff_name: string
  }
  effector_monster_hit_7: {
    cam_eff_name: string
  }
  effector_nightvision_1: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_nightvision_2: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_nightvision_3: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  poltergeist_detection_effector: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  _actor_death_effector: {
    cam_eff_cyclic: number
    cam_eff_name: string
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    snd: string
  }
  brighten: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  fade_in: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  fade_in_out: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  black: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  blink: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  fade_to_black_9_sec: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  agr_u_fade: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
  }
  effector_radar_stop: {
    cam_eff_cyclic: number
    cam_eff_name: string
  }
  extra_controller: {
    pp_eff_cyclic: number
    pp_eff_name: string
    pp_eff_overlap: boolean
    radius_max: number
    radius_min: number
  }
  anti_aim_effector: {
    cam_eff_cyclic: number
    cam_eff_name: string
  }
}

interface IniFileSchemas {
  'misc\\postprocess.ltx': MiscPostprocessIni
}
