// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `misc\\secrets.ltx`. Sections enumerated for autocomplete; `MiscSecretsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface MiscSecretsIni {
  list: Record<string, string>
  pri_b36_tower_treasure: {
    ammo_gauss: CommaSeparatedString<string>
    medkit_army: CommaSeparatedString<string>
  }
  pri_b36_ground_treasure: {
    ammo_gauss: CommaSeparatedString<string>
    medkit_army: CommaSeparatedString<string>
  }
}

interface IniFileSchemas {
  'misc\\secrets.ltx': MiscSecretsIni
}
