// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `misc\\simulation.ltx`. Sections enumerated for autocomplete; `MiscSimulationIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface MiscSimulationIni {
    aes2_monolith_camp1: {
      monolith_sim_squad_advanced: number
    }
    aes2_monolith_camp2: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_veteran: number
    }
    aes2_monolith_camp3: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_veteran: number
    }
    aes2_monolith_camp4: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_veteran: number
    }
    aes2_monolith_snipers_1: {
      monolith_sim_squad_sniper: number
      monolith_sim_squad_veteran: number
    }
    aes2_monolith_snipers_2: {
      monolith_sim_squad_sniper: number
      monolith_sim_squad_veteran: number
    }
    aes2_monolith_snipers_3: {
      monolith_sim_squad_sniper: number
      monolith_sim_squad_veteran: number
    }
    aes2_monsters1: {
      simulation_chimera: number
      simulation_poltergeist_tele: number
    }
    aes2_monsters2: {
      simulation_gigant: number
      simulation_psy_dog: number
    }
    aes_smart_terrain_monolit_blockpost: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
      monolith_sim_squad_veteran: number
    }
    aes_smart_terrain_monolit_blockpost2: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_veteran: number
    }
    aes_smart_terrain_monolit_blockpost4: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_sniper: number
    }
    aes_smart_terrain_monsters1: {
      simulation_bloodsucker: number
      simulation_chimera: number
    }
    aes_smart_terrain_monsters2: {
      simulation_controller: number
      simulation_gigant: number
    }
    aes_smart_terrain_monsters3: {
      simulation_chimera: number
      simulation_psy_dog: number
    }
    aes_smart_terrain_monsters4: {
      simulation_gigant: number
      simulation_snork: number
    }
    aes_smart_terran_soldier: {
      monolith_sim_squad_veteran: number
    }
    aes_smart_terran_soldier2: {
      monolith_sim_squad_veteran: number
    }
    agr_smart_terrain_1_2: {
      per_yant_blood_agr_smart_terrain_1_2: number
    }
    agr_smart_terrain_1_3: {
      ecolog_sim_squad_advanced_1e_2ls: number
    }
    agr_smart_terrain_1_6: {
      agr_1_6_guards_army_mlr_squad: number
      army_sim_squad_advanced: number
      army_sim_squad_novice: number
      army_sim_squad_veteran: number
    }
    agr_smart_terrain_1_6_near_1: {
      army_sim_squad_advanced: number
      army_sim_squad_novice: number
      army_sim_squad_sniper: number
      army_sim_squad_veteran: number
    }
    agr_smart_terrain_1_6_near_2: {
      army_sim_squad_advanced: number
      army_sim_squad_novice: number
      army_sim_squad_sniper: number
      army_sim_squad_veteran: number
    }
    agr_smart_terrain_2_2: {
    }
    agr_smart_terrain_4_4: {
      ecolog_sim_squad_veteran: number
      stalker_sim_squad_advanced: number
    }
    agr_smart_terrain_4_4_near_1: {
      ecolog_sim_squad_advanced: number
      stalker_sim_squad_novice: number
    }
    agr_smart_terrain_4_4_near_2: {
      csky_sim_squad_advanced: number
    }
    agr_smart_terrain_4_4_near_3: {
    }
    agr_smart_terrain_4_6: {
    }
    agr_smart_terrain_5_2: {
    }
    agr_smart_terrain_5_3: {
    }
    agr_smart_terrain_5_7: {
    }
    agr_smart_terrain_6_4: {
    }
    agr_smart_terrain_7_5: {
    }
    agr_u_bandits: {
      agr_u_bandits_squad: number
    }
    agr_u_bloodsucker_1: {
    }
    agr_u_soldiers: {
    }
    agr_u_monsters: {
    }
    bar_dolg_bunker: {
      duty_sim_squad_advanced: number
      duty_sim_squad_novice: number
      duty_sim_squad_veteran: number
    }
    bar_dolg_general: {
      duty_sim_squad_advanced: number
      duty_sim_squad_novice: number
      duty_sim_squad_veteran: number
    }
    bar_visitors: {
      ecolog_sim_squad_advanced: number
      stalker_sim_squad_novice: number
      stalker_sim_squad_veteran: number
    }
    bar_zastava: string[]
    bar_zastava_2: string[]
    bar_zastava_dogs_lair: {
      simulation_dog_5_7: number
    }
    bar_zastava_dogs_lair_2: {
      simulation_mix_dogs: number
      simulation_pseudodog: number
    }
    bun_krovosos_nest: string[]
    cit_bandits: {
    }
    cit_bandits_2: {
    }
    cit_kanaliz1: {
    }
    cit_kanaliz2: {
    }
    cit_killers: {
      merc_sim_squad_veteran: number
    }
    cit_killers_2: {
      merc_sim_squad_advanced: number
      merc_sim_squad_veteran: number
    }
    cit_killers_vs_bandits: {
      merc_sim_squad_novice: number
    }
    zombie_smart_ds_mlr_1: {
    }
    zombie_smart_ds_mlr_2: {
    }
    mlr_terrain: {
      monolith_base_mlr_squad: number
      monolith_base_mlr2_squad: number
      monolith_base_mlra_squad: number
    }
    dar_angar: {
      simulation_fracture: number
    }
    dar_control_poltergeist: {
    }
    dar_poltergeist_tele: {
    }
    dar_poltergeist_tele_round: {
    }
    ds2_domik_st: {
      dasc_tech_mlr_squad: number
      dasc_trade_mlr_squad: number
      stalker_sim_squad_advanced: number
      stalker_sim_squad_novice: number
    }
    ds2_lager_st: {
      bandit_sim_squad_advanced: number
      bandit_sim_squad_novice: number
    }
    ds2_st_dogs: {
    }
    ds2_st_hoofs: {
    }
    ds_boars_nest: {
    }
    ds_deb1: {
    }
    ds_grverfer2: {
    }
    ds_kem1: {
    }
    ds_kem2: {
      army_sim_squad_advanced: number
      army_sim_squad_novice: number
      army_sim_squad_veteran: number
    }
    ds_kem3: {
      ds_kem3_bloodsucker_red: number
    }
    ds_ptr: {
    }
    ds_ptr2: {
    }
    ds_ptr3: {
    }
    ds_ptr4: {
    }
    esc_smart_terrain_1_11: {
    }
    esc_smart_terrain_2_12: {
      escape_novice_visiters_village: number
      stalker_sim_squad_novice: number
    }
    esc_smart_terrain_2_14: {
    }
    esc_smart_terrain_3_16: string[]
    esc_smart_terrain_3_7: {
    }
    esc_smart_terrain_4_11: {
    }
    esc_smart_terrain_4_13: {
    }
    esc_smart_terrain_4_9: {
    }
    esc_smart_terrain_5_12: {
    }
    esc_smart_terrain_5_2: {
    }
    esc_smart_terrain_5_4: {
    }
    esc_smart_terrain_5_6: {
    }
    esc_smart_terrain_5_7: {
      stalker_sim_squad_advanced: number
      stalker_sim_squad_novice: number
    }
    esc_smart_terrain_5_9: {
    }
    esc_smart_terrain_6_6: {
    }
    esc_smart_terrain_6_8: {
    }
    esc_smart_terrain_7_11: {
      bandit_sim_squad_novice: number
    }
    esc_smart_terrain_8_10: {
    }
    esc_smart_terrain_8_9: {
    }
    esc_smart_terrain_9_7: {
    }
    gar_smart_terrain_1_5: {
    }
    gar_smart_terrain_1_7: {
    }
    gar_smart_terrain_2_4: {
    }
    gar_smart_terrain_3_5: {
      stalker_sim_squad_novice: number
    }
    gar_smart_terrain_3_7: {
      ecolog_sim_squad_advanced: number
      stalker_sim_squad_advanced: number
    }
    gar_smart_terrain_4_2: {
    }
    gar_smart_terrain_4_5: {
    }
    gar_smart_terrain_5_2: {
      duty_sim_squad_advanced: number
      duty_sim_squad_novice: number
    }
    gar_smart_terrain_5_4: {
    }
    gar_smart_terrain_5_5: {
    }
    gar_smart_terrain_5_6: {
    }
    gar_smart_terrain_6_1: {
    }
    gar_smart_terrain_6_3: {
      stalker_gar_smart_terrain_6_3: number
    }
    gar_smart_terrain_6_6: {
    }
    gar_smart_terrain_6_7: {
    }
    gar_smart_terrain_7_4: {
    }
    gar_smart_terrain_8_5: {
    }
    gen_smart_terrain_cemetery: {
    }
    gen_smart_terrain_forest: {
    }
    gen_smart_terrain_junk: {
    }
    gen_smart_terrain_lab_entrance: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_sniper: number
      monolith_sim_squad_veteran: number
    }
    gen_smart_terrain_lab_entrance_2: {
      simulation_controller_psy: number
    }
    gen_smart_terrain_military: {
      monolith_sim_squad_veteran: number
    }
    gen_smart_terrain_urod: {
    }
    jup_a12: string[]
    jup_a6: {
      stalker_sim_squad_veteran: number
    }
    jup_b19: string[]
    jup_b200_tushkan_smart_terrain: string[]
    jup_b203: string[]
    jup_b204: string[]
    jup_b205_smart_terrain: string[]
    jup_b205_smart_terrain_tushkano: string[]
    jup_b208: {
    }
    depo_terrain: {
    }
    kbo_terrain: {
      monolith_kbo_squad: number
    }
    jup_b211: string[]
    jup_b41: string[]
    jup_b47: string[]
    jup_a10_smart_terrain: {
      simulation_bloodsucker_red: number
    }
    jup_b8_smart_terrain: string[]
    jup_sim_1: {
    }
    jup_sim_10: {
    }
    jup_sim_11: {
    }
    jup_sim_12: {
    }
    jup_sim_13: {
    }
    jup_sim_14: {
    }
    jup_sim_15: {
    }
    jup_sim_16: {
    }
    jup_sim_17: {
    }
    jup_sim_18: {
    }
    jup_sim_19: {
    }
    jup_sim_2: {
    }
    jup_sim_20: {
    }
    jup_sim_21: {
    }
    jup_sim_3: {
    }
    jup_sim_4: {
    }
    jup_sim_5: {
    }
    jup_sim_6: {
    }
    jup_sim_7: {
    }
    jup_sim_8: {
    }
    jup_sim_9: {
    }
    katacomb_smart_terrain: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
      monolith_sim_squad_veteran: number
    }
    lim_smart_terrain_1: {
    }
    lim_smart_terrain_10: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
      monolith_sim_squad_veteran: number
    }
    lim_smart_terrain_3: {
      merc_sim_squad_advanced: number
      merc_sim_squad_veteran: number
    }
    lim_smart_terrain_4: {
      merc_sim_squad_advanced: number
    }
    lim_smart_terrain_5: {
    }
    lim_smart_terrain_6: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
    }
    lim_smart_terrain_7: {
    }
    lim_smart_terrain_8: {
    }
    lim_smart_terrain_9: {
      monolith_sim_squad_novice: number
    }
    lx8_smart_terrain: string[]
    mar_smart_terrain_10_10: {
    }
    mar_smart_terrain_10_5: {
      army_sim_squad_advanced: number
      army_sim_squad_sniper: number
    }
    mar_smart_terrain_10_7: {
    }
    mar_smart_terrain_11_11: {
      renegade_sim_squad_advanced: number
      renegade_sim_squad_novice: number
    }
    mar_smart_terrain_11_3: {
    }
    mar_smart_terrain_12_2: {
      csky_sim_squad_advanced: number
      csky_sim_squad_novice: number
      stalker_sim_squad_novice: number
    }
    mar_smart_terrain_3_10: {
    }
    mar_smart_terrain_3_3: {
      renegade_sim_squad_advanced: number
      renegade_sim_squad_novice: number
    }
    mar_smart_terrain_3_7: {
    }
    mar_smart_terrain_4_5: {
    }
    mar_smart_terrain_4_7: {
    }
    mar_smart_terrain_5_12: {
      csky_sim_squad_advanced: number
      csky_sim_squad_novice: number
    }
    mar_smart_terrain_5_8: {
      csky_sim_squad_novice: number
      csky_sim_squad_veteran: number
    }
    mar_smart_terrain_6_10: {
    }
    mar_smart_terrain_6_11: {
      csky_sim_squad_advanced: number
      csky_sim_squad_novice: number
    }
    mar_smart_terrain_6_4: {
    }
    mar_smart_terrain_6_7: {
    }
    mar_smart_terrain_6_8: {
    }
    mar_smart_terrain_7_3: {
    }
    mar_smart_terrain_7_7: {
    }
    mar_smart_terrain_8_11: {
      renegade_sim_squad_advanced: number
      renegade_sim_squad_novice: number
    }
    mar_smart_terrain_8_4: {
    }
    mar_smart_terrain_8_8: {
    }
    mar_smart_terrain_8_9: {
    }
    mar_smart_terrain_base: {
      csky_sim_squad_novice: number
      csky_sim_squad_veteran: number
      guid_marsh_mlr_squad: number
    }
    mar_smart_terrain_doc: string[]
    mil_smart_terrain_2_1: {
    }
    mil_smart_terrain_2_10: {
      freedom_sim_squad_novice: number
    }
    mil_smart_terrain_2_2: {
      merc_sim_squad_advanced: number
      merc_sim_squad_novice: number
      merc_sim_squad_veteran: number
    }
    mil_smart_terrain_2_4: {
      bandit_sim_squad_advanced: number
    }
    mil_smart_terrain_2_6: {
    }
    mil_smart_terrain_3_8: {
      freedom_sim_squad_novice: number
    }
    mil_smart_terrain_4_2: {
    }
    mil_smart_terrain_4_3: {
    }
    mil_smart_terrain_4_5: {
      stalker_sim_squad_advanced: number
    }
    mil_smart_terrain_4_7: {
    }
    mil_smart_terrain_4_8: {
      freedom_sim_squad_veteran: number
    }
    mil_smart_terrain_7_10: {
      freedom_sim_squad_novice: number
    }
    mil_smart_terrain_7_12: {
      freedom_sim_squad_veteran: number
    }
    mil_smart_terrain_7_4: {
      duty_sim_squad_novice: number
      duty_sim_squad_veteran: number
    }
    mil_smart_terrain_7_7: {
      freedom_sim_squad_advanced: number
      freedom_sim_squad_novice: number
    }
    mil_smart_terrain_7_8: {
      freedom_sim_squad_veteran: number
    }
    mil_smart_terrain_8_3: {
    }
    pri_a15: {
      guid_pri_a15_mlr_squad: number
    }
    pri_a16_mlr_copy: string[]
    pri_a16: {
      start_prachka_squad: number
      trader_pri_a15_mlr_squad: number
    }
    pri_a17: string[]
    pri_a18_smart_terrain: {
      merc_hide_squad_on_book_store: number
    }
    pas_b400_canalisation: string[]
    pas_b400_downstairs: string[]
    pas_b400_elevator: string[]
    pas_b400_hall: string[]
    pas_b400_track: string[]
    pas_b400_tunnel: string[]
    pri_b303: string[]
    pri_b304_monsters_smart_terrain: string[]
    pri_b306: string[]
    pri_b36_smart_terrain: string[]
    pri_depot: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
      monolith_sim_squad_veteran: number
    }
    pri_monolith: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
      monolith_sim_squad_veteran: number
    }
    pri_sim_1: {
    }
    pri_sim_10: {
    }
    pri_sim_11: {
    }
    pri_sim_12: {
    }
    pri_sim_2: {
    }
    pri_sim_3: {
    }
    pri_sim_4: {
    }
    pri_sim_5: {
    }
    pri_sim_6: {
    }
    pri_sim_7: {
    }
    pri_sim_8: {
    }
    pri_sim_9: {
    }
    pri_smart_bloodsucker_lair1: {
    }
    pri_smart_controler_lair1: {
    }
    pri_smart_controler_lair2: {
    }
    pri_smart_giant_lair1: {
    }
    pri_smart_monolith_stalker2: {
      monolith_sim_squad_advanced: number
    }
    pri_smart_monolith_stalker3: {
      monolith_sim_squad_advanced: number
    }
    pri_smart_monolith_stalker4: {
      monolith_sim_squad_veteran: number
    }
    pri_smart_monolith_stalker6: {
      monolith_sim_squad_novice: number
      monolith_sim_squad_sniper: number
      monolith_sim_squad_veteran: number
    }
    pri_smart_monster_lair1: {
    }
    pri_smart_neutral_stalker1: {
      monolith_sim_squad_veteran: number
    }
    pri_smart_pseudodog_lair1: {
    }
    pri_smart_snork_lair1: {
    }
    pri_smart_snork_lair2: {
    }
    pri_smart_tushkano_lair1: {
    }
    rad2_loner_0000: {
    }
    rad2_loner_0001: {
    }
    rad2_loner_0002: {
    }
    rad2_prip_teleport: {
      monolith_sim_squad_veteran: number
    }
    rad_after_valley: {
    }
    rad_antenna_camper: {
      monolith_sim_squad_advanced: number
    }
    rad_antenna_monolith: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
    }
    rad_antenna_patrol: {
      monolith_sim_squad_veteran: number
    }
    rad_bloodsucker: {
    }
    rad_entrance: {
      monolith_sim_squad_advanced: number
      monolith_sim_squad_novice: number
    }
    rad_pseudodogs: {
    }
    rad_snork1: {
    }
    rad_snork2: {
    }
    rad_valley: {
    }
    rad_valley_dogs: {
    }
    rad_zombied1: {
    }
    rad_zombied2: {
    }
    red_smart_terrain_4_2: {
      stalkers_base_red_forest_mlr_squad: number
    }
    red_bridge_bandit_smart_skirmish: {
      monolith_sim_squad_advanced: number
    }
    red_smart_terrain_3_1: {
    }
    red_smart_terrain_3_2: string[]
    red_smart_terrain_3_3: {
    }
    red_smart_terrain_4_3: {
    }
    red_smart_terrain_4_5: {
    }
    red_smart_terrain_5_5: {
    }
    red_smart_terrain_5_6: {
      simulation_chimera: number
    }
    red_smart_terrain_6_3: {
      ecolog_sim_squad_advanced_2e_2ls_1ss: number
    }
    red_smart_terrain_6_6: {
    }
    red_smart_terrain_monsters: {
    }
    red_smart_terrain_monsters_2: {
    }
    red_smart_terrain_monsters_3: {
    }
    ros_smart_killers1: {
      bandit_sim_squad_advanced: number
      bandit_sim_squad_novice: number
    }
    ros_smart_monster4: {
    }
    ros_smart_monster5: {
    }
    ros_smart_monster7: {
    }
    ros_smart_poltergeist2: {
      simulation_poltergeist_tele: number
      simulation_snork: number
    }
    ros_smart_snork1: {
    }
    ros_smart_stalker1: {
      stalker_sim_squad_advanced: number
      stalker_sim_squad_veteran: number
    }
    ros_smart_stalker_killers1: {
      merc_sim_squad_advanced: number
      merc_sim_squad_novice: number
      merc_sim_squad_veteran: number
    }
    sar_monolith_general: string[]
    sar_monolith_sklad: string[]
    trc_sim_1: {
      bandit_sim_squad_veteran: number
    }
    trc_sim_10: {
      duty_sim_squad_veteran: number
    }
    trc_sim_11: {
    }
    trc_sim_12: {
      bandit_sim_squad_veteran: number
    }
    trc_sim_13: {
    }
    trc_sim_14: {
    }
    trc_sim_15: {
    }
    trc_sim_16: {
    }
    trc_sim_17: {
      freedom_sim_squad_veteran: number
    }
    trc_sim_18: {
      army_sim_squad_advanced: number
      army_sim_squad_veteran: number
    }
    trc_sim_19: {
    }
    trc_sim_2: {
      bandit_sim_squad_veteran: number
    }
    trc_sim_20: {
      bandit_sim_squad_advanced: number
    }
    trc_sim_21: {
    }
    trc_sim_3: {
    }
    trc_sim_4: {
      army_sim_squad_advanced: number
    }
    trc_sim_5: {
    }
    trc_sim_6: {
    }
    trc_sim_7: {
    }
    trc_sim_8: {
    }
    trc_sim_9: {
    }
    val_smart_terrain_1_2: {
      army_sim_squad_advanced: number
      army_sim_squad_sniper: number
      army_sim_squad_veteran: number
    }
    val_smart_terrain_3_0: {
    }
    val_smart_terrain_4_0: {
      stalker_sim_squad_advanced: number
      stalker_sim_squad_novice: number
    }
    val_smart_terrain_5_10: {
    }
    val_smart_terrain_6_4: {
    }
    val_smart_terrain_6_5: {
    }
    val_smart_terrain_7_3: {
      bandit_sim_squad_advanced: number
      bandit_sim_squad_novice: number
    }
    val_smart_terrain_7_4: {
      bandit_sim_squad_advanced: number
      bandit_sim_squad_veteran: number
    }
    val_smart_terrain_7_5: {
      bandit_sim_squad_novice: number
      bandit_sim_squad_veteran: number
    }
    val_smart_terrain_8_6: {
      bandit_sim_squad_novice: number
    }
    val_smart_terrain_8_7: {
    }
    val_smart_terrain_8_9: {
    }
    val_smart_terrain_9_10: {
    }
    val_smart_terrain_9_2: {
    }
    val_smart_terrain_9_4: {
      bandit_sim_squad_novice: number
    }
    val_smart_terrain_9_6: {
    }
    warlab_common_consciousness_smart_terrain: string[]
    yan_smart_terrain_2_4: {
      zombied_sim_squad_advanced: number
      zombied_sim_squad_veteran: number
    }
    yan_smart_terrain_2_5: {
      zombied_sim_squad_advanced: number
    }
    yan_smart_terrain_3_4: {
      zombied_sim_squad_novice: number
    }
    yan_smart_terrain_3_6: {
      ecolog_sim_squad_advanced: number
    }
    yan_smart_terrain_4_5: {
      simulation_snork_2_5: number
    }
    yan_smart_terrain_5_5: {
      ecolog_sim_squad_veteran: number
    }
    yan_smart_terrain_6_2: {
    }
    yan_smart_terrain_6_4: {
      ecolog_sim_squad_advanced: number
      ecolog_sim_squad_novice: number
      ecolog_sim_squad_veteran: number
    }
    yan_smart_terrain_zombi_spawn: {
      simulation_contr_3sn_3gzomb: number
    }
    zat_b100: string[]
    zat_b104_zombied: string[]
    zat_b18: string[]
    zat_b28: string[]
    zat_b33: string[]
    zat_b38: string[]
    zat_b39: string[]
    zat_b40_smart_terrain: string[]
    zat_b42_smart_terrain: {
      simulation_mix_boar_flesh: number
    }
    zat_b7: string[]
    zat_sim_1: {
    }
    zat_sim_10: {
    }
    zat_sim_11: {
    }
    zat_sim_12: {
    }
    zat_sim_13: {
    }
    zat_sim_14: {
    }
    zat_sim_15: {
    }
    zat_sim_16: {
    }
    zat_sim_17: {
    }
    zat_sim_18: {
    }
    zat_sim_19: {
    }
    zat_sim_2: {
    }
    zat_sim_20: {
    }
    zat_sim_21: {
    }
    zat_sim_22: {
    }
    zat_sim_23: {
    }
    zat_sim_24: {
    }
    zat_sim_25: {
    }
    zat_sim_26: {
    }
    zat_sim_27: {
    }
    zat_sim_28: {
    }
    zat_sim_29: {
    }
    zat_sim_3: {
    }
    zat_sim_30: {
    }
    zat_sim_4: {
    }
    zat_sim_5: {
    }
    zat_sim_6: {
    }
    zat_sim_7: {
    }
    zat_sim_8: {
    }
    zat_sim_9: {
    }
    zat_stalker_base_smart: string[]
    pol_smart_terrain_1_1: {
      pol_smart_terrain_1_1_squad: number
    }
    pol_smart_terrain_1_3: {
      pol_smart_terrain_1_3_squad: number
    }
    pol_smart_terrain_2_2: {
      simulation_burer: number
    }
    pol_smart_terrain_2_1: {
      simulation_poltergeist_tele: number
    }
  }

  interface IniFileSchemas {
    'misc\\simulation.ltx': MiscSimulationIni
  }
}
