// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `misc\\surge_manager.ltx`. Sections enumerated for autocomplete; `MiscSurgeManagerIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface MiscSurgeManagerIni {
  settings: {
    condlist: CommaSeparatedString<string>
    survive: CommaSeparatedString<string>
  }
  list: Record<string, string>
}

interface IniFileSchemas {
  'misc\\surge_manager.ltx': MiscSurgeManagerIni
}
