// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\faction_quick_travel.ltx`. Sections enumerated for autocomplete; `PluginsFactionQuickTravelIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsFactionQuickTravelIni {
  settings: {
    enable: boolean
  }
  stalker: Record<string, string>
  bandit: Record<string, string>
  csky: Record<string, string>
  army: Record<string, string>
  dolg: Record<string, string>
  freedom: Record<string, string>
  killer: Record<string, string>
  ecolog: Record<string, string>
  monolith: Record<string, string>
  renegade: Record<string, string>
  greh: Record<string, string>
  isg: Record<string, string>
  zombied: Record<string, string>
}

interface IniFileSchemas {
  'plugins\\faction_quick_travel.ltx': PluginsFactionQuickTravelIni
}
