// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\faction_quick_travel.ltx`. Sections enumerated for autocomplete; `PluginsFactionQuickTravelIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface PluginsFactionQuickTravelIni {
    settings: {
      enable: boolean
    }
    stalker: string[]
    bandit: string[]
    csky: string[]
    army: string[]
    dolg: string[]
    freedom: string[]
    killer: string[]
    ecolog: string[]
    monolith: string[]
    renegade: string[]
    greh: string[]
    isg: string[]
    zombied: string[]
  }

  interface IniFileSchemas {
    'plugins\\faction_quick_travel.ltx': PluginsFactionQuickTravelIni
  }
}
