// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\guaranteed_drops.ltx`. Sections enumerated for autocomplete; `PluginsGuaranteedDropsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsGuaranteedDropsIni {
  settings: {
    bandage: CommaSeparatedString<string>
  }
}

interface IniFileSchemas {
  'plugins\\guaranteed_drops.ltx': PluginsGuaranteedDropsIni
}
