// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\news_tips_icons.ltx`. Sections enumerated for autocomplete; `PluginsNewsTipsIconsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsNewsTipsIconsIni {
  news_tips_icons: {
    absolver: string
    all: string
    army: string
    artificer_eagerness: string
    bandit: string
    barman: string
    bookworm_food: string
    can_resupply: string
    collaborator: string
    common: string
    communication: string
    completionist: string
    csky: string
    death: string
    default: string
    deth: string
    disassemble: string
    dolg: string
    down_to_earth: string
    duga_free: string
    ecolog: string
    freedom: string
    geologist: string
    got_ammo: string
    got_artefact: string
    got_duty_heavy_armor: string
    got_duty_light_armor: string
    got_freedom_heavy_armor: string
    got_freedom_light_armor: string
    got_medicine: string
    greh: string
    griffith: string
    guide_unlock: string
    heavy_pockets: string
    infantile_pleasure: string
    infopreneur: string
    invictus: string
    iron_curtain: string
    isg: string
    killer: string
    leatherman_tool: string
    mechanized_warfare: string
    meeker: string
    monolith: string
    murky_spirit: string
    patriarch: string
    radiotherapy: string
    rag_and_bone: string
    rank_change: string
    recent_surge: string
    recycler: string
    renegade: string
    rep_change: string
    saharov: string
    signal: string
    silver_or_lead: string
    stalker: string
    surge: string
    swiss_knife: string
    tourist: string
    trader: string
    unforeseen_guest: string
    well_dressed: string
    wishful_thinking: string
    wolf: string
  }
}

interface IniFileSchemas {
  'plugins\\news_tips_icons.ltx': PluginsNewsTipsIconsIni
}
