// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\nimble_orders.ltx`. Sections enumerated for autocomplete; `PluginsNimbleOrdersIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsNimbleOrdersIni {
  settings: {
    item_count: number
    nimble_trade_instead: boolean
  }
  item_count: {
    category_1: number
    category_2: number
    category_3: number
    category_4: number
    category_5: number
    category_6: number
    category_7: number
  }
  costs_table: {
    category_1: vector
    category_2: vector
    category_3: vector
    category_4: vector
    category_5: vector
    category_6: vector
    category_7: vector
  }
  buy_item_table_1: Record<string, string>
  buy_item_table_2: Record<string, string>
  buy_item_table_3: Record<string, string>
  buy_item_table_4: Record<string, string>
  buy_item_table_5: {
    helm_hardhat: string
  }
  buy_item_table_6: Record<string, string>
  buy_item_table_7: Record<string, string>
}

interface IniFileSchemas {
  'plugins\\nimble_orders.ltx': PluginsNimbleOrdersIni
}
