// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\player_icons.ltx`. Sections enumerated for autocomplete; `PluginsPlayerIconsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsPlayerIconsIni {
  army_portraits: Record<string, string>
  bandit_portraits: Record<string, string>
  csky_portraits: Record<string, string>
  dolg_portraits: Record<string, string>
  ecolog_portraits: Record<string, string>
  freedom_portraits: Record<string, string>
  killer_portraits: Record<string, string>
  monolith_portraits: Record<string, string>
  stalker_portraits: Record<string, string>
  renegade_portraits: {
  }
  greh_portraits: Record<string, string>
  isg_portraits: Record<string, string>
  zombied_portraits: Record<string, string>
}

interface IniFileSchemas {
  'plugins\\player_icons.ltx': PluginsPlayerIconsIni
}
