// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\player_icons.ltx`. Sections enumerated for autocomplete; `PluginsPlayerIconsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface PluginsPlayerIconsIni {
    army_portraits: string[]
    bandit_portraits: string[]
    csky_portraits: string[]
    dolg_portraits: string[]
    ecolog_portraits: string[]
    freedom_portraits: string[]
    killer_portraits: string[]
    monolith_portraits: string[]
    stalker_portraits: string[]
    renegade_portraits: PluginsPlayerIconsIni['bandit_portraits']
    greh_portraits: string[]
    isg_portraits: string[]
    zombied_portraits: string[]
  }

  interface IniFileSchemas {
    'plugins\\player_icons.ltx': PluginsPlayerIconsIni
  }
}
