// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\radioactive_water_settings.ltx`. Sections enumerated for autocomplete; `PluginsRadioactiveWaterSettingsIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsRadioactiveWaterSettingsIni {
  settings: {
    enabled: boolean
    jupiter: number
    jupiter_underground: number
    k00_marsh: number
    k01_darkscape: number
    k02_trucks_cemetery: number
    l01_escape: number
    l02_garbage: number
    l03_agroprom: number
    l03u_agr_underground: number
    l04_darkvalley: number
    l04u_labx18: number
    l05_bar: number
    l06_rostok: number
    l07_military: number
    l08_yantar: number
    l08u_brainlab: number
    l09_deadcity: number
    l10_limansk: number
    l10_radar: number
    l10_red_forest: number
    l10u_bunker: number
    l11_hospital: number
    l11_pripyat: number
    l12_stancia: number
    l12_stancia_2: number
    l12u_control_monolith: number
    l12u_sarcofag: number
    l13_generators: number
    l13u_warlab: number
    labx8: number
    pripyat: number
    y04_pole: number
    zaton: number
  }
}

interface IniFileSchemas {
  'plugins\\radioactive_water_settings.ltx': PluginsRadioactiveWaterSettingsIni
}
