// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\radio_zone_fm.ltx`. Sections enumerated for autocomplete; `PluginsRadioZoneFmIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface PluginsRadioZoneFmIni {
    trx_radio_plyr: {
      number_of_playlists: number
    }
  }

  interface IniFileSchemas {
    'plugins\\radio_zone_fm.ltx': PluginsRadioZoneFmIni
  }
}
