// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\spawner_blacklist.ltx`. Sections enumerated for autocomplete; `PluginsSpawnerBlacklistIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsSpawnerBlacklistIni {
  ignore_sections: Record<string, string>
}

interface IniFileSchemas {
  'plugins\\spawner_blacklist.ltx': PluginsSpawnerBlacklistIni
}
