// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `plugins\\xr_sound.ltx`. Sections enumerated for autocomplete; `PluginsXrSoundIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface PluginsXrSoundIni {
  shared_radio_music: Record<string, string>
  agr_smart_terrain_1_6_radio: {
  }
  agr_smart_terrain_4_4_radio: {
  }
  agr_smart_terrain_1_6_near_2_radio: {
  }
  agr_smart_terrain_1_6_near_1_radio: {
  }
  bar_visitors_radio: {
  }
  val_smart_terrain_7_3_radio: {
  }
  gar_smart_terrain_3_5_radio: {
  }
  mar_smart_terrain_base_radio: {
  }
  esc_sidorovich_radio: {
  }
  red_forester_radio: {
  }
}

interface IniFileSchemas {
  'plugins\\xr_sound.ltx': PluginsXrSoundIni
}
