// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\actor_inventory_box.ltx`. Sections enumerated for autocomplete; `ScriptsActorInventoryBoxIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface ScriptsActorInventoryBoxIni {
  logic: {
    active: string
  }
  'ph_idle@open': {
    nonscript_usable: boolean
    tips: string
  }
}

interface IniFileSchemas {
  'scripts\\actor_inventory_box.ltx': ScriptsActorInventoryBoxIni
}
