// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\box_door_wood.ltx`. Sections enumerated for autocomplete; `ScriptsBoxDoorWoodIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsBoxDoorWoodIni {
    logic: {
      active: string
    }
    'ph_door@locked': {
      closed: boolean
      locked: boolean
      snd_close_start: string
      snd_close_stop: string
      snd_open_start: string
    }
    'ph_door@close': {
      closed: boolean
      locked: boolean
      on_use: string
      snd_close_start: string
      snd_close_stop: string
      snd_open_start: string
    }
    'ph_door@open': {
      closed: boolean
      locked: boolean
      on_use: string
      snd_close_start: string
      snd_close_stop: string
      snd_open_start: string
    }
  }

  interface IniFileSchemas {
    'scripts\\box_door_wood.ltx': ScriptsBoxDoorWoodIni
  }
}
