// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\door_locked.ltx`. Sections enumerated for autocomplete; `ScriptsDoorLockedIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsDoorLockedIni {
    logic: {
      active: string
    }
    'ph_door@locked': {
      locked: boolean
      snd_open_start: string
    }
  }

  interface IniFileSchemas {
    'scripts\\door_locked.ltx': ScriptsDoorLockedIni
  }
}
