// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\door.ltx`. Sections enumerated for autocomplete; `ScriptsDoorIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsDoorIni {
    logic: {
      active: string
    }
    'ph_door@unlocked': {
      closed: boolean
      locked: boolean
    }
  }

  interface IniFileSchemas {
    'scripts\\door.ltx': ScriptsDoorIni
  }
}
