// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\dummy.ltx`. Sections enumerated for autocomplete; `ScriptsDummyIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsDummyIni {
    logic: {
      active: string
    }
  }

  interface IniFileSchemas {
    'scripts\\dummy.ltx': ScriptsDummyIni
  }
}
