// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\ph_campfire.ltx`. Sections enumerated for autocomplete; `ScriptsPhCampfireIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsPhCampfireIni {
    logic: {
      active: string
    }
    'ph_idle@open': {
      nonscript_usable: boolean
      tips: string
    }
    collide: string[]
  }

  interface IniFileSchemas {
    'scripts\\ph_campfire.ltx': ScriptsPhCampfireIni
  }
}
