// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\ph_tent.ltx`. Sections enumerated for autocomplete; `ScriptsPhTentIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsPhTentIni {
    logic: {
      active: string
    }
    'ph_idle@open': {
      nonscript_usable: boolean
    }
    collide: string[]
  }

  interface IniFileSchemas {
    'scripts\\ph_tent.ltx': ScriptsPhTentIni
  }
}
