// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\sr_sleep.ltx`. Sections enumerated for autocomplete; `ScriptsSrSleepIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface ScriptsSrSleepIni {
  logic: {
    active: string
  }
  'sr_idle@wait': {
    on_actor_inside: CommaSeparatedString<string>
  }
  'sr_idle@run': {
    on_actor_outside: CommaSeparatedString<string>
    on_info: CommaSeparatedString<string>
    on_info2: string
  }
}

interface IniFileSchemas {
  'scripts\\sr_sleep.ltx': ScriptsSrSleepIni
}
