// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\sr_teleport_logic.ltx`. Sections enumerated for autocomplete; `ScriptsSrTeleportLogicIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface ScriptsSrTeleportLogicIni {
  logic: {
    active: string
  }
  'sr_idle@wait': {
    on_actor_inside: string
  }
  'sr_idle@run': {
    on_actor_outside: string
  }
}

interface IniFileSchemas {
  'scripts\\sr_teleport_logic.ltx': ScriptsSrTeleportLogicIni
}
