// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\sr_teleport_no_cofirm_logic.ltx`. Sections enumerated for autocomplete; `ScriptsSrTeleportNoCofirmLogicIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsSrTeleportNoCofirmLogicIni {
    logic: {
      active: string
    }
    'sr_idle@wait': {
      on_actor_inside: string
    }
    'sr_idle@run': {
      on_actor_outside: string
    }
  }

  interface IniFileSchemas {
    'scripts\\sr_teleport_no_cofirm_logic.ltx': ScriptsSrTeleportNoCofirmLogicIni
  }
}
