// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\tiski.ltx`. Sections enumerated for autocomplete; `ScriptsTiskiIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).
export { }

declare global {
  interface ScriptsTiskiIni {
    logic: {
      active: string
    }
    'ph_idle@close': {
      nonscript_usable: boolean
      on_info: string
      tips: string
    }
    'ph_idle@open': {
      on_info: string
      tips: string
    }
    collide: string[]
  }

  interface IniFileSchemas {
    'scripts\\tiski.ltx': ScriptsTiskiIni
  }
}
