// AUTO-GENERATED by `tsx src/scripts/gen-ini-schemas.ts`. Do not edit by hand.
// Schema of `scripts\\treasure_inventory_box.ltx`. Sections enumerated for autocomplete; `ScriptsTreasureInventoryBoxIni` is a
// mergeable interface — augment it to add sections. Field value types are
// conservative (multi-token values become branded separated-strings).

interface ScriptsTreasureInventoryBoxIni {
  logic: {
    active: string
  }
  'ph_idle@enable': {
    nonscript_usable: boolean
    tips: string
  }
}

interface IniFileSchemas {
  'scripts\\treasure_inventory_box.ltx': ScriptsTreasureInventoryBoxIni
}
