// AUTO-GENERATED by `tsx src/scripts/gen-sections.ts`. Do not edit by hand.
// Ambient back-compat aliases for the section-id types re-exported from 'anomaly-packer'.
// Kept so the hand-written game .d.ts that reference the bare `Section`/`AnySection`
// globals compile unchanged. Inline `import()` types keep this file an ambient script (no
// top-level import/export) — the aliases remain global. New code should import from
// 'anomaly-packer' directly; addons augment via `declare module 'anomaly-packer'`.

/** @deprecated prefer `import('anomaly-packer').Section.Item` */
type Section = import('anomaly-packer').Section.Item
/** @deprecated prefer `import('anomaly-packer').Section.Npc` */
type NpcSection = import('anomaly-packer').Section.Npc
/** @deprecated prefer `import('anomaly-packer').Section.Squad` */
type SquadSection = import('anomaly-packer').Section.Squad
/** @deprecated prefer `import('anomaly-packer').Section.All` */
type AnySection = import('anomaly-packer').Section.All
