// AUTO-GENERATED by `tsx src/scripts/gen-weather.ts`. Do not edit by hand.
// Vanilla Anomaly weather. Both registries are mergeable interfaces: an addon's
// own .d.ts can add entries (e.g. `interface Weathers { my_preset: 0 }`) and the
// derived unions grow automatically.
//   Weather      - weather presets (environment/weathers/*.ltx); level.set_weather.
//   WeatherCycle - weather cycles ([weather_cycles] in dynamic_weather_graphs.ltx).

interface Weathers {
  '[default]': 0
  default_clear: 0
  default_cloudy: 0
  default_rain: 0
  indoor: 0
  indoor_ambient: 0
  map: 0
  night: 0
  old_version_weather: 0
  stancia2: 0
  sun_shafts: 0
  w_clear1: 0
  w_clear2: 0
  w_cloudy1: 0
  w_cloudy2_dark: 0
  w_foggy1: 0
  w_foggy2: 0
  w_indoor_agr_underground: 0
  w_indoor_ambient: 0
  w_indoor_default: 0
  w_indoor_jupiter_underground: 0
  w_indoor_sarcofag: 0
  w_partly1: 0
  w_partly2: 0
  w_rain1: 0
  w_rain2: 0
  w_rain3: 0
  w_storm1: 0
  w_storm2: 0
}
type Weather = keyof Weathers

interface WeatherCycles {
  clear: 0
  cloudy: 0
  foggy: 0
  partly: 0
  rain: 0
  storm: 0
}
type WeatherCycle = keyof WeatherCycles
